//! Build-time sizing for proxima-patterns::alert per principle 12.
//!
//! Reads `proxima-notify.toml` at the crate root + applies optional
//! `PROXIMA_NOTIFY_<SECTION>_<KEY>` env-var overrides, emits a
//! generated constant module into `OUT_DIR/proxima_notify_sized.rs`.
//! The library `include!`s the generated file inside a `sized` module.

use std::env;
use std::fs;
use std::path::PathBuf;

use proxima_build::sizing::{SizingSource, require_nonzero};

fn require_pow2(name: &str, value: usize) -> usize {
    assert!(
        value.is_power_of_two(),
        "{name} must be a power of two (heapless::FnvIndexMap requirement); got {value}"
    );
    value
}

fn resolve(source: &SizingSource, section: &str, key: &str) -> i64 {
    source
        .resolve_int(section, key)
        .unwrap_or_else(|err| panic!("{err}"))
}

#[allow(clippy::expect_used)]
fn main() {
    // SizingSource::load only arms rerun-if-changed for the toml it reads;
    // printing any rerun-if-changed disables cargo's implicit whole-package
    // watch, so build.rs itself needs re-arming explicitly.
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let source = SizingSource::load(&manifest_dir, "proxima-notify.toml", "PROXIMA_NOTIFY")
        .unwrap_or_else(|err| panic!("{err}"));

    let label_key_max = require_nonzero(
        "alert.label_key_max",
        resolve(&source, "alert", "label_key_max"),
    );
    let label_val_max = require_nonzero(
        "alert.label_val_max",
        resolve(&source, "alert", "label_val_max"),
    );
    let labels_max = require_pow2(
        "alert.labels_max",
        require_nonzero("alert.labels_max", resolve(&source, "alert", "labels_max")),
    );
    let kind_max = require_nonzero("alert.kind_max", resolve(&source, "alert", "kind_max"));
    let payload_max = require_nonzero(
        "alert.payload_max",
        resolve(&source, "alert", "payload_max"),
    );

    let question_max = require_nonzero(
        "guidance.question_max",
        resolve(&source, "guidance", "question_max"),
    );
    let answer_max = require_nonzero(
        "guidance.answer_max",
        resolve(&source, "guidance", "answer_max"),
    );
    let context_max = require_nonzero(
        "guidance.context_max",
        resolve(&source, "guidance", "context_max"),
    );
    let responder_max = require_nonzero(
        "guidance.responder_max",
        resolve(&source, "guidance", "responder_max"),
    );

    let out_dir =
        PathBuf::from(env::var_os("OUT_DIR").unwrap_or_else(|| panic!("OUT_DIR set by cargo")));
    let out_path = out_dir.join("proxima_notify_sized.rs");
    let generated = format!(
        "// generated by build.rs from proxima-notify.toml — do not edit by hand.\n\
         //\n\
         // Override any cap at build time via PROXIMA_NOTIFY_<SECTION>_<KEY>.\n\
         \n\
         /// Max bytes per label KEY (UTF-8). Default 64.\n\
         pub const ALERT_LABEL_KEY_MAX:  usize = {label_key_max};\n\
         /// Max bytes per label VALUE (UTF-8). Default 256.\n\
         pub const ALERT_LABEL_VAL_MAX:  usize = {label_val_max};\n\
         /// Max number of label entries. Power of 2 for heapless::FnvIndexMap. Default 16.\n\
         pub const ALERT_LABELS_MAX:     usize = {labels_max};\n\
         /// Max bytes for AlertEvent::kind. Default 64.\n\
         pub const ALERT_KIND_MAX:       usize = {kind_max};\n\
         /// Max bytes for AlertEvent::payload (opaque bytes). Default 4096.\n\
         pub const ALERT_PAYLOAD_MAX:    usize = {payload_max};\n\
         \n\
         /// Max bytes for GuidanceQuestion::question. Default 4096.\n\
         pub const GUIDANCE_QUESTION_MAX:  usize = {question_max};\n\
         /// Max bytes for GuidanceAnswer::content. Default 4096.\n\
         pub const GUIDANCE_ANSWER_MAX:    usize = {answer_max};\n\
         /// Max bytes for GuidanceQuestion::context (postcard-encoded opaque). Default 4096.\n\
         pub const GUIDANCE_CONTEXT_MAX:   usize = {context_max};\n\
         /// Max bytes for GuidanceAnswer::responder identifier. Default 128.\n\
         pub const GUIDANCE_RESPONDER_MAX: usize = {responder_max};\n",
    );
    fs::write(&out_path, generated).unwrap_or_else(|err| panic!("write sized.rs: {err}"));
}
