//! Build-time sizing for proxima-notify per principle 12.
//!
//! Reads `proxima-notify.toml` at the crate root + applies optional
//! `PROXIMA_NOTIFY_<SECTION>_<KEY>` env-var overrides, emits a
//! generated constant module into `OUT_DIR/proxima_notify_proto_sized.rs`.
//! The library `include!`s the generated file inside a `sized` module.

use std::env;
use std::fs;
use std::path::PathBuf;

use toml::Value;

fn require_nonzero(name: &str, value: u64) -> u64 {
    assert!(value > 0, "{name} must be non-zero; got {value}");
    value
}

fn require_pow2(name: &str, value: u64) -> u64 {
    assert!(
        value.is_power_of_two(),
        "{name} must be a power of two (heapless::FnvIndexMap requirement); got {value}"
    );
    value
}

fn require_usize(name: &str, value: u64) -> usize {
    usize::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows usize"))
}

fn read_int(table: &Value, section: &str, key: &str) -> u64 {
    let raw = table
        .get(section)
        .and_then(|sec| sec.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| panic!("proxima-notify.toml: missing or non-integer [{section}].{key}"));
    u64::try_from(raw).unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
}

fn resolve(table: &Value, section: &str, key: &str) -> u64 {
    let env_name = format!(
        "PROXIMA_NOTIFY_{section}_{key}",
        section = section.to_uppercase(),
        key = key.to_uppercase()
    );
    println!("cargo:rerun-if-env-changed={env_name}");
    if let Ok(raw) = env::var(&env_name) {
        raw.parse::<u64>()
            .unwrap_or_else(|err| panic!("{env_name}={raw} must parse as u64: {err}"))
    } else {
        read_int(table, section, key)
    }
}

#[allow(clippy::expect_used)]
fn main() {
    println!("cargo:rerun-if-changed=proxima-notify.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let toml_text = fs::read_to_string("proxima-notify.toml")
        .unwrap_or_else(|err| panic!("read proxima-notify.toml: {err}"));
    let toml_table: Value =
        toml::from_str(&toml_text).unwrap_or_else(|err| panic!("parse proxima-notify.toml: {err}"));

    let label_key_max = require_usize(
        "alert.label_key_max",
        require_nonzero(
            "alert.label_key_max",
            resolve(&toml_table, "alert", "label_key_max"),
        ),
    );
    let label_val_max = require_usize(
        "alert.label_val_max",
        require_nonzero(
            "alert.label_val_max",
            resolve(&toml_table, "alert", "label_val_max"),
        ),
    );
    let labels_max = require_usize(
        "alert.labels_max",
        require_pow2(
            "alert.labels_max",
            require_nonzero(
                "alert.labels_max",
                resolve(&toml_table, "alert", "labels_max"),
            ),
        ),
    );
    let kind_max = require_usize(
        "alert.kind_max",
        require_nonzero("alert.kind_max", resolve(&toml_table, "alert", "kind_max")),
    );
    let payload_max = require_usize(
        "alert.payload_max",
        require_nonzero(
            "alert.payload_max",
            resolve(&toml_table, "alert", "payload_max"),
        ),
    );

    let question_max = require_usize(
        "guidance.question_max",
        require_nonzero(
            "guidance.question_max",
            resolve(&toml_table, "guidance", "question_max"),
        ),
    );
    let answer_max = require_usize(
        "guidance.answer_max",
        require_nonzero(
            "guidance.answer_max",
            resolve(&toml_table, "guidance", "answer_max"),
        ),
    );
    let context_max = require_usize(
        "guidance.context_max",
        require_nonzero(
            "guidance.context_max",
            resolve(&toml_table, "guidance", "context_max"),
        ),
    );
    let responder_max = require_usize(
        "guidance.responder_max",
        require_nonzero(
            "guidance.responder_max",
            resolve(&toml_table, "guidance", "responder_max"),
        ),
    );

    let out_dir =
        PathBuf::from(env::var_os("OUT_DIR").unwrap_or_else(|| panic!("OUT_DIR set by cargo")));
    let out_path = out_dir.join("proxima_notify_sized.rs");
    let generated = format!(
        "// generated by build.rs from proxima-notify.toml — do not edit by hand.\n\
         //\n\
         // Override any cap at build time via PROXIMA_NOTIFY_<SECTION>_<KEY>.\n\
         \n\
         /// Max bytes per label KEY (UTF-8). Default 64.\n\
         pub const ALERT_LABEL_KEY_MAX:  usize = {label_key_max};\n\
         /// Max bytes per label VALUE (UTF-8). Default 256.\n\
         pub const ALERT_LABEL_VAL_MAX:  usize = {label_val_max};\n\
         /// Max number of label entries. Power of 2 for heapless::FnvIndexMap. Default 16.\n\
         pub const ALERT_LABELS_MAX:     usize = {labels_max};\n\
         /// Max bytes for AlertEvent::kind. Default 64.\n\
         pub const ALERT_KIND_MAX:       usize = {kind_max};\n\
         /// Max bytes for AlertEvent::payload (opaque bytes). Default 4096.\n\
         pub const ALERT_PAYLOAD_MAX:    usize = {payload_max};\n\
         \n\
         /// Max bytes for GuidanceQuestion::question. Default 4096.\n\
         pub const GUIDANCE_QUESTION_MAX:  usize = {question_max};\n\
         /// Max bytes for GuidanceAnswer::content. Default 4096.\n\
         pub const GUIDANCE_ANSWER_MAX:    usize = {answer_max};\n\
         /// Max bytes for GuidanceQuestion::context (postcard-encoded opaque). Default 4096.\n\
         pub const GUIDANCE_CONTEXT_MAX:   usize = {context_max};\n\
         /// Max bytes for GuidanceAnswer::responder identifier. Default 128.\n\
         pub const GUIDANCE_RESPONDER_MAX: usize = {responder_max};\n",
    );
    fs::write(&out_path, generated).unwrap_or_else(|err| panic!("write sized.rs: {err}"));
}
