//! substrate-native telemetry for proxima: traces, metrics, logs, events.
//!
//! the primitives below (ring, id, level, clock, tag, trace, metric, log,
//! recorder, native exporter, config) are structural -- always-on. only
//! consumer-facing toggles remain as features (\, \,
//! \, \). see \ for the
//! historical build-order log (c1..c15) that produced this substrate.
//!
//! \ carries the pre-component proxima Metrics/Labels/TelemetryHandle
//! surface that production code still uses; new code emits via \.
//!
//! Tiers: `std` (default) is the full runtime — recorder (per-core TLS + drainer
//! thread), config loading, native/otlp exporters, pipes. `alloc` (no_std) is the
//! data + primitive layer — tag, trace records, log, metric, sampler, ring. The
//! floor (no features) is no_std + no_alloc: `sized` + `id` + `error` +
//! `trace::{status, kind, clock}` — the Copy/core types that never touch a `Tag`.

#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(feature = "alloc")]
extern crate alloc;

/// Build-time sizing constants generated by `build.rs` from
/// `proxima-telemetry.toml` + optional `PROXIMA_TELEMETRY_*` env overrides. These
/// are the compile-time DEFAULTS for the drain / elastic-assist batch sizes; the
/// per-process surface is the runtime `config::TelemetryConfig` (drain_batch /
/// assist_batch), which overrides them via file / env / fluent builder.
pub mod sized {
    include!(concat!(env!("OUT_DIR"), "/proxima_telemetry_sized.rs"));
}

/// Is `severity` enabled at the build-time emit floor (`sized::EMIT_COMPILE_FLOOR`,
/// from `build.rs` `[emit] max_level`)?
///
/// A `const fn` over a `const`, so a call with a literal severity folds to a
/// compile-time `bool`: a statically-below-floor level emits ZERO runtime code,
/// at every tier including no_std + no_alloc (where there is no runtime
/// `CompiledEmit`). The compile-time half of the emit filter — proxima's analogue
/// of tracing's `max_level_*` features, driven by proxima's build config. Pair it
/// with the runtime [`emit::CallsiteGate`] (the disabled-fast-path cache) on the
/// `std`/`alloc` tiers.
///
/// ```
/// # use proxima_telemetry::emit_statically_enabled;
/// // folds at compile time — usable in `const` context, so a guarded emit below
/// // the floor is dead code the optimizer deletes (zero runtime cost).
/// const KEEPS_ERROR: bool = emit_statically_enabled(17); // error severity
/// assert!(KEEPS_ERROR); // default floor is trace (1), so error is enabled
/// ```
#[must_use]
pub const fn emit_statically_enabled(severity: u8) -> bool {
    severity >= sized::EMIT_COMPILE_FLOOR
}

// T0 — no_std + no_alloc floor: Copy/core only, no `Tag`, no heap, no
// proxima-pipe. `error` + `id` + `trace::{status, kind}` + `sized`.
pub mod error;

// `id` is the W3C trace/span identifier layer that proxima-telemetry owns
// outright: fixed-size byte arrays + `core::fmt` only, no heap, no
// proxima-pipe. Kept at the T0 floor (un-gated) so it's reachable on bare
// metal, same as `error` and `trace::{status, kind}`.
pub mod id;

// trace is always-on; its Copy submodules (status / kind) are T0, while the
// record types (span / event / link / tracestate) and the `Clock` re-export gate
// to `alloc` inside the module — so `trace::SpanKind` is reachable on bare metal
// while `SpanRecord` is not.
pub mod trace;

// T1 — no_std + alloc: the data + primitive layer.
#[cfg(feature = "alloc")]
pub mod clock;
#[cfg(feature = "emit")]
pub mod emit;
#[cfg(feature = "alloc")]
pub mod level;
#[cfg(feature = "alloc")]
pub mod log;
#[cfg(feature = "alloc")]
pub mod metric;
#[cfg(feature = "alloc")]
// ring moved to proxima-core (no_std concurrency primitive); re-exported so
// `crate::ring::*` and `proxima_telemetry::ring::*` keep resolving.
pub use proxima_core::ring;
// W3C traceparent/baggage header codec over `proxima_primitives::pipe::HeaderList` —
// needs `alloc` for `Bytes`/`HeaderList`; proxima-pipe's own trace-context
// byte fields (`RequestContext::trace_id`/`baggage`) are populated by callers
// through this module, so proxima-pipe never depends on proxima-telemetry.
#[cfg(feature = "alloc")]
pub mod propagation;
// scoped current-span for log/metric correlation; std keeps a thread-local LIFO
// stack, no_std degrades to `None`.
#[cfg(feature = "alloc")]
pub mod current;
#[cfg(feature = "alloc")]
pub mod sampler;
#[cfg(feature = "alloc")]
pub mod spanned;
#[cfg(feature = "alloc")]
pub mod tag;

// T2 — std: the runtime (recorder, config loading, exporters, pipes, legacy).
#[cfg(feature = "std")]
mod legacy;
#[cfg(feature = "std")]
pub use legacy::{
    HistogramSummary, Labels, Metrics, MetricsSnapshot, NoopTelemetry, ShardedHistogram, Telemetry,
    TelemetryHandle,
};
#[cfg(feature = "std")]
pub mod capture;
#[cfg(feature = "std")]
pub mod config;
// ring-buffered log capture + live-tail fanout (folded in from the former
// proxima-log-buffer satellite crate) — needs dashmap + arc-swap + Notify,
// so it rides the std tier alongside the rest of the runtime.
#[cfg(feature = "std")]
pub mod log_buffer;
// shared per-field merge core for every hand-rolled `XxxLayerBuilder`
// (config, emit::config, metric::instrument_config) — not part of the
// public API.
#[cfg(feature = "std")]
pub(crate) mod config_merge;
#[cfg(feature = "std")]
pub mod export;
#[cfg(feature = "std")]
pub mod out;
#[cfg(feature = "std")]
pub mod pipes;
#[cfg(feature = "std")]
pub mod recorder;

#[cfg(feature = "macros")]
pub use proxima_macros::{SpanCarrier, instrument, span};

#[cfg(feature = "tracing-init")]
pub mod tracing_bridge;
