// build-time sizing for omega's MSL kernel selection — mirrors
// `proxima-tensor/build.rs`'s `emit_sizing_consts`/`resolve_int` shape over
// `proxima-tensor-runtime.toml`, instantiated here for `omega-runtime.toml`
// instead. See `src/sized.rs`'s module doc for the two-family split this
// generated module feeds.
use std::env;
use std::fs;
use std::path::PathBuf;

use toml::Value;

fn main() {
    emit_sizing_consts();
}

fn require_nonzero(name: &str, value: i64) -> usize {
    let value = usize::try_from(value)
        .unwrap_or_else(|_| panic!("{name} must be a non-negative integer; got {value}"));
    assert!(value > 0, "{name} must be non-zero");
    value
}

fn get_int(table: &Value, section: &str, key: &str) -> i64 {
    table
        .get(section)
        .and_then(|section_value| section_value.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| panic!("omega-runtime.toml: missing or non-integer [{section}].{key}"))
}

/// like `get_int`, but an `OMEGA_<SECTION>_<KEY>` env var overrides the TOML
/// value when present — mirrors `proxima-tensor/build.rs`'s `resolve_int`
/// (principle 12: every override consulted emits its own
/// `cargo:rerun-if-env-changed` line, so a cached build never ignores it).
fn resolve_int(table: &Value, section: &str, key: &str) -> i64 {
    let env_name = format!(
        "OMEGA_{section}_{key}",
        section = section.to_uppercase(),
        key = key.to_uppercase()
    );
    println!("cargo:rerun-if-env-changed={env_name}");
    match env::var(&env_name) {
        Ok(raw) => raw
            .parse::<i64>()
            .unwrap_or_else(|err| panic!("{env_name}={raw} must parse as i64: {err}")),
        Err(_) => get_int(table, section, key),
    }
}

/// Reads `omega-runtime.toml`, emits `OUT_DIR/omega_sized.rs`. Only
/// `tiled_gemm.min_tokens` exists today; a new execution-policy key follows
/// the same `resolve_int` + `require_nonzero` + generated-`pub const` shape.
/// `TILED_GEMM_MIN_TOKENS` is `feature = "metal-tiled-gemm"`-only in
/// `src/sized.rs` (the tiled path has no meaning without it), so this only
/// emits the line when Cargo reports the feature active for THIS build — on
/// every other build the generated file simply omits it, keeping the private
/// `generated` module free of an unreferenced (dead-code-linted) constant,
/// the same convention `proxima-tensor/build.rs`'s
/// `CARGO_FEATURE_COHORT_STAGED_GRAPH` branch uses.
#[allow(clippy::expect_used)]
fn emit_sizing_consts() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let toml_path = PathBuf::from(&manifest_dir).join("omega-runtime.toml");
    println!("cargo:rerun-if-changed=omega-runtime.toml");

    let text = fs::read_to_string(&toml_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
    let root: Value = text
        .parse()
        .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

    let mut out = String::from("// AUTO-GENERATED by build.rs from omega-runtime.toml. DO NOT EDIT.\n");

    if env::var_os("CARGO_FEATURE_METAL_TILED_GEMM").is_some() {
        let min_tokens = require_nonzero(
            "tiled_gemm.min_tokens",
            resolve_int(&root, "tiled_gemm", "min_tokens"),
        );
        out.push_str(&format!("pub const TILED_GEMM_MIN_TOKENS: u64 = {min_tokens};\n"));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("omega_sized.rs");
    fs::write(&out_path, out).unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}
