//! Build-time sizing for proxima-telemetry.
//!
//! Reads `proxima-telemetry.toml` at the crate root + applies optional
//! per-system env-var overrides, emitting a generated constant module into
//! `OUT_DIR/proxima_telemetry_sized.rs`. The library `include!`s the generated
//! file inside a `sized` module.
//!
//! These are the compile-time DEFAULTS. The per-process surface is the runtime
//! conflaguration `TelemetryConfig` (`drain_batch` / `assist_batch`), which
//! overrides them via config file / env / fluent builder.
//!
//! Env-var override naming: `PROXIMA_TELEMETRY_<SECTION>_<KEY>`
//! (e.g. `PROXIMA_TELEMETRY_DRAIN_ASSIST_BATCH=32`). Downstream consumers that
//! re-brand their own surface map their config onto these via the runtime
//! `TelemetryConfig` API, not by setting these build vars directly.
//!
//! Also emits the `log_buffer` module's sizing (folded in from the former
//! `proxima-log-buffer` satellite crate): reads `proxima-log-buffer.toml` +
//! `PROXIMA_LOG_BUFFER_<SECTION>_<KEY>` env overrides into
//! `OUT_DIR/proxima_log_buffer_sized.rs`, unchanged from that crate's own
//! build-time contract.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use proxima_build::sizing::{SizingError, SizingSource, require_nonzero};

/// Resolve the compile-time emit floor: `[emit] max_level` (a level name) with a
/// `PROXIMA_TELEMETRY_EMIT_MAX_LEVEL` env override, mapped to proxima severity.
/// `trace` (1) keeps everything; `off` (255) compiles out all emits. The key
/// is optional (unlike every other resolved key here): missing anywhere
/// defaults to `"trace"`, matching the pre-`SizingSource` fallback.
fn resolve_emit_floor(source: &SizingSource) -> u8 {
    let name = match source.resolve_str("emit", "max_level") {
        Ok(value) => value,
        Err(SizingError::MissingStr { .. }) => "trace".to_string(),
        Err(err) => panic!("{err}"),
    };
    match name.to_ascii_lowercase().as_str() {
        "trace" => 1,
        "debug" => 5,
        "info" => 9,
        "warn" => 13,
        "error" => 17,
        "fatal" => 21,
        "off" => u8::MAX,
        other => {
            panic!("[emit].max_level = {other:?}: expected trace|debug|info|warn|error|fatal|off")
        }
    }
}

#[allow(clippy::expect_used)]
fn emit_sizing_consts(out_dir: &Path) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let source = SizingSource::load(&manifest_dir, "proxima-telemetry.toml", "PROXIMA_TELEMETRY")
        .unwrap_or_else(|err| panic!("{err}"));
    let resolve = |section: &str, key: &str| {
        source
            .resolve_int(section, key)
            .unwrap_or_else(|err| panic!("{err}"))
    };

    let drain_batch = require_nonzero("drain.batch", resolve("drain", "batch"));
    let assist_batch = require_nonzero("drain.assist_batch", resolve("drain", "assist_batch"));
    let flush_interval_micros = require_nonzero(
        "pump.flush_interval_micros",
        resolve("pump", "flush_interval_micros"),
    );
    let emit_floor = resolve_emit_floor(&source);
    // unified-instrument compile-time defaults (the no_std+no_alloc config floor).
    let instrument_metrics = resolve("instrument", "metrics") != 0;
    let instrument_default_budget_micros = resolve("instrument", "default_budget_micros");
    let sink_capacity_bytes =
        require_nonzero("sink.capacity_bytes", resolve("sink", "capacity_bytes"));
    // error-elevation caps (feature `elevation`): bound the per-trace replay
    // buffer's memory. Always emitted; consumed only under the feature.
    let elevation_max_traces =
        require_nonzero("elevation.max_traces", resolve("elevation", "max_traces"));
    let elevation_per_trace_ring = require_nonzero(
        "elevation.per_trace_ring",
        resolve("elevation", "per_trace_ring"),
    );

    let out = format!(
        "// AUTO-GENERATED by build.rs from proxima-telemetry.toml. DO NOT EDIT.\n\
         /// Records a background drain pass moves+exports per ring per pass (default cap).\n\
         pub const DRAIN_BATCH: usize = {drain_batch};\n\
         /// Records a producer drains+exports on a full ring before retrying its push.\n\
         pub const DRAIN_ASSIST_BATCH: usize = {assist_batch};\n\
         /// Managed pump time-trigger flush interval in microseconds (default).\n\
         pub const FLUSH_INTERVAL_MICROS: u64 = {flush_interval_micros};\n\
         /// Compile-time emit severity floor (build.rs `[emit] max_level`): a record\n\
         /// below this severity is statically disabled. 1=trace .. 21=fatal, 255=off.\n\
         pub const EMIT_COMPILE_FLOOR: u8 = {emit_floor};\n\
         /// Unified-instrument default: does a recorder consume the span-duration\n\
         /// metric by default (the consumer gate)? At no_std+no_alloc this const IS\n\
         /// the config; at std it seeds `InstrumentConfig`.\n\
         pub const INSTRUMENT_METRICS_DEFAULT: bool = {instrument_metrics};\n\
         /// Unified-instrument default tail-sampling budget (microseconds) for spans\n\
         /// without an explicit `#[span(budget)]`. 0 = none.\n\
         pub const INSTRUMENT_DEFAULT_BUDGET_MICROS: u64 = {instrument_default_budget_micros};\n\
         /// Preallocation (bytes) for the terminal batch buffer. At no_std+no_alloc\n\
         /// this const IS the reserved buffer size; at std it is the build-time default.\n\
         pub const SINK_CAPACITY_BYTES: usize = {sink_capacity_bytes};\n\
         /// Error-elevation hard count-cap: max concurrently-buffered traces before\n\
         /// the least-recently-touched trace's replay buffer is evicted (OOM backstop).\n\
         pub const ELEVATION_MAX_TRACES: usize = {elevation_max_traces};\n\
         /// Error-elevation per-trace replay ring capacity (records); DropOldest past it.\n\
         pub const ELEVATION_PER_TRACE_RING: usize = {elevation_per_trace_ring};\n",
    );

    let out_path = out_dir.join("proxima_telemetry_sized.rs");
    fs::write(&out_path, out).unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}

#[allow(clippy::expect_used)]
fn emit_log_buffer_sizing_consts(out_dir: &Path) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let source = SizingSource::load(
        &manifest_dir,
        "proxima-log-buffer.toml",
        "PROXIMA_LOG_BUFFER",
    )
    .unwrap_or_else(|err| panic!("{err}"));

    let capacity = require_nonzero(
        "buffer.capacity",
        source
            .resolve_int("buffer", "capacity")
            .unwrap_or_else(|err| panic!("{err}")),
    );
    let live_tail_channel_capacity = require_nonzero(
        "live_tail.channel_capacity",
        source
            .resolve_int("live_tail", "channel_capacity")
            .unwrap_or_else(|err| panic!("{err}")),
    );

    let out = format!(
        "// AUTO-GENERATED by build.rs from proxima-log-buffer.toml. DO NOT EDIT.\n\
         /// Retained ring-buffer capacity (lines) for a `LogBuffer` (default cap).\n\
         /// At no_std+no_alloc this const IS the ring's reserved size; at std it\n\
         /// seeds `LogBufferConfig::capacity`.\n\
         pub const LOG_BUFFER_CAPACITY_DEFAULT: usize = {capacity};\n\
         /// Per-subscriber live-tail queue capacity (default cap). At\n\
         /// no_std+no_alloc this const IS the queue's reserved size; at std it\n\
         /// seeds `LogBufferConfig::live_tail_channel_capacity`.\n\
         pub const LIVE_TAIL_CHANNEL_CAPACITY_DEFAULT: usize = {live_tail_channel_capacity};\n",
    );

    let out_path = out_dir.join("proxima_log_buffer_sized.rs");
    fs::write(&out_path, out).unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}

#[allow(clippy::expect_used)]
fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    emit_sizing_consts(&out_dir);
    emit_log_buffer_sizing_consts(&out_dir);
}
