//! Build-time config baking — the no-runtime tier of conflaguration.
//!
//! There is no `std::env`, no config file loader, and no runtime resolution
//! step in the compiled `#![no_std]` crate: `no-std.toml` is read exactly
//! once, here, on the host, and its two values are baked into `pub const`s
//! at `OUT_DIR/no_std_config.rs`. This mirrors `proxima-primitives/build.rs`,
//! which bakes `RETRY_STATUS_CAP` from `proxima-primitives.toml` the same
//! way — the same recipe, minimal enough to read end-to-end in one file.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use toml::Value;

fn require_nonzero(name: &str, value: u64) -> u64 {
    assert!(value > 0, "{name} must be non-zero; got {value}");
    value
}

fn require_usize(name: &str, value: u64) -> usize {
    usize::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows usize"))
}

fn get_int(table: &Value, section: &str, key: &str) -> u64 {
    let raw = table
        .get(section)
        .and_then(|section_table| section_table.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| panic!("no-std.toml: missing or non-integer [{section}].{key}"));
    u64::try_from(raw).unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
}

#[allow(clippy::expect_used)]
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let toml_path = Path::new(&manifest_dir).join("no-std.toml");
    println!("cargo:rerun-if-changed=no-std.toml");

    let text = fs::read_to_string(&toml_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
    let root: Value = text
        .parse()
        .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

    let slots = require_usize(
        "ring.slots",
        require_nonzero("ring.slots", get_int(&root, "ring", "slots")),
    );
    let slot_bytes = require_usize(
        "ring.slot_bytes",
        require_nonzero("ring.slot_bytes", get_int(&root, "ring", "slot_bytes")),
    );

    let generated = format!(
        "// AUTO-GENERATED by build.rs from no-std.toml. DO NOT EDIT.\n\
         pub const RING_SLOTS: usize = {slots};\n\
         pub const RING_SLOT_BYTES: usize = {slot_bytes};\n",
    );

    let out_path = out_dir.join("no_std_config.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}
