//! Build-time tier wiring for proxima-primitives.
//!
//! Union of the former proxima-pipe and proxima-sync build scripts (Wave D
//! Phase 3 primitives merge). Three responsibilities, mirroring the proxima
//! sizing+profile build pattern (proxima-quic-proto.toml for caps,
//! proxima-time/build.rs for the profile):
//!
//! 1. Bake the no-alloc heapless cap from `proxima-primitives.toml` into
//!    `OUT_DIR/proxima_primitives_pipe_sized.rs` — always, regardless of
//!    profile. (from proxima-pipe/build.rs)
//! 2. Emit the `proxima_alloc` cfg that selects the `RetryRules` backing store:
//!    set => `alloc::collections::BTreeSet`; unset => the heapless const-cap
//!    form. When `PROXIMA_PROFILE` is set the cfg follows the resolved Profile's
//!    `alloc` axis (proxima-build, P8); otherwise it follows the cargo `alloc`
//!    feature so a plain `cargo build` keeps the BTreeSet form ("std as
//!    today"). (from proxima-pipe/build.rs)
//! 3. Declare the `loom` cfg so `--cfg loom` builds stay clean under
//!    `unexpected_cfgs`. (from proxima-sync/build.rs)

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use toml::Value;

fn require_nonzero(name: &str, value: u64) -> u64 {
    assert!(value > 0, "{name} must be non-zero; got {value}");
    value
}

fn require_usize(name: &str, value: u64) -> usize {
    usize::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows usize"))
}

fn get_int(table: &Value, section: &str, key: &str) -> u64 {
    let raw = table
        .get(section)
        .and_then(|sec| sec.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| {
            panic!("proxima-primitives.toml: missing or non-integer [{section}].{key}")
        });
    u64::try_from(raw).unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
}

/// Read `(section, key)` from the TOML, then apply the optional
/// `PROXIMA_PIPE_<SECTION>_<KEY>` env-var override. The `PROXIMA_PIPE_`
/// prefix is kept verbatim (unchanged env-var contract) even though the
/// crate is now `proxima-primitives`.
fn resolve(table: &Value, section: &str, key: &str) -> u64 {
    let env_name = format!(
        "PROXIMA_PIPE_{}_{}",
        section.to_ascii_uppercase(),
        key.to_ascii_uppercase()
    );
    println!("cargo:rerun-if-env-changed={env_name}");
    if let Ok(raw) = env::var(&env_name) {
        return raw
            .parse()
            .unwrap_or_else(|err| panic!("{env_name} = {raw}: {err}"));
    }
    get_int(table, section, key)
}

#[allow(clippy::expect_used)]
fn emit_sizing_consts(out_dir: &Path) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let toml_path = PathBuf::from(&manifest_dir).join("proxima-primitives.toml");
    println!("cargo:rerun-if-changed=proxima-primitives.toml");

    let text = fs::read_to_string(&toml_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
    let root: Value = text
        .parse()
        .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

    let retry_status_cap = require_usize(
        "retry.status_cap",
        require_nonzero("retry.status_cap", resolve(&root, "retry", "status_cap")),
    );

    let out = format!(
        "// AUTO-GENERATED by build.rs from proxima-primitives.toml. DO NOT EDIT.\n\
         pub const RETRY_STATUS_CAP: usize = {retry_status_cap};\n",
    );

    let out_path = out_dir.join("proxima_primitives_pipe_sized.rs");
    fs::write(&out_path, out).unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}

#[allow(clippy::expect_used)]
fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    // heapless cap const — always emitted; the no-alloc RetryRules reads it.
    emit_sizing_consts(&out_dir);

    // declare every cfg name proxima-build's emit_cfg_directives can emit, so
    // the unexpected_cfgs lint stays quiet under deny-warnings. proxima_alloc is
    // the only one this crate reads; the rest are declared because the broad
    // emitter sets them whenever a profile is active.
    for name in ["proxima_alloc", "proxima_std", "proxima_quic_enabled"] {
        println!("cargo:rustc-check-cfg=cfg({name})");
    }
    for name in [
        "proxima_executor",
        "proxima_reactor",
        "proxima_tls",
        "proxima_timer",
        "proxima_quic_impl",
        "proxima_h3_impl",
        "proxima_profile_schema",
    ] {
        println!("cargo:rustc-check-cfg=cfg({name}, values(any()))");
    }

    // former proxima-sync/build.rs: declares `loom` so `--cfg loom` builds
    // (which never set this via a cargo feature) stay clean under
    // unexpected_cfgs.
    println!("cargo::rustc-check-cfg=cfg(loom)");

    // profile present => the Profile's alloc axis drives the cfg (proxima-build,
    // P8). absent => fall back to the cargo `alloc` feature so a plain build
    // keeps the BTreeSet form.
    if env::var("PROXIMA_PROFILE").is_ok() {
        let resolved = proxima_build::resolve_profile().expect("resolve proxima profile");
        proxima_build::emit_cfg_directives(&resolved);
        proxima_build::emit_generated_module(&resolved).expect("emit proxima_profile.rs");
        proxima_build::emit_rerun_directives(&resolved);
    } else if env::var("CARGO_FEATURE_ALLOC").is_ok() {
        println!("cargo:rustc-cfg=proxima_alloc");
    }
    println!("cargo:rerun-if-env-changed=PROXIMA_PROFILE");
}
