//! build.rs helper for proxima crates. Resolves a typed [`Profile`] via
//! conflaguration's standard layering (defaults → file → env → validate)
//! and emits a generated module + cfg directives for downstream
//! `build.rs` files to consume.
//!
//! Typical consumer (in a downstream crate's `build.rs`):
//!
//! ```ignore
//! fn main() {
//!     let profile = proxima_build::resolve_profile().expect("resolve profile");
//!     proxima_build::emit_generated_module(&profile);
//!     proxima_build::emit_cfg_directives(&profile);
//!     proxima_build::emit_rerun_directives(&profile);
//! }
//! ```
//!
//! The generated module ends up at `$OUT_DIR/proxima_profile.rs` and is
//! included by the consumer via:
//!
//! ```ignore
//! mod profile {
//!     include!(concat!(env!("OUT_DIR"), "/proxima_profile.rs"));
//! }
//! ```

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

pub mod profile;

pub use profile::{Executor, Profile, Reactor, Timer, TimerParseError, TlsBackend};

/// Errors that can occur during profile resolution or codegen.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("PROXIMA_PROFILE env var is not set; cannot resolve profile")]
    ProfileEnvUnset,
    #[error("profile file not found at {0}; check PROXIMA_PROFILE and workspace root")]
    ProfileFileMissing(PathBuf),
    #[error("could not determine workspace root from CARGO_MANIFEST_DIR")]
    WorkspaceRootUnknown,
    #[error("OUT_DIR env var not set; build.rs context required")]
    OutDirUnset,
    #[error("io error writing generated module: {0}")]
    Io(#[from] std::io::Error),
    #[error("conflaguration error: {0}")]
    Conflag(#[from] conflaguration::Error),
}

pub type Result<T> = core::result::Result<T, Error>;

/// Resolved profile + the source paths that were consulted (so
/// callers can wire them into `cargo:rerun-if-changed` directives).
#[derive(Debug)]
pub struct Resolved {
    pub profile: Profile,
    pub profile_file: PathBuf,
    pub env_vars: Vec<&'static str>,
}

/// Resolve the active profile from env + file + validation.
///
/// Reads `PROXIMA_PROFILE` from env; loads `<workspace>/profiles/<name>.toml`;
/// overlays `PROXIMA_*` env-var overrides; validates cross-axis rules.
///
/// Workspace root is inferred from `CARGO_MANIFEST_DIR` by walking up
/// until a `Cargo.toml` containing `[workspace]` is found.
#[allow(clippy::missing_errors_doc)]
pub fn resolve_profile() -> Result<Resolved> {
    let workspace_root = locate_workspace_root()?;
    let profile_name = env::var("PROXIMA_PROFILE").map_err(|_| Error::ProfileEnvUnset)?;
    let profile_file = workspace_root
        .join("profiles")
        .join(format!("{profile_name}.toml"));
    if !profile_file.exists() {
        return Err(Error::ProfileFileMissing(profile_file));
    }

    let profile: Profile = conflaguration::builder()
        .file(&profile_file)
        .env()
        .validate()
        .build()?;

    Ok(Resolved {
        profile,
        profile_file,
        env_vars: tracked_env_vars(),
    })
}

/// Resolve a profile from an explicit file path (skips env-var lookup
/// for `PROXIMA_PROFILE`; useful for tests).
#[allow(clippy::missing_errors_doc)]
pub fn resolve_profile_from(path: &Path) -> Result<Resolved> {
    if !path.exists() {
        return Err(Error::ProfileFileMissing(path.to_owned()));
    }
    let profile: Profile = conflaguration::builder()
        .file(path)
        .env()
        .validate()
        .build()?;
    Ok(Resolved {
        profile,
        profile_file: path.to_owned(),
        env_vars: tracked_env_vars(),
    })
}

/// Env vars that callers must declare in `cargo:rerun-if-env-changed`.
/// Listed centrally so consumers don't drift.
fn tracked_env_vars() -> Vec<&'static str> {
    vec![
        "PROXIMA_PROFILE",
        "PROXIMA_ALLOC",
        "PROXIMA_STD",
        "PROXIMA_EXECUTOR",
        "PROXIMA_REACTOR",
        "PROXIMA_TLS",
        "PROXIMA_QUIC_ENABLED",
        "PROXIMA_QUIC_IMPL",
        "PROXIMA_H3_IMPL",
        "PROXIMA_TIMER",
    ]
}

/// Emit `$OUT_DIR/proxima_profile.rs` with const + type alias derived
/// from the resolved profile. Consumer includes this module via
/// `include!(concat!(env!("OUT_DIR"), "/proxima_profile.rs"))`.
#[allow(clippy::missing_errors_doc)]
pub fn emit_generated_module(resolved: &Resolved) -> Result<()> {
    let out_dir = env::var("OUT_DIR").map_err(|_| Error::OutDirUnset)?;
    let out_path = Path::new(&out_dir).join("proxima_profile.rs");
    let mut file = fs::File::create(&out_path)?;

    let profile = &resolved.profile;

    writeln!(file, "// generated by proxima-build — do not edit by hand")?;
    writeln!(file, "// source: {}", resolved.profile_file.display())?;
    writeln!(file)?;
    writeln!(file, "pub const SCHEMA: u32 = {};", profile.schema)?;
    writeln!(file, "pub const ALLOC: bool = {};", profile.alloc)?;
    writeln!(file, "pub const STD: bool = {};", profile.std)?;
    writeln!(
        file,
        "pub const QUIC_ENABLED: bool = {};",
        profile.quic_enabled
    )?;
    writeln!(file)?;
    writeln!(file, "pub const EXECUTOR: &str = {:?};", profile.executor)?;
    writeln!(file, "pub const REACTOR: &str = {:?};", profile.reactor)?;
    writeln!(file, "pub const TLS: &str = {:?};", profile.tls)?;
    writeln!(file, "pub const TIMER: &str = {:?};", profile.timer)?;
    writeln!(file, "pub const QUIC_IMPL: &str = {:?};", profile.quic_impl)?;
    writeln!(file, "pub const H3_IMPL: &str = {:?};", profile.h3_impl)?;

    Ok(())
}

/// Emit `cargo:rustc-cfg=...` directives so consumers can `#[cfg(proxima_alloc)]`
/// and `#[cfg(proxima_executor = "tokio")]` against the active profile.
pub fn emit_cfg_directives(resolved: &Resolved) {
    let profile = &resolved.profile;
    if profile.alloc {
        println!("cargo:rustc-cfg=proxima_alloc");
    }
    if profile.std {
        println!("cargo:rustc-cfg=proxima_std");
    }
    if profile.quic_enabled {
        println!("cargo:rustc-cfg=proxima_quic_enabled");
    }
    println!("cargo:rustc-cfg=proxima_executor=\"{}\"", profile.executor);
    println!("cargo:rustc-cfg=proxima_reactor=\"{}\"", profile.reactor);
    println!("cargo:rustc-cfg=proxima_tls=\"{}\"", profile.tls);
    println!("cargo:rustc-cfg=proxima_timer=\"{}\"", profile.timer);
    println!(
        "cargo:rustc-cfg=proxima_quic_impl=\"{}\"",
        profile.quic_impl
    );
    println!("cargo:rustc-cfg=proxima_h3_impl=\"{}\"", profile.h3_impl);
    println!(
        "cargo:rustc-cfg=proxima_profile_schema=\"{}\"",
        profile.schema
    );
}

/// Emit `$OUT_DIR/proxima_time_bound_driver.rs` with the link-time-bound
/// `BOUND_DRIVER` static for `proxima_core::time`'s `Delay` future.
///
/// The generated file is one line:
///
/// ```ignore
/// pub static BOUND_DRIVER: &dyn crate::time::Driver = &<resolved-driver-path>;
/// ```
///
/// where `<resolved-driver-path>` comes from `Profile::timer_kind()?.driver_path()`.
/// `proxima-core`'s `time/mod.rs` includes this file with:
///
/// ```ignore
/// include!(concat!(env!("OUT_DIR"), "/proxima_time_bound_driver.rs"));
/// ```
///
/// Wrong path / missing symbol / wrong type / non-`'static` all surface as
/// compile errors in proxima-core, never at runtime.
#[allow(clippy::missing_errors_doc)]
pub fn emit_timer_binding(resolved: &Resolved) -> Result<()> {
    let out_dir = env::var("OUT_DIR").map_err(|_| Error::OutDirUnset)?;
    let out_path = Path::new(&out_dir).join("proxima_time_bound_driver.rs");
    let timer = resolved.profile.timer_kind().map_err(|err| {
        Error::Conflag(conflaguration::Error::Validation {
            errors: vec![conflaguration::ValidationMessage::new(
                "timer",
                err.to_string(),
            )],
        })
    })?;
    let mut file = fs::File::create(&out_path)?;
    writeln!(file, "// generated by proxima-build — do not edit by hand")?;
    writeln!(file, "// source: {}", resolved.profile_file.display())?;
    writeln!(file, "// timer = {:?}", resolved.profile.timer)?;
    writeln!(file)?;
    writeln!(
        file,
        "pub static BOUND_DRIVER: &dyn crate::time::Driver = &{};",
        timer.driver_path()
    )?;
    Ok(())
}

/// Emit `cargo:rerun-if-*` directives so cargo invalidates the build
/// when the profile file or any tracked env var changes.
pub fn emit_rerun_directives(resolved: &Resolved) {
    println!("cargo:rerun-if-changed={}", resolved.profile_file.display());
    for key in &resolved.env_vars {
        println!("cargo:rerun-if-env-changed={key}");
    }
}

fn locate_workspace_root() -> Result<PathBuf> {
    let start = env::var("CARGO_MANIFEST_DIR").map_err(|_| Error::WorkspaceRootUnknown)?;
    let mut path = PathBuf::from(start);
    loop {
        let candidate = path.join("Cargo.toml");
        if candidate.exists() {
            let contents = fs::read_to_string(&candidate)?;
            if contents.contains("[workspace]") {
                return Ok(path);
            }
        }
        if !path.pop() {
            return Err(Error::WorkspaceRootUnknown);
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn write_temp_profile(dir: &Path, contents: &str) -> PathBuf {
        let path = dir.join("profile.toml");
        fs::write(&path, contents).unwrap();
        path
    }

    #[test]
    fn resolve_from_file_loads_linux_daemon_shape() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_temp_profile(
            tmp.path(),
            r#"
schema = 1
alloc = true
std = true
executor = "tokio"
reactor = "tokio-epoll"
tls = "rustls"
quic_enabled = false
timer = "std-thread"
"#,
        );
        let resolved = resolve_profile_from(&path).expect("resolve");
        assert!(resolved.profile.alloc);
        assert!(resolved.profile.std);
        assert_eq!(resolved.profile.executor_kind().unwrap(), Executor::Tokio);
        assert_eq!(resolved.profile.tls_backend().unwrap(), TlsBackend::Rustls);
    }

    #[test]
    fn resolve_from_file_loads_embedded_mqtt_gateway_shape() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_temp_profile(
            tmp.path(),
            r#"
schema = 1
alloc = true
std = false
executor = "embassy"
reactor = "embassy-net"
tls = "embedded-tls"
quic_enabled = false
timer = "embassy-time"
"#,
        );
        let resolved = resolve_profile_from(&path).expect("resolve");
        assert!(!resolved.profile.std);
        assert!(resolved.profile.alloc);
        assert_eq!(resolved.profile.executor_kind().unwrap(), Executor::Embassy);
        assert_eq!(
            resolved.profile.tls_backend().unwrap(),
            TlsBackend::EmbeddedTls
        );
    }

    #[test]
    fn resolve_missing_file_returns_typed_error() {
        let missing = PathBuf::from("/nonexistent/profile.toml");
        let err = resolve_profile_from(&missing).expect_err("should error on missing");
        match err {
            Error::ProfileFileMissing(p) => assert_eq!(p, missing),
            other => panic!("expected ProfileFileMissing, got {other:?}"),
        }
    }

    #[test]
    fn resolve_validation_rule_rejects_rustls_without_std() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_temp_profile(
            tmp.path(),
            r#"
schema = 1
alloc = true
std = false
executor = "embassy"
reactor = "embassy-net"
tls = "rustls"
quic_enabled = false
timer = "embassy-time"
"#,
        );
        let err = resolve_profile_from(&path).expect_err("should reject");
        match err {
            Error::Conflag(_) => {} // validation surfaced
            other => panic!("expected validation error, got {other:?}"),
        }
    }

    #[test]
    fn emit_generated_module_writes_consts() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_temp_profile(
            tmp.path(),
            r#"
schema = 1
alloc = true
std = true
executor = "prime"
reactor = "tokio-epoll"
tls = "rustls"
quic_enabled = false
timer = "prime-wheel"
"#,
        );
        let resolved = resolve_profile_from(&path).unwrap();

        // simulate OUT_DIR
        let out_dir = tempfile::tempdir().unwrap();
        // SAFETY: test-only env mutation; tests run serially in this module.
        unsafe { env::set_var("OUT_DIR", out_dir.path()) };
        emit_generated_module(&resolved).unwrap();

        let generated = fs::read_to_string(out_dir.path().join("proxima_profile.rs")).unwrap();
        assert!(generated.contains("pub const ALLOC: bool = true;"));
        assert!(generated.contains("pub const STD: bool = true;"));
        assert!(
            generated.contains("pub const EXECUTOR: &str = \"prime\";"),
            "want EXECUTOR const, got: {generated}"
        );
        assert!(generated.contains("pub const TLS: &str = \"rustls\";"));

        unsafe { env::remove_var("OUT_DIR") };
    }

    #[test]
    fn schema_unsupported_rejected() {
        let tmp = tempfile::tempdir().unwrap();
        let path = write_temp_profile(
            tmp.path(),
            r#"
schema = 99
alloc = true
std = true
executor = "tokio"
reactor = "tokio-epoll"
tls = "rustls"
quic_enabled = false
timer = "std-thread"
"#,
        );
        let err = resolve_profile_from(&path).expect_err("schema 99 should reject");
        match err {
            Error::Conflag(_) => {}
            other => panic!("expected validation error, got {other:?}"),
        }
    }

    #[test]
    fn tracked_env_vars_includes_proxima_profile() {
        let vars = tracked_env_vars();
        assert!(vars.contains(&"PROXIMA_PROFILE"));
        assert!(vars.contains(&"PROXIMA_ALLOC"));
        assert!(vars.contains(&"PROXIMA_STD"));
    }
}
