//! Pure-Rust dpdk FFI — no C linked into the crate.
//!
//! dpdk's control plane (EAL init, pool create, device configure/start) is real
//! exported symbols, bound directly. Its hot path (`rte_eth_rx_burst`/`tx_burst`,
//! `rte_pktmbuf_alloc`/`_free`, mbuf field access) is `static inline` in the
//! headers — no linkable symbol — so it is reimplemented here over dpdk's real
//! exported globals (`rte_eth_fp_ops`, `rte_mempool_ops_table`) and the mbuf
//! struct fields. Struct offsets/sizes come from [`abi`], generated by build.rs
//! from the INSTALLED dpdk headers, so the binding tracks whatever dpdk is
//! present and cannot silently go stale. See `docs/net-dpdk/discipline.md`.
//!
//! Pools are created with cache_size = 0 so every object lives in the ring and
//! alloc/free go straight through the mempool ops — no per-lcore cache to mirror
//! (the cache is the version-fragile part; we sidestep it). Fine for a per-core
//! PMD; a cache is a later perf row.

#![allow(non_upper_case_globals)]

use core::ffi::{c_char, c_int, c_uint, c_void};
use core::ptr;

/// Struct offsets/sizes derived from the installed dpdk headers at build time.
pub mod abi {
    include!(concat!(env!("OUT_DIR"), "/dpdk_abi.rs"));
}

const DATA_ROOM: u16 = 2176; // RTE_MBUF_DEFAULT_BUF_SIZE (2048 data + 128 headroom)
const RX_DESC: u16 = 1024;
const TX_DESC: u16 = 1024;

/// Opaque dpdk mempool; only ever held behind a pointer.
#[repr(C)]
pub struct RteMempool {
    _opaque: [u8; 0],
}

/// Opaque dpdk packet buffer; only ever held behind a pointer.
#[repr(C)]
pub struct RteMbuf {
    _opaque: [u8; 0],
}

type RxBurstFn = unsafe extern "C" fn(*mut c_void, *mut *mut RteMbuf, u16) -> u16;
type TxBurstFn = unsafe extern "C" fn(*mut c_void, *mut *mut RteMbuf, u16) -> u16;
type EnqueueFn = unsafe extern "C" fn(*mut RteMempool, *const *mut c_void, c_uint) -> c_int;
type DequeueFn = unsafe extern "C" fn(*mut RteMempool, *mut *mut c_void, c_uint) -> c_int;

unsafe extern "C" {
    fn rte_eal_init(argc: c_int, argv: *mut *mut c_char) -> c_int;
    fn rte_eal_cleanup() -> c_int;
    fn rte_pktmbuf_pool_create(
        name: *const c_char,
        n: c_uint,
        cache_size: c_uint,
        priv_size: u16,
        data_room_size: u16,
        socket_id: c_int,
    ) -> *mut RteMempool;
    fn rte_eth_dev_count_avail() -> u16;
    fn rte_eth_dev_configure(port: u16, nb_rx: u16, nb_tx: u16, conf: *const c_void) -> c_int;
    fn rte_eth_rx_queue_setup(
        port: u16,
        q: u16,
        n: u16,
        socket: c_uint,
        conf: *const c_void,
        pool: *mut RteMempool,
    ) -> c_int;
    fn rte_eth_tx_queue_setup(
        port: u16,
        q: u16,
        n: u16,
        socket: c_uint,
        conf: *const c_void,
    ) -> c_int;
    fn rte_eth_dev_start(port: u16) -> c_int;
    fn rte_eth_promiscuous_enable(port: u16) -> c_int;
    fn rte_eth_macaddr_get(port: u16, mac: *mut u8) -> c_int;
    fn rte_eth_dev_socket_id(port: u16) -> c_int;
    fn rte_version() -> *const c_char;

    // exported globals (arrays); their symbol address is the array base.
    static rte_eth_fp_ops: u8;
    static rte_mempool_ops_table: u8;
}

#[inline]
unsafe fn field<T: Copy>(base: *const u8, offset: usize) -> T {
    unsafe { base.add(offset).cast::<T>().read_unaligned() }
}

#[inline]
unsafe fn set_field<T>(base: *mut u8, offset: usize, value: T) {
    unsafe { base.add(offset).cast::<T>().write_unaligned(value) }
}

// ---- control plane (real symbols) ----

pub unsafe fn eal_init(argc: c_int, argv: *mut *mut c_char) -> c_int {
    unsafe { rte_eal_init(argc, argv) }
}

pub unsafe fn eal_cleanup() {
    unsafe {
        rte_eal_cleanup();
    }
}

#[must_use]
pub fn version() -> String {
    let ptr = unsafe { rte_version() };
    if ptr.is_null() {
        return String::new();
    }
    unsafe { core::ffi::CStr::from_ptr(ptr) }
        .to_string_lossy()
        .into_owned()
}

pub unsafe fn pool_create(name: *const c_char, n: c_uint, socket_id: c_int) -> *mut RteMempool {
    // cache_size = 0: all objects in the ring, alloc/free via ops only.
    unsafe { rte_pktmbuf_pool_create(name, n, 0, 0, DATA_ROOM, socket_id) }
}

#[must_use]
pub fn port_count() -> u16 {
    unsafe { rte_eth_dev_count_avail() }
}

/// Configure 1 rx + 1 tx queue, start the port, enable promiscuous. Returns 0 or
/// dpdk's negative code.
pub unsafe fn port_init(port: u16, pool: *mut RteMempool) -> c_int {
    let conf = vec![0u8; abi::SIZEOF_rte_eth_conf];
    let code = unsafe { rte_eth_dev_configure(port, 1, 1, conf.as_ptr().cast::<c_void>()) };
    if code < 0 {
        return code;
    }
    let socket = unsafe { rte_eth_dev_socket_id(port) };
    let socket = socket as c_uint;
    let code = unsafe { rte_eth_rx_queue_setup(port, 0, RX_DESC, socket, ptr::null(), pool) };
    if code < 0 {
        return code;
    }
    let code = unsafe { rte_eth_tx_queue_setup(port, 0, TX_DESC, socket, ptr::null()) };
    if code < 0 {
        return code;
    }
    let code = unsafe { rte_eth_dev_start(port) };
    if code < 0 {
        return code;
    }
    unsafe { rte_eth_promiscuous_enable(port) };
    0
}

pub unsafe fn macaddr(port: u16, out: *mut u8) -> c_int {
    unsafe { rte_eth_macaddr_get(port, out) }
}

// ---- hot path (reimplemented over dpdk globals + mbuf fields) ----

#[inline]
unsafe fn fp_ops_entry(port: u16) -> *const u8 {
    let base = ptr::addr_of!(rte_eth_fp_ops);
    unsafe { base.add(usize::from(port) * abi::SIZEOF_rte_eth_fp_ops) }
}

pub unsafe fn rx_burst(port: u16, bufs: *mut *mut RteMbuf, max: u16) -> u16 {
    let entry = unsafe { fp_ops_entry(port) };
    let data: *mut *mut c_void = unsafe { field(entry, abi::FPOPS_RXQ_DATA) };
    let queue = unsafe { *data }; // queue 0
    let burst: RxBurstFn = unsafe { field(entry, abi::FPOPS_RX_BURST) };
    unsafe { burst(queue, bufs, max) }
}

pub unsafe fn tx_burst(port: u16, bufs: *mut *mut RteMbuf, nb: u16) -> u16 {
    let entry = unsafe { fp_ops_entry(port) };
    let data: *mut *mut c_void = unsafe { field(entry, abi::FPOPS_TXQ_DATA) };
    let queue = unsafe { *data }; // queue 0
    let burst: TxBurstFn = unsafe { field(entry, abi::FPOPS_TX_BURST) };
    unsafe { burst(queue, bufs, nb) }
}

#[inline]
unsafe fn pool_ops(pool: *const u8) -> *const u8 {
    let ops_index: i32 = unsafe { field(pool, abi::MEMPOOL_OPS_INDEX) };
    let table = ptr::addr_of!(rte_mempool_ops_table);
    let offset = abi::MEMPOOL_OPS_TABLE_OPS + (ops_index as usize) * abi::SIZEOF_rte_mempool_ops;
    unsafe { table.add(offset) }
}

pub unsafe fn mbuf_alloc(pool: *mut RteMempool) -> *mut RteMbuf {
    let ops = unsafe { pool_ops(pool.cast()) };
    let dequeue: DequeueFn = unsafe { field(ops, abi::OPS_DEQUEUE) };
    let mut obj: *mut c_void = ptr::null_mut();
    if unsafe { dequeue(pool, &mut obj, 1) } != 0 {
        return ptr::null_mut(); // pool empty
    }
    let mbuf = obj.cast::<RteMbuf>();
    unsafe { mbuf_reset(mbuf) };
    mbuf
}

// rte_pktmbuf_reset + refcnt = 1, for a fresh single-segment direct mbuf.
unsafe fn mbuf_reset(mbuf: *mut RteMbuf) {
    let base = mbuf.cast::<u8>();
    unsafe {
        set_field::<u16>(base, abi::MBUF_REFCNT, 1);
        set_field::<*mut c_void>(base, abi::MBUF_NEXT, ptr::null_mut());
        set_field::<u32>(base, abi::MBUF_PKT_LEN, 0);
        set_field::<u64>(base, abi::MBUF_TX_OFFLOAD, 0);
        set_field::<u16>(base, abi::MBUF_VLAN_TCI, 0);
        set_field::<u16>(base, abi::MBUF_VLAN_TCI_OUTER, 0);
        set_field::<u16>(base, abi::MBUF_NB_SEGS, 1);
        set_field::<u16>(base, abi::MBUF_PORT, abi::PORT_INVALID);
        let ol: u64 = field(base, abi::MBUF_OL_FLAGS);
        set_field::<u64>(base, abi::MBUF_OL_FLAGS, ol & abi::F_EXTERNAL);
        set_field::<u32>(base, abi::MBUF_PACKET_TYPE, 0);
        let buf_len: u16 = field(base, abi::MBUF_BUF_LEN);
        let headroom = (abi::HEADROOM as u16).min(buf_len);
        set_field::<u16>(base, abi::MBUF_DATA_OFF, headroom);
        set_field::<u16>(base, abi::MBUF_DATA_LEN, 0);
    }
}

pub unsafe fn mbuf_free(mbuf: *mut RteMbuf) {
    let base = mbuf.cast::<u8>();
    let refcnt: u16 = unsafe { field(base, abi::MBUF_REFCNT) };
    if refcnt != 1 {
        // shared segment: drop a reference, free only when it hits zero.
        let next = refcnt - 1;
        unsafe { set_field::<u16>(base, abi::MBUF_REFCNT, next) };
        if next != 0 {
            return;
        }
        unsafe { set_field::<u16>(base, abi::MBUF_REFCNT, 1) };
    }
    let pool: *mut RteMempool = unsafe { field(base, abi::MBUF_POOL) };
    let ops = unsafe { pool_ops(pool.cast()) };
    let enqueue: EnqueueFn = unsafe { field(ops, abi::OPS_ENQUEUE) };
    let obj = mbuf.cast::<c_void>();
    unsafe { enqueue(pool, &obj, 1) };
}

pub unsafe fn mbuf_append(mbuf: *mut RteMbuf, len: u16) -> *mut u8 {
    let base = mbuf.cast::<u8>();
    let buf_addr: *mut u8 = unsafe { field(base, abi::MBUF_BUF_ADDR) };
    let data_off: u16 = unsafe { field(base, abi::MBUF_DATA_OFF) };
    let data_len: u16 = unsafe { field(base, abi::MBUF_DATA_LEN) };
    let buf_len: u16 = unsafe { field(base, abi::MBUF_BUF_LEN) };
    if len > buf_len - (data_off + data_len) {
        return ptr::null_mut();
    }
    let tail = unsafe { buf_addr.add(usize::from(data_off + data_len)) };
    unsafe { set_field::<u16>(base, abi::MBUF_DATA_LEN, data_len + len) };
    let pkt_len: u32 = unsafe { field(base, abi::MBUF_PKT_LEN) };
    unsafe { set_field::<u32>(base, abi::MBUF_PKT_LEN, pkt_len + u32::from(len)) };
    tail
}

#[must_use]
pub unsafe fn mbuf_data(mbuf: *mut RteMbuf) -> *mut u8 {
    let base = mbuf.cast::<u8>();
    let buf_addr: *mut u8 = unsafe { field(base, abi::MBUF_BUF_ADDR) };
    let data_off: u16 = unsafe { field(base, abi::MBUF_DATA_OFF) };
    unsafe { buf_addr.add(usize::from(data_off)) }
}

#[must_use]
pub unsafe fn mbuf_len(mbuf: *mut RteMbuf) -> u16 {
    unsafe { field(mbuf.cast::<u8>(), abi::MBUF_DATA_LEN) }
}

// ---- boot guards (turn silent ABI drift into a loud failure at startup) ----

/// The dpdk YY.MM the build-time probe read offsets from.
#[must_use]
pub fn version_built() -> String {
    format!("{}.{:02}", abi::BUILT_VER_YEAR, abi::BUILT_VER_MONTH)
}

/// Whether the runtime dpdk `.so` matches the YY.MM we generated offsets against.
#[must_use]
pub fn version_matches_build() -> bool {
    version().contains(&version_built())
}

/// Exercise alloc → append → read-back → free → realloc against a real pool, so a
/// wrong struct offset or mempool-ops mistake fails loudly here (boot) rather
/// than as silent corruption under load.
///
/// # Errors
/// [`super::DpdkError::AbiSelfCheck`] with the failing step.
///
/// # Safety
/// `pool` must be a live dpdk mempool.
pub unsafe fn abi_self_check(pool: *mut RteMempool) -> Result<(), super::DpdkError> {
    use super::DpdkError::AbiSelfCheck;
    const SENTINEL: [u8; 4] = [0xde, 0xad, 0xbe, 0xef];

    let probe = unsafe { mbuf_alloc(pool) };
    if probe.is_null() {
        return Err(AbiSelfCheck("mbuf_alloc returned null"));
    }
    let outcome = (|| {
        if unsafe { mbuf_len(probe) } != 0 {
            return Err(AbiSelfCheck("fresh mbuf data_len != 0"));
        }
        let tail = unsafe { mbuf_append(probe, 4) };
        if tail.is_null() {
            return Err(AbiSelfCheck("mbuf_append failed"));
        }
        unsafe { ptr::copy_nonoverlapping(SENTINEL.as_ptr(), tail, 4) };
        if unsafe { mbuf_data(probe) } != tail {
            return Err(AbiSelfCheck("mbuf_data != appended tail"));
        }
        if unsafe { core::slice::from_raw_parts(tail, 4) } != SENTINEL {
            return Err(AbiSelfCheck("sentinel read-back mismatch"));
        }
        if unsafe { mbuf_len(probe) } != 4 {
            return Err(AbiSelfCheck("data_len != 4 after append"));
        }
        Ok(())
    })();
    unsafe { mbuf_free(probe) };
    outcome?;

    // free must have returned the buffer to the ring — a realloc proves enqueue.
    let again = unsafe { mbuf_alloc(pool) };
    if again.is_null() {
        return Err(AbiSelfCheck("free did not return the mbuf to the pool"));
    }
    unsafe { mbuf_free(again) };
    Ok(())
}
