//! Sans-IO protocol parser primitives for proxima, one feature-gated
//! module per protocol.
//!
//! Folded from eleven single-purpose parser crates (`proxima-dns`,
//! `proxima-mqtt`, `proxima-amqp`, `proxima-kafka`,
//! `proxima-memcached`, `proxima-grpc-framing`,
//! `proxima-protobuf-wire`, `proxima-jsonrpc`,
//! `proxima-websocket-frame`, `proxima-websocket-handshake`,
//! `proxima-proxy-protocol`) plus the four HTTP wire codecs
//! (`proxima-h1-codec`, `proxima-h2-codec`, `proxima-hpack`,
//! `proxima-h3-proto`), then a second wave of eight more (`proxima-tcp`,
//! `proxima-inet-codec`, `proxima-nvme-codec`, `proxima-pgwire-codec`,
//! `proxima-process-protocol`, `proxima-framing-json` whole,
//! `proxima-redis`'s codec half, and `proxima-quic-proto`) into one
//! crate with a module per protocol, matching the workspace's internal
//! tier-gating convention (cf. `proxima-pipe`, `prime`) — each module
//! is independently enabled by its own feature and compiles under
//! `no_std` + `alloc` unless its feature pulls in a std-only adapter
//! (see `proxy_protocol`, `json_framing-std`). `pgwire_codec` and
//! `redis` mirror each other's split shape: the sans-IO codec lives
//! here, the std client stays in `proxima-pgwire` / `proxima-redis`.
//!
//! Every module is sans-IO: pure buffer-in / buffer-out parsing and
//! encoding. The caller owns the transport (`AsyncRead` / socket /
//! DPDK ring — all the codec's problem).

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

#[cfg(feature = "amqp")]
pub mod amqp;
/// Generic [`FrameCodec`](proxima_codec::FrameCodec) -> `Pipe` adapter, shared
/// by every codec's own `-frame-pipe` feature (`http1_codec`, `grpc_framing`,
/// `websocket_frame`, ...). See the module doc for why the adapter is generic
/// while `OwnFrame`/`Incomplete` stay per-codec.
#[cfg(feature = "codec-pipe")]
pub mod codec_pipe;
#[cfg(feature = "dns")]
pub mod dns;
#[cfg(feature = "grpc_framing")]
pub mod grpc_framing;
#[cfg(feature = "hpack")]
pub mod hpack;
#[cfg(feature = "http1_codec")]
pub mod http1_codec;
#[cfg(feature = "http2_codec")]
pub mod http2_codec;
#[cfg(feature = "http3_codec")]
pub mod http3_codec;
#[cfg(feature = "inet")]
pub mod inet;
#[cfg(feature = "json_framing")]
pub mod json_framing;
#[cfg(feature = "jsonrpc")]
pub mod jsonrpc;
#[cfg(feature = "kafka")]
pub mod kafka;
#[cfg(feature = "memcached")]
pub mod memcached;
#[cfg(feature = "mqtt")]
pub mod mqtt;
#[cfg(feature = "nvme")]
pub mod nvme;
#[cfg(feature = "pgwire_codec")]
pub mod pgwire_codec;
#[cfg(feature = "process")]
pub mod process;
#[cfg(feature = "protobuf_wire")]
pub mod protobuf_wire;
#[cfg(feature = "proxy_protocol")]
pub mod proxy_protocol;
// shared by the independently-gated quic + tcp data paths
#[cfg(any(feature = "quic", feature = "tcp"))]
pub mod time;

#[cfg(feature = "quic")]
pub mod quic;
#[cfg(feature = "redis")]
pub mod redis;
#[cfg(feature = "tcp")]
pub mod tcp;
#[cfg(feature = "websocket_frame")]
pub mod websocket_frame;
#[cfg(feature = "websocket_handshake")]
pub mod websocket_handshake;

/// Build-time sizing constants for [`http3_codec`], generated by
/// `build.rs` from `http3_codec.toml` + optional
/// `PROXIMA_PROTOCOLS_HTTP3_CODEC_*` env overrides. Every const-generic
/// cap in `http3_codec` threads through these values so downstream
/// consumers can re-tune via the TOML or env at build time without
/// forking the source.
#[cfg(feature = "http3_codec")]
pub mod sized {
    include!(concat!(env!("OUT_DIR"), "/proxima_h3_proto_sized.rs"));
}

/// A counting global allocator, wired in ONLY for this crate's own
/// `#[cfg(test)]` unit-test binary (never for normal builds, benches,
/// or downstream consumers). [`hpack::decoder`] and
/// [`http3_codec::qpack::decoder`] tests snapshot
/// [`stats_alloc::Region`] around a call to assert their respective
/// allocation-count claims mechanically, instead of by memory. Shared
/// across both modules (rather than one static per module) because a
/// binary may only declare one `#[global_allocator]` — `http3_codec`
/// depends on the `hpack` feature, so both modules' tests can compile
/// into the same test binary.
#[cfg(all(test, feature = "std"))]
pub(crate) mod alloc_test {
    use std::alloc::System;
    use std::sync::Mutex;

    use stats_alloc::{Region, Stats};
    use stats_alloc::StatsAlloc;

    #[global_allocator]
    pub(crate) static PROTOCOLS_TEST_ALLOC: StatsAlloc<System> = StatsAlloc::system();

    // the allocator above is one process-global static shared by every
    // alloc_count_* test in this binary; the default `cargo test` harness
    // runs tests concurrently on multiple threads, so an unguarded
    // before/after snapshot here counts whatever ELSE is allocating on
    // other threads at the same moment (measured: 100% failure rate
    // across 6 tests under `cargo test`, 0/30 failures once every
    // measurement window serializes through this lock).
    static ALLOC_TEST_LOCK: Mutex<()> = Mutex::new(());

    /// exclusive measurement window: holds `ALLOC_TEST_LOCK` for as long as
    /// the returned value lives, so two `alloc_count_*` tests can never
    /// observe each other's allocations regardless of which thread the test
    /// harness schedules them on.
    pub(crate) struct ExclusiveRegion {
        _guard: std::sync::MutexGuard<'static, ()>,
        region: Region<'static, System>,
    }

    impl ExclusiveRegion {
        pub(crate) fn change(&self) -> Stats {
            self.region.change()
        }
    }

    pub(crate) fn exclusive_region() -> ExclusiveRegion {
        let guard = ALLOC_TEST_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        ExclusiveRegion {
            _guard: guard,
            region: Region::new(&PROTOCOLS_TEST_ALLOC),
        }
    }
}
