use std::env;
use std::fs;
use std::path::PathBuf;

use toml::Value;

fn main() {
    emit_kv_sizing_consts();
}

/// Emits `sized.rs`'s `generated` module from
/// `proxima-model-interop-runtime.toml`'s `[kv]` section -- mirrors
/// `proxima-tensor/build.rs`'s `emit_sizing_consts` (guiding-principle 12).
/// `kv-capacity-bucket`-only: this crate's own `src/sized.rs` compiles the
/// `generated` module (and this file's own `include!`) out entirely when the
/// feature is off, so the file is only written when Cargo reports the
/// feature active for THIS build, exactly as that crate's own aarch64 and
/// `cohort-staged-graph` branches skip emission on a build that never
/// references the constant.
#[allow(clippy::expect_used)]
fn emit_kv_sizing_consts() {
    if env::var_os("CARGO_FEATURE_KV_CAPACITY_BUCKET").is_none() {
        return;
    }

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let toml_path = PathBuf::from(&manifest_dir).join("proxima-model-interop-runtime.toml");
    println!("cargo:rerun-if-changed=proxima-model-interop-runtime.toml");

    let text = fs::read_to_string(&toml_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
    let root: Value = text
        .parse()
        .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

    // the 34 GB trap's build-time close: this constant sizes a plan-cache
    // KEY bucket, never a device allocation, so a value large enough to
    // suggest it was conflated with `ServingConfig::context_length` (whose
    // own default is 131_072) is a build failure, not a runtime one.
    let bucket_tokens = require_nonzero("kv.bucket_tokens", resolve_int(&root, "kv", "bucket_tokens"));
    assert!(
        bucket_tokens <= 65_536,
        "kv.bucket_tokens={bucket_tokens} exceeds the 65,536-token sanity ceiling -- \
         this constant sizes a plan-cache KEY bucket, never a device allocation; a \
         value this large suggests it was conflated with ServingConfig::context_length"
    );

    let out = format!(
        "// AUTO-GENERATED by build.rs from proxima-model-interop-runtime.toml. DO NOT EDIT.\n\
         pub const KV_BUCKET_TOKENS: usize = {bucket_tokens};\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("proxima_model_interop_sized.rs");
    fs::write(&out_path, out).unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}

fn require_nonzero(name: &str, value: i64) -> usize {
    let value = usize::try_from(value)
        .unwrap_or_else(|_| panic!("{name} must be a non-negative integer; got {value}"));
    assert!(value > 0, "{name} must be non-zero");
    value
}

fn get_int(table: &Value, section: &str, key: &str) -> i64 {
    table
        .get(section)
        .and_then(|section_value| section_value.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| {
            panic!("proxima-model-interop-runtime.toml: missing or non-integer [{section}].{key}")
        })
}

/// like `get_int`, but a `PROXIMA_MODEL_INTEROP_<SECTION>_<KEY>` env var
/// overrides the TOML value when present -- mirrors
/// `proxima-tensor/build.rs`'s `resolve_int` (guiding-principle 12: every
/// override consulted emits its own `cargo:rerun-if-env-changed` line, so a
/// cached build never ignores it).
fn resolve_int(table: &Value, section: &str, key: &str) -> i64 {
    let env_name = format!(
        "PROXIMA_MODEL_INTEROP_{section}_{key}",
        section = section.to_uppercase(),
        key = key.to_uppercase()
    );
    println!("cargo:rerun-if-env-changed={env_name}");
    match env::var(&env_name) {
        Ok(raw) => raw
            .parse::<i64>()
            .unwrap_or_else(|err| panic!("{env_name}={raw} must parse as i64: {err}")),
        Err(_) => get_int(table, section, key),
    }
}
