//! AF_XDP zero-copy datapath for the proxima userspace network stack — the
//! kernel-bypass peer of `proxima-net-dpdk`.
//!
//! Like the dpdk crate, this splits into two halves. The sans-IO half
//! ([`ring`], [`uapi`]) is pure — the AF_XDP producer/consumer index arithmetic
//! and the kernel UAPI layout — so it builds everywhere and is unit-tested in
//! mac CI. The socket/UMEM/BPF datapath is behind the default-off `xdp` feature
//! and links nothing C: it drives the four AF_XDP rings over raw `libc`
//! syscalls, so it builds only on a linux host.
//!
//! An AF_XDP socket (XSK) owns four single-producer/single-consumer rings over a
//! shared UMEM region: FILL (we hand the kernel empty frames), RX (the kernel
//! hands us received frames), TX (we hand the kernel frames to send), and
//! COMPLETION (the kernel hands back transmitted frames). [`ProducerIndex`] and
//! [`ConsumerIndex`] are the ring bookkeeping those four share.

pub mod error;
pub mod ring;
pub mod uapi;

/// Build-time sizing (principle 12): ring depths, UMEM geometry, and the RX
/// drain batch, generated by `build.rs` from `proxima-net-xdp.toml`. Pure
/// consts, so this compiles on every target regardless of the `xdp` feature.
pub mod sized {
    include!(concat!(env!("OUT_DIR"), "/proxima_net_xdp_sized.rs"));
}

#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod bpf;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod packet_listener;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod readiness;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod stream_listener;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod sys;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod umem;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub mod xsk;

pub use error::XdpError;
pub use ring::{ConsumerIndex, ProducerIndex};

#[cfg(all(feature = "xdp", target_os = "linux"))]
pub use bpf::XdpProgram;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub use packet_listener::XdpPacketListener;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub use stream_listener::{XdpStreamConnection, XdpStreamListener, XdpStreamUpstream};
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub use umem::Umem;
#[cfg(all(feature = "xdp", target_os = "linux"))]
pub use xsk::{CompletionRing, FillRing, RingSizes, RxRing, TxRing, UmemConfig, XskSocket};
