//! Real-traffic shape sweep for BGE-small-en-v1.5, answering the gap named
//! against `docs/discipline.md`'s sealed `bge_eval` number (6.061 ms/sentence
//! Accelerate / 7.521 NEON at S=7-9, batch=1): that number is three
//! sentences of 7/8/9 tokens, and real embedding traffic is document chunks
//! of 128-512 tokens at varied lengths and batch sizes -- none of which the
//! sealed harness exercises. This file measures three things directly
//! rather than assuming any of them:
//!
//! (A) sequence-length sweep -- S in {8,32,64,128,256,512} (512 = BGE's own
//!     `max_position_embeddings`, `config.json`), NEON and Accelerate, plus
//!     `width_tile_plan` gate engagement (N of the 96 gemm-shaped `MatMul`
//!     folds `bge_route_census.rs`'s own doc names) and the decline-reason
//!     census at each S.
//! (B) cache behaviour -- 200-call stream of varied pinned lengths through
//!     `cpu::evaluate_named`'s own process-global `ARENA_CACHE` (capacity
//!     8, FIFO, `cpu.rs::ARENA_CACHE_CAPACITY`), measuring hit vs miss wall
//!     time directly from per-call timing classified by
//!     `cpu::arena_cache_totals()` deltas.
//! (C) batch sweep -- batch in {1,8,32} at S=128, pinning `batch_size` in
//!     `lower_graph_pinned` the same way `sequence_length` is already
//!     pinned.
//!
//! Token content is synthetic (this crate has no BGE-compatible tokenizer,
//! see `bge_eval.rs`'s own doc), generated by one deterministic formula
//! (`synthetic_tokens`) so every id stays a valid BGE-small vocab index
//! (`vocab_size` 30522) without claiming to be real English -- real-word
//! semantics are irrelevant to a shape/cache/batch measurement. Embeddings
//! are dumped to `BGE_TRAFFIC_OUT_DIR` (plain text, one file per S) for the
//! companion onnxruntime harness to diff against out-of-process.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write as _;
use std::path::Path;
use std::time::{Duration, Instant};

use proxima_tensor::NodeId;
#[cfg(any(target_arch = "aarch64", feature = "bge-eval-diag"))]
use proxima_tensor::cpu;
use proxima_tensor::cpu::{
    StaticArena, build_static_arena_with_constants, evaluate_named, evaluate_named_with_arena,
};

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
fn set_accelerate_gemm_enabled(enabled: bool) {
    cpu::set_accelerate_gemm_enabled(enabled);
}
#[cfg(not(all(target_os = "macos", target_arch = "aarch64")))]
fn set_accelerate_gemm_enabled(_enabled: bool) {}

const MODEL_PATH_ENV: &str = "BGE_MODEL_PATH";
const OUT_DIR_ENV: &str = "BGE_TRAFFIC_OUT_DIR";
/// BGE-small-en-v1.5's own `max_position_embeddings`, read from the real HF
/// `config.json` (`~/.cache/huggingface/hub/models--BAAI--bge-small-en-v1.5/
/// snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json`):
/// `"max_position_embeddings": 512`. Matches the task's own guess, verified
/// rather than assumed.
const MAX_POSITION_EMBEDDINGS: usize = 512;
/// BGE-small's own vocab size (`tokenizer.json`'s `model.vocab` length,
/// read directly: 30522). `synthetic_tokens` stays well inside this.
const VOCAB_SIZE: i64 = 30522;

/// Deterministic, valid-vocab synthetic token stream: `[CLS]` + `length - 2`
/// interior ids + `[SEP]`, each interior id `2000 + ((i * 9301 + seed *
/// 49297) % 26000)` -- comfortably inside `[2000, 28000)` (below
/// `VOCAB_SIZE`), well past BERT's reserved/unused/punctuation range
/// (`[unused0..993]`, special tokens, ids 0-1999), so every id resolves to
/// a genuine wordpiece embedding row. Implemented identically (same
/// integer arithmetic, no floats) in the Python onnxruntime harness
/// (`scripts/onnx_reference/traffic_bench.py`) so both arms embed the
/// exact same input at a given `(length, seed)`.
fn synthetic_tokens(length: usize, seed: u64) -> Vec<i64> {
    assert!(length >= 3, "need room for [CLS] + >=1 interior + [SEP]");
    let interior = length - 2;
    let mut tokens = Vec::with_capacity(length);
    tokens.push(101i64);
    for index in 0..interior {
        let value = (index as u64)
            .wrapping_mul(9301)
            .wrapping_add(seed.wrapping_mul(49297))
            % 26000;
        let id = 2000i64 + value as i64;
        assert!(id < VOCAB_SIZE, "generated id out of vocab range");
        tokens.push(id);
    }
    tokens.push(102i64);
    tokens
}

fn dynamic_inputs_batch(rows: &[Vec<i64>]) -> (Vec<f32>, Vec<f32>, Vec<f32>) {
    let mut input_ids = Vec::new();
    let mut attention_mask = Vec::new();
    let mut token_type_ids = Vec::new();
    for row in rows {
        input_ids.extend(row.iter().map(|&id| id as f32));
        attention_mask.extend(std::iter::repeat_n(1.0f32, row.len()));
        token_type_ids.extend(std::iter::repeat_n(0.0f32, row.len()));
    }
    (input_ids, attention_mask, token_type_ids)
}

fn runtime_named_inputs<'data>(
    graph_inputs: &'data [String],
    input_ids: &'data [f32],
    attention_mask: &'data [f32],
    token_type_ids: &'data [f32],
) -> Vec<(&'data str, &'data [f32])> {
    graph_inputs
        .iter()
        .map(|name| {
            let data: &[f32] = match name.as_str() {
                "input_ids" => input_ids,
                "attention_mask" => attention_mask,
                "token_type_ids" => token_type_ids,
                other => panic!("unexpected graph input {other:?}"),
            };
            (name.as_str(), data)
        })
        .collect()
}

fn named_inputs<'data>(
    initializers: &'data [(String, Vec<f32>)],
    graph_inputs: &'data [String],
    input_ids: &'data [f32],
    attention_mask: &'data [f32],
    token_type_ids: &'data [f32],
) -> Vec<(&'data str, &'data [f32])> {
    let mut named: Vec<(&str, &[f32])> = initializers
        .iter()
        .map(|(name, data)| (name.as_str(), data.as_slice()))
        .collect();
    named.extend(runtime_named_inputs(
        graph_inputs,
        input_ids,
        attention_mask,
        token_type_ids,
    ));
    named
}

/// CLS pool over ONE row of a (possibly batched) `[batch, seq, 384]`
/// `last_hidden_state`: row `row_index`'s first token.
fn cls_normalize_row(data: &[f32], sequence_length: usize, row_index: usize) -> Vec<f32> {
    let row_stride = sequence_length * 384;
    let cls_offset = row_index * row_stride;
    let cls = &data[cls_offset..cls_offset + 384];
    let norm = cls.iter().map(|value| value * value).sum::<f32>().sqrt();
    cls.iter().map(|&value| value / norm).collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    a.iter()
        .zip(b.iter())
        .map(|(&left, &right)| (left - right).abs())
        .fold(0.0f32, f32::max)
}

fn coefficient_of_variation(samples: &[f64], mean: f64) -> f64 {
    if samples.len() < 2 || mean == 0.0 {
        return 0.0;
    }
    let variance = samples
        .iter()
        .map(|&value| (value - mean).powi(2))
        .sum::<f64>()
        / samples.len() as f64;
    variance.sqrt() / mean * 100.0
}

fn write_embedding(out_dir: &str, label: &str, embedding: &[f32]) {
    if out_dir.is_empty() {
        return;
    }
    let path = Path::new(out_dir).join(format!("{label}.txt"));
    let mut file = fs::File::create(&path).expect("create embedding dump file");
    let text: Vec<String> = embedding
        .iter()
        .map(|value| format!("{value:.9}"))
        .collect();
    writeln!(file, "{}", text.join(" ")).expect("write embedding dump file");
}

/// One arena-backed pass over a single `(batch, sequence_length)` shape,
/// own local (unbounded) lower+arena cache -- same shape `bge_eval.rs`'s
/// `run_pass_arena` uses, generalized to an arbitrary pinned batch extent.
#[allow(clippy::too_many_arguments)]
fn run_pass_arena_shape(
    graph: &proxima_onnx::messages::GraphProto<'_>,
    rows: &[Vec<i64>],
    batch: u64,
    sequence_length: u64,
    lower_cache: &mut BTreeMap<(u64, u64), proxima_onnx::lower::Lowered>,
    arena_cache: &mut BTreeMap<(u64, u64), StaticArena>,
    accelerate: bool,
) -> (Duration, Vec<f32>, Vec<u64>) {
    set_accelerate_gemm_enabled(accelerate);
    let mut pins = BTreeMap::new();
    pins.insert("batch_size", batch);
    pins.insert("sequence_length", sequence_length);
    let cache_key = (batch, sequence_length);

    let lowered = lower_cache.entry(cache_key).or_insert_with(|| {
        proxima_onnx::lower::lower_graph_pinned(graph, &pins)
            .expect("lower BGE-small with pinned batch/sequence axes")
    });
    let output: NodeId = lowered
        .graph_outputs
        .first()
        .expect("last_hidden_state output")
        .1;

    let arena = arena_cache.entry(cache_key).or_insert_with(|| {
        let constant_inputs: Vec<(&str, &[f32])> = lowered
            .initializers
            .iter()
            .map(|(name, data)| (name.as_str(), data.as_slice()))
            .collect();
        build_static_arena_with_constants(&lowered.program, &[], &[output], &constant_inputs)
            .expect("build BGE-small static arena")
    });

    let (input_ids, attention_mask, token_type_ids) = dynamic_inputs_batch(rows);
    let named = runtime_named_inputs(
        &lowered.graph_inputs,
        &input_ids,
        &attention_mask,
        &token_type_ids,
    );

    let eval_start = Instant::now();
    let evaluated = evaluate_named_with_arena(arena, &named)
        .expect("evaluate BGE-small on the StaticArena fast path");
    let elapsed = eval_start.elapsed();

    let (data, shape) = evaluated.get(output).expect("last_hidden_state present");
    assert_eq!(
        shape,
        &[batch, sequence_length, 384u64],
        "unexpected last_hidden_state shape"
    );
    assert!(
        data.iter().all(|value| value.is_finite()),
        "non-finite value in last_hidden_state"
    );
    let embedding = cls_normalize_row(data, sequence_length as usize, 0);
    (elapsed, embedding, shape.to_vec())
}

fn section_a_sequence_sweep(graph: &proxima_onnx::messages::GraphProto<'_>, out_dir: &str) {
    println!("\n\n=== (A) SEQUENCE-LENGTH SWEEP ===");
    println!(
        "max_position_embeddings = {MAX_POSITION_EMBEDDINGS} (HF config.json, verified not assumed)"
    );
    let lengths: [usize; 6] = [8, 32, 64, 128, 256, 512];
    const REPS: usize = 5;

    for &length in &lengths {
        let tokens = synthetic_tokens(length, length as u64);
        let rows = vec![tokens];
        let mut lower_cache = BTreeMap::new();
        let mut arena_cache = BTreeMap::new();

        let mut neon_means = Vec::new();
        let mut accel_means = Vec::new();
        let mut neon_embedding = Vec::new();
        let mut accel_embedding = Vec::new();

        for _run in 0..REPS {
            let (elapsed, embedding, _shape) = run_pass_arena_shape(
                graph,
                &rows,
                1,
                length as u64,
                &mut lower_cache,
                &mut arena_cache,
                false,
            );
            neon_means.push(elapsed.as_secs_f64() * 1000.0);
            neon_embedding = embedding;
        }
        for _run in 0..REPS {
            let (elapsed, embedding, _shape) = run_pass_arena_shape(
                graph,
                &rows,
                1,
                length as u64,
                &mut lower_cache,
                &mut arena_cache,
                true,
            );
            accel_means.push(elapsed.as_secs_f64() * 1000.0);
            accel_embedding = embedding;
        }
        set_accelerate_gemm_enabled(false);

        let neon_mean = neon_means.iter().sum::<f64>() / neon_means.len() as f64;
        let neon_cov = coefficient_of_variation(&neon_means, neon_mean);
        let accel_mean = accel_means.iter().sum::<f64>() / accel_means.len() as f64;
        let accel_cov = coefficient_of_variation(&accel_means, accel_mean);

        println!(
            "S={length:>4}: neon mean_ms={neon_mean:.4} CoV%={neon_cov:.2} ms/token={:.5} | accelerate mean_ms={accel_mean:.4} CoV%={accel_cov:.2} ms/token={:.5}",
            neon_mean / length as f64,
            accel_mean / length as f64,
        );

        write_embedding(out_dir, &format!("ours_neon_S{length}"), &neon_embedding);
        write_embedding(out_dir, &format!("ours_accel_S{length}"), &accel_embedding);

        #[cfg(feature = "bge-eval-diag")]
        {
            proxima_tensor::instrument::reset_reduce_gemm_path();
            proxima_tensor::instrument::reset_width_tile_decline();
            #[cfg(target_arch = "aarch64")]
            let (gate_before, invocations_before, _) = cpu::width_tile_counters();
            set_accelerate_gemm_enabled(false);
            let (_elapsed, _embedding, _shape) = run_pass_arena_shape(
                graph,
                &rows,
                1,
                length as u64,
                &mut lower_cache,
                &mut arena_cache,
                false,
            );
            let (dot_fast, _, width_fast, _, conv_tile, _, generic, _) =
                proxima_tensor::instrument::reduce_gemm_path_totals();
            let total_gemm = dot_fast + width_fast + conv_tile + generic;
            #[cfg(target_arch = "aarch64")]
            {
                let (gate_after, invocations_after, _) = cpu::width_tile_counters();
                println!(
                    "  engagement: width_fast_calls={width_fast}/{total_gemm} gemm-shaped folds \
                     (dot_fast={dot_fast} conv_tile={conv_tile} generic={generic}) \
                     gate_passes_delta={} tile_invocations_delta={}",
                    gate_after - gate_before,
                    invocations_after - invocations_before,
                );
            }
            #[cfg(not(target_arch = "aarch64"))]
            println!(
                "  engagement: width_fast_calls={width_fast}/{total_gemm} gemm-shaped folds \
                 (dot_fast={dot_fast} conv_tile={conv_tile} generic={generic}) \
                 [non-aarch64 host: width_tile_counters unavailable]"
            );
            let declines = proxima_tensor::instrument::width_tile_decline_snapshot();
            let mut by_reason: BTreeMap<String, u64> = BTreeMap::new();
            for (_node, reason, calls, _m, _k, _n, _stride_a, _stride_b) in &declines {
                *by_reason.entry(format!("{reason:?}")).or_insert(0) += calls;
            }
            if by_reason.is_empty() {
                println!("  declines: none (all gemm-shaped folds resolved Some)");
            } else {
                println!("  declines by reason (summed over declining nodes): {by_reason:?}");
            }
        }

        let diff = max_abs_diff(&neon_embedding, &accel_embedding);
        println!("  max_abs_diff(neon, accelerate) at S={length} = {diff:e}");
    }
}

fn section_b_cache_behaviour() {
    println!("\n\n=== (B) CACHE BEHAVIOUR UNDER VARIED LENGTHS ===");
    println!(
        "spread: 20 distinct lengths, 16 + 24*i for i in 0..20 (16..=472, step 24) -- \
         modeling document-chunk sizes from a short paragraph fragment (16 tok) up past \
         a full paragraph (472 tok), well over ARENA_CACHE_CAPACITY=8 distinct shapes; \
         200 draws in a fixed pseudo-random (non-cyclic) order over those 20 lengths, LCG \
         seeded, so no length repeats in a short streak that would flatter the cache"
    );

    let base_lengths: Vec<usize> = (0..20).map(|i| 16 + i * 24).collect();
    let mut draws = Vec::with_capacity(200);
    let mut state: u64 = 88172645463325252;
    for _ in 0..200 {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        let index = (state as usize) % base_lengths.len();
        draws.push(base_lengths[index]);
    }
    let distinct: std::collections::BTreeSet<usize> = draws.iter().copied().collect();
    println!(
        "distinct lengths actually drawn = {} of {} base lengths, over {} calls",
        distinct.len(),
        base_lengths.len(),
        draws.len()
    );

    run_cache_stream("exact-length (20 distinct shapes)", &draws);

    println!(
        "\ncontrolled probe: S=128 called twice per round (first call after eviction = miss, \
         immediate second call = hit, holding S constant so the split is never confounded by a \
         different S's own compute cost), then 9 other distinct lengths in between rounds to force \
         FIFO eviction of the S=128 entry (capacity=8) before the next round"
    );
    let mut probe_stream = Vec::new();
    let evictors: Vec<usize> = base_lengths.iter().take(9).copied().collect();
    for _round in 0..8 {
        probe_stream.push(128usize);
        probe_stream.push(128usize);
        probe_stream.extend(evictors.iter().copied());
    }
    run_cache_stream(
        "controlled-probe (S=128 miss-vs-hit, isolated)",
        &probe_stream,
    );

    let bucket_sizes = [32usize, 64, 128, 256, 512];
    let bucketed: Vec<usize> = draws
        .iter()
        .map(|&length| {
            *bucket_sizes
                .iter()
                .find(|&&bucket| bucket >= length)
                .unwrap_or(&512)
        })
        .collect();
    let bucketed_distinct: std::collections::BTreeSet<usize> = bucketed.iter().copied().collect();
    println!(
        "\nbucketed variant: same 200 draws, each rounded up to the nearest of {{32,64,128,256,512}} \
         -- {} distinct shapes now (proxy for padding to a bucket boundary; content beyond the \
         real length is not masked out here, this measures ONLY cache-pressure, not padded-output \
         correctness)",
        bucketed_distinct.len()
    );
    run_cache_stream("bucketed-length (5 distinct shapes)", &bucketed);
}

fn run_cache_stream(label: &str, lengths: &[usize]) {
    let model_path = env::var(MODEL_PATH_ENV).expect("model path checked by caller");
    let bytes = fs::read(&model_path).expect("read bge model.onnx");
    let model = proxima_onnx::pipe::parse_complete(&bytes).expect("parse");
    let graph = model.graph.as_ref().expect("graph");

    #[cfg(feature = "bge-eval-diag")]
    {
        cpu::arena_cache_reset();
    }
    set_accelerate_gemm_enabled(false);

    let mut lower_cache: BTreeMap<u64, proxima_onnx::lower::Lowered> = BTreeMap::new();
    let mut hit_times_ms = Vec::new();
    let mut miss_times_ms = Vec::new();

    for (call_index, &length) in lengths.iter().enumerate() {
        let tokens = synthetic_tokens(length, (call_index as u64) * 7919 + length as u64);
        let mut pins = BTreeMap::new();
        pins.insert("batch_size", 1u64);
        pins.insert("sequence_length", length as u64);
        let cache_key = length as u64;
        let (lowered, _hit) = proxima_onnx::lower::lower_graph_pinned_cached(
            &mut lower_cache,
            graph,
            &pins,
            cache_key,
        )
        .expect("lower BGE-small with pinned sequence axis (cached)");
        let output: NodeId = lowered
            .graph_outputs
            .first()
            .expect("last_hidden_state output")
            .1;
        let (input_ids, attention_mask, token_type_ids) = dynamic_inputs_batch(&[tokens]);
        let named = named_inputs(
            &lowered.initializers,
            &lowered.graph_inputs,
            &input_ids,
            &attention_mask,
            &token_type_ids,
        );

        #[cfg(feature = "bge-eval-diag")]
        let (builds_before, _hits_before) = cpu::arena_cache_totals();

        let call_start = Instant::now();
        let evaluated = evaluate_named(&lowered.program, &[], &named, &[output])
            .expect("evaluate BGE-small on the default (process-global-cached) path");
        let elapsed_ms = call_start.elapsed().as_secs_f64() * 1000.0;
        let (data, _shape) = evaluated.get(output).expect("output present");
        assert!(data.iter().all(|value| value.is_finite()));

        #[cfg(feature = "bge-eval-diag")]
        {
            let (builds_after, _hits_after) = cpu::arena_cache_totals();
            if builds_after > builds_before {
                miss_times_ms.push(elapsed_ms);
            } else {
                hit_times_ms.push(elapsed_ms);
            }
        }
    }

    #[cfg(feature = "bge-eval-diag")]
    {
        let (builds, hits) = cpu::arena_cache_totals();
        let packed = cpu::arena_cache_packed_node_count();
        let miss_mean = if miss_times_ms.is_empty() {
            0.0
        } else {
            miss_times_ms.iter().sum::<f64>() / miss_times_ms.len() as f64
        };
        let hit_mean = if hit_times_ms.is_empty() {
            0.0
        } else {
            hit_times_ms.iter().sum::<f64>() / hit_times_ms.len() as f64
        };
        println!(
            "[{label}] arena_cache: builds={builds} hits={hits} over {} calls, \
             packed_node_count(summed over whatever is checked in RIGHT NOW, capacity=8 entries)={packed}",
            lengths.len(),
        );
        println!(
            "[{label}] miss call latency: n={} mean_ms={miss_mean:.4} | hit call latency: n={} mean_ms={hit_mean:.4} | \
             miss/hit ratio={:.2}x",
            miss_times_ms.len(),
            hit_times_ms.len(),
            if hit_mean > 0.0 {
                miss_mean / hit_mean
            } else {
                0.0
            },
        );
        assert!(builds + hits > 0, "engagement N==0 is RED");
    }
}

fn section_c_batch_sweep(graph: &proxima_onnx::messages::GraphProto<'_>) {
    println!("\n\n=== (C) BATCH SWEEP (S=128) ===");
    const SEQUENCE_LENGTH: usize = 128;
    for &batch in &[1u64, 8, 32] {
        let rows: Vec<Vec<i64>> = (0..batch)
            .map(|row_index| synthetic_tokens(SEQUENCE_LENGTH, row_index * 31 + 128))
            .collect();
        let mut lower_cache = BTreeMap::new();
        let mut arena_cache = BTreeMap::new();

        let attempt = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let mut times_ms = Vec::new();
            for _run in 0..5 {
                let (elapsed, _embedding, _shape) = run_pass_arena_shape(
                    graph,
                    &rows,
                    batch,
                    SEQUENCE_LENGTH as u64,
                    &mut lower_cache,
                    &mut arena_cache,
                    false,
                );
                times_ms.push(elapsed.as_secs_f64() * 1000.0);
            }
            times_ms
        }));

        match attempt {
            Ok(times_ms) => {
                let total_mean = times_ms.iter().sum::<f64>() / times_ms.len() as f64;
                let cov = coefficient_of_variation(&times_ms, total_mean);
                let per_sentence = total_mean / batch as f64;
                let throughput = (batch as f64) / (total_mean / 1000.0);
                println!(
                    "batch={batch:>2}: total_ms/call={total_mean:.4} CoV%={cov:.2} \
                     ms/sentence={per_sentence:.4} throughput={throughput:.1} sentences/sec"
                );
            }
            Err(payload) => {
                let message = payload
                    .downcast_ref::<String>()
                    .cloned()
                    .or_else(|| {
                        payload
                            .downcast_ref::<&str>()
                            .map(|value| value.to_string())
                    })
                    .unwrap_or_else(|| "non-string panic payload".to_string());
                println!(
                    "batch={batch:>2}: FAILED -- {message} (batching this graph at batch_size={batch} \
                     is not supported by the current lowering/arena path without further work; \
                     reported plainly, not faked)"
                );
            }
        }
    }
}

fn main() {
    let Ok(model_path) = env::var(MODEL_PATH_ENV) else {
        eprintln!(
            "skipping: set {MODEL_PATH_ENV} to a local BGE-small-en-v1.5 model.onnx checkout"
        );
        return;
    };
    if !Path::new(&model_path).exists() {
        eprintln!("skipping: {MODEL_PATH_ENV}={model_path:?} does not exist");
        return;
    }
    let out_dir = env::var(OUT_DIR_ENV).unwrap_or_default();
    if !out_dir.is_empty() {
        fs::create_dir_all(&out_dir).expect("create embedding out dir");
    }

    let bytes = fs::read(&model_path).expect("read bge model.onnx");
    let model = proxima_onnx::pipe::parse_complete(&bytes).expect("parse");
    let graph = model.graph.as_ref().expect("graph");

    section_a_sequence_sweep(graph, &out_dir);
    section_b_cache_behaviour();
    section_c_batch_sweep(graph);

    println!("\n\n=== bge_traffic_sweep complete ===");
}
