//! Build-time sizing for proxima-listen.
//!
//! Folded from three former sibling crates' build scripts
//! (`proxima-listen`, `proxima-listeners-stream`, `proxima-listen-core`)
//! — each reads its own crate-root TOML (`proxima-listen.toml`,
//! `proxima-listeners-stream.toml`, `proxima-listen-core.toml`) plus
//! optional per-system env-var overrides, emitting a generated constant
//! module into `OUT_DIR/<name>_sized.rs`. The library `include!`s each
//! generated file inside its module's own `sized` submodule.
//!
//! These are the compile-time DEFAULTS. The per-process surface is
//! runtime conflaguration, which overrides them via config file / env
//! / fluent builder.

use std::env;
use std::path::PathBuf;

mod listen {
    use std::env;
    use std::fs;
    use std::path::{Path, PathBuf};

    use toml::Value;

    fn get_int(table: &Value, section: &str, key: &str) -> u64 {
        let raw = table
            .get(section)
            .and_then(|sec| sec.get(key))
            .and_then(Value::as_integer)
            .unwrap_or_else(|| {
                panic!("proxima-listen.toml: missing or non-integer [{section}].{key}")
            });
        u64::try_from(raw)
            .unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
    }

    /// Read `(section, key)` from the TOML, then apply the optional
    /// `PROXIMA_LISTEN_<SECTION>_<KEY>` env-var override.
    fn resolve(table: &Value, section: &str, key: &str) -> u64 {
        let env_name = format!(
            "PROXIMA_LISTEN_{}_{}",
            section.to_ascii_uppercase(),
            key.to_ascii_uppercase()
        );
        println!("cargo:rerun-if-env-changed={env_name}");
        if let Ok(raw) = env::var(&env_name) {
            return raw
                .parse()
                .unwrap_or_else(|err| panic!("{env_name} = {raw}: {err}"));
        }
        get_int(table, section, key)
    }

    fn require_nonzero(name: &str, value: u64) -> u64 {
        assert!(value > 0, "{name} must be non-zero; got {value}");
        value
    }

    fn require_i32(name: &str, value: u64) -> i32 {
        i32::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows i32"))
    }

    #[allow(clippy::expect_used)]
    pub fn emit_sizing_consts(out_dir: &Path) {
        let manifest_dir =
            env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
        let toml_path = PathBuf::from(&manifest_dir).join("proxima-listen.toml");
        println!("cargo:rerun-if-changed=proxima-listen.toml");

        let text = fs::read_to_string(&toml_path)
            .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
        let root: Value = text
            .parse()
            .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

        let backlog = require_i32(
            "listener.backlog",
            require_nonzero("listener.backlog", resolve(&root, "listener", "backlog")),
        );
        let drain_timeout_ms = require_nonzero(
            "listener.drain_timeout_ms",
            resolve(&root, "listener", "drain_timeout_ms"),
        );

        let out = format!(
            "// AUTO-GENERATED by build.rs from proxima-listen.toml. DO NOT EDIT.\n\
             /// TCP listen() backlog (SYN accept queue depth) for reuseport-bound\n\
             /// sockets (default). At no_std+no_alloc this const IS the queue's\n\
             /// reserved depth; at std it seeds `ListenTuningConfig::backlog`.\n\
             pub const LISTENER_BACKLOG_DEFAULT: i32 = {backlog};\n\
             /// Default graceful-drain timeout (ms, default cap). At\n\
             /// no_std+no_alloc this const IS the drain window; at std it seeds\n\
             /// `ListenTuningConfig::drain_timeout_ms`.\n\
             pub const LISTENER_DRAIN_TIMEOUT_MS_DEFAULT: u64 = {drain_timeout_ms};\n",
        );

        let out_path = out_dir.join("proxima_listen_sized.rs");
        fs::write(&out_path, out)
            .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
    }
}

mod listeners_stream {
    use std::env;
    use std::fs;
    use std::path::{Path, PathBuf};

    use toml::Value;

    fn get_str<'table>(table: &'table Value, section: &str, key: &str) -> &'table str {
        table
            .get(section)
            .and_then(|sec| sec.get(key))
            .and_then(Value::as_str)
            .unwrap_or_else(|| {
                panic!("proxima-listeners-stream.toml: missing or non-string [{section}].{key}")
            })
    }

    fn get_int(table: &Value, section: &str, key: &str) -> u64 {
        let raw = table
            .get(section)
            .and_then(|sec| sec.get(key))
            .and_then(Value::as_integer)
            .unwrap_or_else(|| {
                panic!("proxima-listeners-stream.toml: missing or non-integer [{section}].{key}")
            });
        u64::try_from(raw)
            .unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
    }

    fn env_name(section: &str, key: &str) -> String {
        format!(
            "PROXIMA_LISTENERS_STREAM_{}_{}",
            section.to_ascii_uppercase(),
            key.to_ascii_uppercase()
        )
    }

    fn resolve_str(table: &Value, section: &str, key: &str) -> String {
        let name = env_name(section, key);
        println!("cargo:rerun-if-env-changed={name}");
        env::var(&name).unwrap_or_else(|_| get_str(table, section, key).to_string())
    }

    fn resolve_int(table: &Value, section: &str, key: &str) -> u64 {
        let name = env_name(section, key);
        println!("cargo:rerun-if-env-changed={name}");
        if let Ok(raw) = env::var(&name) {
            return raw
                .parse()
                .unwrap_or_else(|err| panic!("{name} = {raw}: {err}"));
        }
        get_int(table, section, key)
    }

    fn require_nonzero(name: &str, value: u64) -> u64 {
        assert!(value > 0, "{name} must be non-zero; got {value}");
        value
    }

    fn require_usize(name: &str, value: u64) -> usize {
        usize::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows usize"))
    }

    #[allow(clippy::expect_used)]
    pub fn emit_sizing_consts(out_dir: &Path) {
        let manifest_dir =
            env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
        let toml_path = PathBuf::from(&manifest_dir).join("proxima-listeners-stream.toml");
        println!("cargo:rerun-if-changed=proxima-listeners-stream.toml");

        let text = fs::read_to_string(&toml_path)
            .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
        let root: Value = text
            .parse()
            .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

        let method = resolve_str(&root, "listener", "method");
        let path = resolve_str(&root, "listener", "path");
        let chunk_bytes = require_usize(
            "listener.chunk_bytes",
            require_nonzero(
                "listener.chunk_bytes",
                resolve_int(&root, "listener", "chunk_bytes"),
            ),
        );

        let out = format!(
            "// AUTO-GENERATED by build.rs from proxima-listeners-stream.toml. DO NOT EDIT.\n\
             /// Synthetic request method assigned to an accepted stream connection\n\
             /// (default). At std this seeds `ListenerStreamConfig::method`.\n\
             pub const LISTENER_METHOD_DEFAULT: &str = {method:?};\n\
             /// Synthetic request path assigned to an accepted stream connection\n\
             /// (default). At std this seeds `ListenerStreamConfig::path`.\n\
             pub const LISTENER_PATH_DEFAULT: &str = {path:?};\n\
             /// Read-buffer chunk size (bytes) for streaming a connection's body\n\
             /// (default cap). At no_std+no_alloc this const IS the read buffer's\n\
             /// reserved size; at std it seeds `ListenerStreamConfig::chunk_bytes`.\n\
             pub const LISTENER_CHUNK_BYTES_DEFAULT: usize = {chunk_bytes};\n",
        );

        let out_path = out_dir.join("proxima_listeners_stream_sized.rs");
        fs::write(&out_path, out)
            .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
    }
}

mod admission_core {
    use std::env;
    use std::fs;
    use std::path::{Path, PathBuf};

    use toml::Value;

    fn get_int(table: &Value, section: &str, key: &str) -> u64 {
        let raw = table
            .get(section)
            .and_then(|sec| sec.get(key))
            .and_then(Value::as_integer)
            .unwrap_or_else(|| {
                panic!("proxima-listen-core.toml: missing or non-integer [{section}].{key}")
            });
        u64::try_from(raw)
            .unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
    }

    /// Read `(section, key)` from the TOML, then apply the optional
    /// `PROXIMA_LISTEN_CORE_<SECTION>_<KEY>` env-var override.
    fn resolve(table: &Value, section: &str, key: &str) -> u64 {
        let env_name = format!(
            "PROXIMA_LISTEN_CORE_{}_{}",
            section.to_ascii_uppercase(),
            key.to_ascii_uppercase()
        );
        println!("cargo:rerun-if-env-changed={env_name}");
        if let Ok(raw) = env::var(&env_name) {
            return raw
                .parse()
                .unwrap_or_else(|err| panic!("{env_name} = {raw}: {err}"));
        }
        get_int(table, section, key)
    }

    fn require_nonzero(name: &str, value: u64) -> u64 {
        assert!(value > 0, "{name} must be non-zero; got {value}");
        value
    }

    fn require_usize(name: &str, value: u64) -> usize {
        usize::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows usize"))
    }

    fn require_power_of_two(name: &str, value: usize) -> usize {
        assert!(
            value.is_power_of_two(),
            "{name} = {value} must be a power of two (backs a fixed-cap heapless::FnvIndexMap)"
        );
        value
    }

    #[allow(clippy::expect_used)]
    pub fn emit_sizing_consts(out_dir: &Path) {
        let manifest_dir =
            env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
        let toml_path = PathBuf::from(&manifest_dir).join("proxima-listen-core.toml");
        println!("cargo:rerun-if-changed=proxima-listen-core.toml");

        let text = fs::read_to_string(&toml_path)
            .unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
        let root: Value = text
            .parse()
            .unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

        let table_cap = require_power_of_two(
            "admission.table_cap",
            require_usize(
                "admission.table_cap",
                require_nonzero(
                    "admission.table_cap",
                    resolve(&root, "admission", "table_cap"),
                ),
            ),
        );
        let peer_table_cap = require_power_of_two(
            "admission.peer_table_cap",
            require_usize(
                "admission.peer_table_cap",
                require_nonzero(
                    "admission.peer_table_cap",
                    resolve(&root, "admission", "peer_table_cap"),
                ),
            ),
        );
        let per_peer_cap = require_usize(
            "admission.per_peer_cap",
            require_nonzero(
                "admission.per_peer_cap",
                resolve(&root, "admission", "per_peer_cap"),
            ),
        );

        let out = format!(
            "// AUTO-GENERATED by build.rs from proxima-listen-core.toml. DO NOT EDIT.\n\
             /// Fixed cap on tracked live connections in the **no-alloc** admission\n\
             /// table. Only the `no_std + no_alloc` tier is bounded by this — the\n\
             /// `alloc` tier grows (its capacity is a runtime value, `usize::MAX` by\n\
             /// default). Must be a power of two for the backing\n\
             /// `heapless::FnvIndexMap`.\n\
             pub const ADMISSION_TABLE_CAP: usize = {table_cap};\n\
             /// Fixed cap on distinct peers tracked for per-peer shedding on the\n\
             /// **no-alloc** tier. Must be a power of two for the backing\n\
             /// `heapless::FnvIndexMap`.\n\
             pub const PEER_TABLE_CAP: usize = {peer_table_cap};\n\
             /// Default per-peer live-connection cap (the DoS knob): a peer sheds\n\
             /// with `ShedReason::PerPeerLimit` once its own live count reaches\n\
             /// this, even when the listener's global capacity has room left.\n\
             pub const PER_PEER_CAP_DEFAULT: usize = {per_peer_cap};\n",
        );

        let out_path = out_dir.join("proxima_listen_core_sized.rs");
        fs::write(&out_path, out)
            .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
    }
}

#[allow(clippy::expect_used)]
fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    listen::emit_sizing_consts(&out_dir);
    listeners_stream::emit_sizing_consts(&out_dir);
    admission_core::emit_sizing_consts(&out_dir);
}
