//! Build-time sizing for proxima-protocols' http1_codec, http3_codec, and
//! quic modules.
//!
//! Each module reads its own crate-root TOML + applies optional
//! per-system env-var overrides, emitting a generated constant module
//! into `OUT_DIR`. The library `include!`s each generated file inside
//! its own `sized` module (`crate::http1_codec::sized` for http1_codec,
//! `crate::sized` for http3_codec, `crate::quic::sized` for quic).

use std::env;
use std::path::PathBuf;

mod http1_codec_sizing {
    //! Reads `http1_codec.toml` at the crate root + applies an optional
    //! per-system env-var override, emitting a generated constant
    //! module into `OUT_DIR/proxima_protocols_http1_codec_sized.rs`.
    //!
    //! Env-var override naming: `PROXIMA_PROTOCOLS_HTTP1_CODEC_<SECTION>_<KEY>`
    //! (e.g. `PROXIMA_PROTOCOLS_HTTP1_CODEC_HEADER_INLINE_CAP=24`).

    use std::env;
    use std::fs;

    use proxima_build::sizing::{SizingSource, require_nonzero};

    #[allow(clippy::expect_used)]
    pub(super) fn emit_sizing_consts(out_dir: &std::path::Path) {
        let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
        let source = SizingSource::load(
            &manifest_dir,
            "http1_codec.toml",
            "PROXIMA_PROTOCOLS_HTTP1_CODEC",
        )
        .unwrap_or_else(|err| panic!("{err}"));

        let header_inline_cap = require_nonzero(
            "header.inline_cap",
            source
                .resolve_int("header", "inline_cap")
                .unwrap_or_else(|err| panic!("{err}")),
        );

        let body = format!(
            "// Generated by build.rs. Do not edit.\n\
             pub const HEADER_INLINE_CAP: usize = {header_inline_cap};\n"
        );

        let out_file = out_dir.join("proxima_protocols_http1_codec_sized.rs");
        fs::write(&out_file, body)
            .unwrap_or_else(|err| panic!("write {}: {err}", out_file.display()));
    }
}

mod http3_codec_sizing {
    //! Reads `http3_codec.toml` at the crate root + applies optional
    //! per-system env-var overrides, emitting a generated constant
    //! module into `OUT_DIR/proxima_h3_proto_sized.rs`.
    //!
    //! Env-var override naming: `PROXIMA_PROTOCOLS_HTTP3_CODEC_<SECTION>_<KEY>`
    //! (e.g. `PROXIMA_PROTOCOLS_HTTP3_CODEC_SERVER_MAX_CONCURRENT_REQUESTS=64`).

    use std::env;
    use std::fs;

    use proxima_build::sizing::{SizingSource, require_nonzero};

    fn require_pow2(name: &str, value: usize) -> usize {
        assert!(
            value.is_power_of_two(),
            "{name} must be a power of two (heapless::FnvIndexMap requirement); got {value}"
        );
        value
    }

    #[allow(clippy::expect_used)]
    pub(super) fn emit_sizing_consts(out_dir: &std::path::Path) {
        let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
        let source = SizingSource::load(
            &manifest_dir,
            "http3_codec.toml",
            "PROXIMA_PROTOCOLS_HTTP3_CODEC",
        )
        .unwrap_or_else(|err| panic!("{err}"));
        let resolve = |section: &str, key: &str| {
            source
                .resolve_int(section, key)
                .unwrap_or_else(|err| panic!("{err}"))
        };

        let server_max_concurrent_requests = require_pow2(
            "server.max_concurrent_requests",
            require_nonzero(
                "server.max_concurrent_requests",
                resolve("server", "max_concurrent_requests"),
            ),
        );
        let client_max_concurrent_requests = require_pow2(
            "client.max_concurrent_requests",
            require_nonzero(
                "client.max_concurrent_requests",
                resolve("client", "max_concurrent_requests"),
            ),
        );

        let qpack_decode_bounded_scratch_len = require_nonzero(
            "qpack.decode_bounded_scratch_len",
            resolve("qpack", "decode_bounded_scratch_len"),
        );

        let part_source_arena_len = require_nonzero(
            "qpack.part_source_arena_len",
            resolve("qpack", "part_source_arena_len"),
        );
        let part_source_max_headers = require_nonzero(
            "qpack.part_source_max_headers",
            resolve("qpack", "part_source_max_headers"),
        );

        let body = format!(
            "// Generated by build.rs. Do not edit.\n\
             pub const PROXIMA_PROTOCOLS_HTTP3_CODEC_SERVER_MAX_CONCURRENT_REQUESTS: usize = {server_max_concurrent_requests};\n\
             pub const PROXIMA_PROTOCOLS_HTTP3_CODEC_CLIENT_MAX_CONCURRENT_REQUESTS: usize = {client_max_concurrent_requests};\n\
             pub const PROXIMA_PROTOCOLS_HTTP3_CODEC_QPACK_DECODE_BOUNDED_SCRATCH_LEN: usize = {qpack_decode_bounded_scratch_len};\n\
             pub const PROXIMA_PROTOCOLS_HTTP3_CODEC_QPACK_PART_SOURCE_ARENA_LEN: usize = {part_source_arena_len};\n\
             pub const PROXIMA_PROTOCOLS_HTTP3_CODEC_QPACK_PART_SOURCE_MAX_HEADERS: usize = {part_source_max_headers};\n"
        );

        let out_file = out_dir.join("proxima_h3_proto_sized.rs");
        fs::write(&out_file, body)
            .unwrap_or_else(|err| panic!("write {}: {err}", out_file.display()));
    }
}

mod quic_sizing {
    //! Folded from proxima-quic-proto's own build.rs. Reads `quic.toml`
    //! at the crate root + applies optional per-system env-var
    //! overrides, emitting a generated constant module into
    //! `OUT_DIR/proxima_protocols_quic_sized.rs`.
    //!
    //! Env-var override naming: `PROXIMA_PROTOCOLS_QUIC_<SECTION>_<KEY>`
    //! (e.g. `PROXIMA_PROTOCOLS_QUIC_STREAMS_MAX_CONCURRENT_BIDI=64`).

    use std::env;
    use std::fs;

    use proxima_build::sizing::{SizingSource, require_nonneg, require_nonzero};

    fn require_pow2(name: &str, value: usize) -> usize {
        assert!(
            value.is_power_of_two(),
            "{name} must be a power of two (heapless::FnvIndexMap requirement); got {value}"
        );
        value
    }

    #[allow(clippy::expect_used)]
    pub(super) fn emit_sizing_consts(out_dir: &std::path::Path) {
        let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
        let source = SizingSource::load(&manifest_dir, "quic.toml", "PROXIMA_PROTOCOLS_QUIC")
            .unwrap_or_else(|err| panic!("{err}"));
        let resolve = |section: &str, key: &str| {
            source
                .resolve_int(section, key)
                .unwrap_or_else(|err| panic!("{err}"))
        };

        let streams_max_bidi = require_pow2(
            "streams.max_concurrent_bidi",
            require_nonzero(
                "streams.max_concurrent_bidi",
                resolve("streams", "max_concurrent_bidi"),
            ),
        );
        let streams_max_uni = require_pow2(
            "streams.max_concurrent_uni",
            require_nonzero(
                "streams.max_concurrent_uni",
                resolve("streams", "max_concurrent_uni"),
            ),
        );
        let streams_send_inline = require_nonzero(
            "streams.send_buffer_inline_bytes",
            resolve("streams", "send_buffer_inline_bytes"),
        );
        let streams_recv_inline = require_nonzero(
            "streams.recv_buffer_inline_bytes",
            resolve("streams", "recv_buffer_inline_bytes"),
        );
        let streams_reassembly_max_fragments = require_nonzero(
            "streams.reassembly_max_fragments",
            resolve("streams", "reassembly_max_fragments"),
        );
        let streams_reassembly_fragment_inline_bytes = require_nonzero(
            "streams.reassembly_fragment_inline_bytes",
            resolve("streams", "reassembly_fragment_inline_bytes"),
        );
        let connection_cid_queue_cap = require_nonzero(
            "connection.cid_queue_cap",
            resolve("connection", "cid_queue_cap"),
        );
        let connection_vn_max_offered_versions = require_nonzero(
            "connection.vn_max_offered_versions",
            resolve("connection", "vn_max_offered_versions"),
        );
        let ack_max_ranges = require_nonzero("ack.max_ranges", resolve("ack", "max_ranges"));
        let ack_default_max_ack_delay_micros = require_nonneg(
            "ack.default_max_ack_delay_micros",
            resolve("ack", "default_max_ack_delay_micros"),
        );
        let loss_max_sent_packets =
            require_nonzero("loss.max_sent_packets", resolve("loss", "max_sent_packets"));
        let loss_max_loss_burst =
            require_nonzero("loss.max_loss_burst", resolve("loss", "max_loss_burst"));
        let key_update_min_initiation_interval_micros = require_nonneg(
            "key_update.min_initiation_interval_micros",
            resolve("key_update", "min_initiation_interval_micros"),
        );
        let path_max_outstanding_challenges = require_nonzero(
            "path.max_outstanding_challenges",
            resolve("path", "max_outstanding_challenges"),
        );
        let bbr_min_rtt_filter_window_micros = require_nonneg(
            "bbr.min_rtt_filter_window_micros",
            resolve("bbr", "min_rtt_filter_window_micros"),
        );
        let endpoint_dcid_table_cap = require_pow2(
            "endpoint.dcid_table_cap",
            require_nonzero(
                "endpoint.dcid_table_cap",
                resolve("endpoint", "dcid_table_cap"),
            ),
        );
        let endpoint_max_udp_payload_size = require_nonneg(
            "endpoint.max_udp_payload_size",
            resolve("endpoint", "max_udp_payload_size"),
        );
        let zero_rtt_max_resumption_ticket_len = require_nonzero(
            "zero_rtt.max_resumption_ticket_len",
            resolve("zero_rtt", "max_resumption_ticket_len"),
        );
        let multipath_max_paths_per_connection = require_nonzero(
            "multipath.max_paths_per_connection",
            resolve("multipath", "max_paths_per_connection"),
        );
        let retry_token_max_token_len = require_nonzero(
            "retry_token.max_token_len",
            resolve("retry_token", "max_token_len"),
        );
        let retry_token_max_client_addr_len = require_nonzero(
            "retry_token.max_client_addr_len",
            resolve("retry_token", "max_client_addr_len"),
        );
        let retry_token_max_cid_len = require_nonzero(
            "retry_token.max_cid_len",
            resolve("retry_token", "max_cid_len"),
        );
        let datagram_send_queue_cap = require_nonzero(
            "datagram.send_queue_cap",
            resolve("datagram", "send_queue_cap"),
        );
        let datagram_recv_queue_cap = require_nonzero(
            "datagram.recv_queue_cap",
            resolve("datagram", "recv_queue_cap"),
        );
        let datagram_local_max_datagram_frame_size = require_nonneg(
            "datagram.local_max_datagram_frame_size",
            resolve("datagram", "local_max_datagram_frame_size"),
        );

        let handshake_early_data_max_bytes = require_nonzero(
            "handshake.early_data_max_bytes",
            resolve("handshake", "early_data_max_bytes"),
        );
        let handshake_early_data_max_datagrams = require_nonzero(
            "handshake.early_data_max_datagrams",
            resolve("handshake", "early_data_max_datagrams"),
        );
        let handshake_early_data_hold_micros = require_nonneg(
            "handshake.early_data_hold_micros",
            resolve("handshake", "early_data_hold_micros"),
        );
        let handshake_completion_micros = require_nonneg(
            "handshake.handshake_completion_micros",
            resolve("handshake", "handshake_completion_micros"),
        );

        let out = format!(
            "// AUTO-GENERATED by build.rs from quic.toml. DO NOT EDIT.\n\
             pub const STREAMS_MAX_CONCURRENT_BIDI: usize = {streams_max_bidi};\n\
             pub const STREAMS_MAX_CONCURRENT_UNI: usize = {streams_max_uni};\n\
             pub const STREAMS_SEND_BUFFER_INLINE_BYTES: usize = {streams_send_inline};\n\
             pub const STREAMS_RECV_BUFFER_INLINE_BYTES: usize = {streams_recv_inline};\n\
             pub const STREAMS_REASSEMBLY_MAX_FRAGMENTS: usize = {streams_reassembly_max_fragments};\n\
             pub const STREAMS_REASSEMBLY_FRAGMENT_INLINE_BYTES: usize = {streams_reassembly_fragment_inline_bytes};\n\
             pub const CONNECTION_CID_QUEUE_CAP: usize = {connection_cid_queue_cap};\n\
             pub const CONNECTION_VN_MAX_OFFERED_VERSIONS: usize = {connection_vn_max_offered_versions};\n\
             pub const ACK_MAX_RANGES: usize = {ack_max_ranges};\n\
             pub const ACK_DEFAULT_MAX_ACK_DELAY_MICROS: u64 = {ack_default_max_ack_delay_micros};\n\
             pub const LOSS_MAX_SENT_PACKETS: usize = {loss_max_sent_packets};\n\
             pub const LOSS_MAX_LOSS_BURST: usize = {loss_max_loss_burst};\n\
             pub const KEY_UPDATE_MIN_INITIATION_INTERVAL_MICROS: u64 = {key_update_min_initiation_interval_micros};\n\
             pub const PATH_MAX_OUTSTANDING_CHALLENGES: usize = {path_max_outstanding_challenges};\n\
             pub const BBR_MIN_RTT_FILTER_WINDOW_MICROS: u64 = {bbr_min_rtt_filter_window_micros};\n\
             pub const ENDPOINT_DCID_TABLE_CAP: usize = {endpoint_dcid_table_cap};\n\
             pub const ENDPOINT_MAX_UDP_PAYLOAD_SIZE: usize = {endpoint_max_udp_payload_size};\n\
             pub const MULTIPATH_MAX_PATHS_PER_CONNECTION: usize = {multipath_max_paths_per_connection};\n\
             pub const ZERO_RTT_MAX_RESUMPTION_TICKET_LEN: usize = {zero_rtt_max_resumption_ticket_len};\n\
             pub const RETRY_TOKEN_MAX_TOKEN_LEN: usize = {retry_token_max_token_len};\n\
             pub const RETRY_TOKEN_MAX_CLIENT_ADDR_LEN: usize = {retry_token_max_client_addr_len};\n\
             pub const RETRY_TOKEN_MAX_CID_LEN: usize = {retry_token_max_cid_len};\n\
             pub const DATAGRAM_SEND_QUEUE_CAP: usize = {datagram_send_queue_cap};\n\
             pub const DATAGRAM_RECV_QUEUE_CAP: usize = {datagram_recv_queue_cap};\n\
             pub const DATAGRAM_LOCAL_MAX_DATAGRAM_FRAME_SIZE: u64 = {datagram_local_max_datagram_frame_size};\n\
             pub const HANDSHAKE_EARLY_DATA_MAX_BYTES: usize = {handshake_early_data_max_bytes};\n\
             pub const HANDSHAKE_EARLY_DATA_MAX_DATAGRAMS: usize = {handshake_early_data_max_datagrams};\n\
             pub const HANDSHAKE_EARLY_DATA_HOLD_MICROS: u64 = {handshake_early_data_hold_micros};\n\
             pub const HANDSHAKE_COMPLETION_MICROS: u64 = {handshake_completion_micros};\n",
        );

        let out_path = out_dir.join("proxima_protocols_quic_sized.rs");
        fs::write(&out_path, out)
            .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
    }
}

#[allow(clippy::expect_used)]
fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"));
    http1_codec_sizing::emit_sizing_consts(&out_dir);
    http3_codec_sizing::emit_sizing_consts(&out_dir);
    quic_sizing::emit_sizing_consts(&out_dir);

    // proxima_alloc cfg — copied from proxima-primitives/build.rs (C3, the
    // DNS-TCP no-alloc rung): selects between an unbounded
    // `alloc::string::String` and a `heapless::String` inline buffer for
    // `dns::frame_codec::DnsTcpQuery::name`. Plain-feature fallback only
    // (no PROXIMA_PROFILE cross-axis here — this crate has no profile
    // resolution of its own).
    println!("cargo:rustc-check-cfg=cfg(proxima_alloc)");
    if env::var("CARGO_FEATURE_ALLOC").is_ok() {
        println!("cargo:rustc-cfg=proxima_alloc");
    }
}
