// build scripts fail-fast: a missing pkg-config / dpdk / compiler is a hard
// build error, so expect/unwrap here are the correct way to abort loudly.
#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use toml::Value;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    if env::var_os("CARGO_FEATURE_XDP").is_some() {
        build_xdp_sized();
    }
    if env::var_os("CARGO_FEATURE_DPDK").is_some() {
        build_dpdk_abi();
    }
}

// xdp: build-time sizing (principle 12)
//
// Reads `proxima-net-xdp.toml` at the crate root + applies optional
// `PROXIMA_NET_XDP_<SECTION>_<KEY>` env-var overrides, and emits a generated
// constant module into `OUT_DIR/proxima_net_xdp_sized.rs`. `crate::xdp::sized`
// `include!`s the generated file — the single source of truth for the ring
// depths, UMEM geometry, and RX drain batch.

fn xdp_require_nonzero(name: &str, value: u64) -> u64 {
    assert!(value > 0, "{name} must be non-zero; got {value}");
    value
}

fn xdp_require_pow2(name: &str, value: u64) -> u64 {
    assert!(
        value.is_power_of_two(),
        "{name} must be a power of two (SPSC ring index masks with size-1); got {value}"
    );
    value
}

fn xdp_require_u32(name: &str, value: u64) -> u32 {
    u32::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows u32"))
}

fn xdp_require_usize(name: &str, value: u64) -> usize {
    usize::try_from(value).unwrap_or_else(|_| panic!("{name} = {value} overflows usize"))
}

fn xdp_read_int(table: &Value, section: &str, key: &str) -> u64 {
    let raw = table
        .get(section)
        .and_then(|sec| sec.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| {
            panic!("proxima-net-xdp.toml: missing or non-integer [{section}].{key}")
        });
    u64::try_from(raw).unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
}

fn xdp_resolve(table: &Value, section: &str, key: &str) -> u64 {
    let env_name = format!(
        "PROXIMA_NET_XDP_{section}_{key}",
        section = section.to_uppercase(),
        key = key.to_uppercase()
    );
    println!("cargo:rerun-if-env-changed={env_name}");
    if let Ok(raw) = env::var(&env_name) {
        raw.parse::<u64>()
            .unwrap_or_else(|err| panic!("{env_name}={raw} must parse as u64: {err}"))
    } else {
        xdp_read_int(table, section, key)
    }
}

fn build_xdp_sized() {
    println!("cargo:rerun-if-changed=proxima-net-xdp.toml");

    let toml_text = fs::read_to_string("proxima-net-xdp.toml")
        .unwrap_or_else(|err| panic!("read proxima-net-xdp.toml: {err}"));
    let table: Value = toml::from_str(&toml_text)
        .unwrap_or_else(|err| panic!("parse proxima-net-xdp.toml: {err}"));

    let ring = |key: &str| {
        xdp_require_u32(
            key,
            xdp_require_pow2(
                key,
                xdp_require_nonzero(key, xdp_resolve(&table, "rings", key)),
            ),
        )
    };
    let fill = ring("fill");
    let completion = ring("completion");
    let rx = ring("rx");
    let tx = ring("tx");

    let frame_count = xdp_require_u32(
        "umem.frame_count",
        xdp_require_nonzero("umem.frame_count", xdp_resolve(&table, "umem", "frame_count")),
    );
    let frame_size = xdp_require_u32(
        "umem.frame_size",
        xdp_require_nonzero("umem.frame_size", xdp_resolve(&table, "umem", "frame_size")),
    );
    let headroom = xdp_require_u32("umem.headroom", xdp_resolve(&table, "umem", "headroom"));

    let rx_drain = xdp_require_usize(
        "batch.rx_drain",
        xdp_require_nonzero("batch.rx_drain", xdp_resolve(&table, "batch", "rx_drain")),
    );

    let out_dir =
        PathBuf::from(env::var_os("OUT_DIR").unwrap_or_else(|| panic!("OUT_DIR set by cargo")));
    let out_path = out_dir.join("proxima_net_xdp_sized.rs");
    let generated = format!(
        "// generated by build.rs from proxima-net-xdp.toml — do not edit by hand.\n\
         //\n\
         // Override any key at build time via PROXIMA_NET_XDP_<SECTION>_<KEY>.\n\
         \n\
         /// FILL ring depth (entries, power of two).\n\
         pub const RINGS_FILL: u32 = {fill};\n\
         /// COMPLETION ring depth (entries, power of two).\n\
         pub const RINGS_COMPLETION: u32 = {completion};\n\
         /// RX ring depth (entries, power of two).\n\
         pub const RINGS_RX: u32 = {rx};\n\
         /// TX ring depth (entries, power of two).\n\
         pub const RINGS_TX: u32 = {tx};\n\
         /// UMEM frame-pool count.\n\
         pub const UMEM_FRAME_COUNT: u32 = {frame_count};\n\
         /// UMEM per-frame chunk size in bytes.\n\
         pub const UMEM_FRAME_SIZE: u32 = {frame_size};\n\
         /// Extra per-frame headroom in bytes (on top of XDP_PACKET_HEADROOM).\n\
         pub const UMEM_HEADROOM: u32 = {headroom};\n\
         /// Descriptors moved per batched RX-drain ring op.\n\
         pub const BATCH_RX_DRAIN: usize = {rx_drain};\n",
    );
    fs::write(&out_path, generated).unwrap_or_else(|err| panic!("write sized.rs: {err}"));
}

// dpdk: ABI probe
//
// The dpdk hot path (rx/tx burst, mbuf alloc/free/field access) is `static
// inline` in the headers — no linkable symbol. Rather than a runtime C shim, we
// reimplement those in pure Rust over dpdk's real exported globals
// (`rte_eth_fp_ops`, `rte_mempool_ops_table`) and the mbuf struct fields. The
// only thing we cannot hardcode safely is the struct LAYOUT, which is
// version-specific. So this compiles + runs a tiny C probe that emits
// `offsetof`/`sizeof` from the INSTALLED dpdk headers and generates
// `dpdk_abi.rs` — the Rust hot path reads those, so the binding tracks
// whatever dpdk is present and can never go silently stale. The probe is
// build-time only; nothing C is linked into the crate.

fn dpdk_pkg_config(arg: &str) -> Vec<String> {
    let output = Command::new("pkg-config")
        .args(["--silence-errors", arg, "libdpdk"])
        .output()
        .expect("pkg-config must be on PATH to build proxima-net with --features dpdk");
    assert!(
        output.status.success(),
        "pkg-config {arg} libdpdk failed; is dpdk installed?"
    );
    String::from_utf8(output.stdout)
        .expect("pkg-config output is utf8")
        .split_whitespace()
        .map(String::from)
        .collect()
}

trait DpdkStatusExt {
    fn success_or_dump(&self, stderr: &[u8]) -> bool;
}
impl DpdkStatusExt for std::process::Output {
    fn success_or_dump(&self, stderr: &[u8]) -> bool {
        if !self.status.success() {
            eprintln!("{}", String::from_utf8_lossy(stderr));
        }
        self.status.success()
    }
}

fn build_dpdk_abi() {
    let cflags = dpdk_pkg_config("--cflags");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // 1. compile + run the ABI probe against the installed dpdk headers.
    let probe_c = out_dir.join("dpdk_abi_probe.c");
    fs::write(&probe_c, DPDK_PROBE_SRC).expect("write abi probe");
    let probe_bin = out_dir.join("dpdk_abi_probe");
    let compiler = env::var("CC").unwrap_or_else(|_| "cc".to_string());
    let mut compile = Command::new(&compiler);
    compile.arg(&probe_c).arg("-o").arg(&probe_bin);
    for flag in &cflags {
        compile.arg(flag);
    }
    let compiled = compile
        .status()
        .expect("run the C compiler for the abi probe");
    assert!(compiled.success(), "dpdk abi probe failed to compile");
    let run = Command::new(&probe_bin)
        .output()
        .expect("run the abi probe");
    assert!(
        run.success_or_dump(&run.stderr),
        "dpdk abi probe failed at runtime"
    );

    // 2. generate dpdk_abi.rs from the probe's `<type> <NAME> <value>` lines.
    let probe_out = String::from_utf8(run.stdout).expect("abi probe output is utf8");
    let mut generated =
        String::from("// generated by build.rs from the installed dpdk headers — do not edit\n");
    for line in probe_out.lines() {
        let mut fields = line.split_whitespace();
        let ty = fields.next().expect("probe line has a type");
        let name = fields.next().expect("probe line has a name");
        let value = fields.next().expect("probe line has a value");
        generated.push_str(&format!("pub const {name}: {ty} = {value};\n"));
    }
    fs::write(out_dir.join("dpdk_abi.rs"), generated).expect("write dpdk_abi.rs");

    // 3. link the real dpdk libraries (they export the control-plane symbols plus
    //    the rte_eth_fp_ops / rte_mempool_ops_table globals the hot path reads).
    for token in dpdk_pkg_config("--libs") {
        if let Some(lib) = token.strip_prefix("-l") {
            println!("cargo:rustc-link-lib={lib}");
        } else if let Some(dir) = token.strip_prefix("-L") {
            println!("cargo:rustc-link-search=native={dir}");
        } else {
            println!("cargo:rustc-link-arg={token}");
        }
    }
}

const DPDK_PROBE_SRC: &str = r#"
#include <stddef.h>
#include <stdio.h>
#include <rte_config.h>
#include <rte_mbuf.h>
#include <rte_mbuf_core.h>
#include <rte_ethdev.h>
#include <rte_ethdev_core.h>
#include <rte_mempool.h>
#include <rte_version.h>

#define OFF(s, f)  printf("usize %s %zu\n", #f, offsetof(struct s, f))
#define SZ(s)      printf("usize SIZEOF_%s %zu\n", #s, sizeof(struct s))

int main(void) {
    printf("usize MBUF_BUF_ADDR %zu\n", offsetof(struct rte_mbuf, buf_addr));
    printf("usize MBUF_DATA_OFF %zu\n", offsetof(struct rte_mbuf, data_off));
    printf("usize MBUF_DATA_LEN %zu\n", offsetof(struct rte_mbuf, data_len));
    printf("usize MBUF_PKT_LEN %zu\n", offsetof(struct rte_mbuf, pkt_len));
    printf("usize MBUF_BUF_LEN %zu\n", offsetof(struct rte_mbuf, buf_len));
    printf("usize MBUF_REFCNT %zu\n", offsetof(struct rte_mbuf, refcnt));
    printf("usize MBUF_NB_SEGS %zu\n", offsetof(struct rte_mbuf, nb_segs));
    printf("usize MBUF_PORT %zu\n", offsetof(struct rte_mbuf, port));
    printf("usize MBUF_OL_FLAGS %zu\n", offsetof(struct rte_mbuf, ol_flags));
    printf("usize MBUF_PACKET_TYPE %zu\n", offsetof(struct rte_mbuf, packet_type));
    printf("usize MBUF_VLAN_TCI %zu\n", offsetof(struct rte_mbuf, vlan_tci));
    printf("usize MBUF_VLAN_TCI_OUTER %zu\n", offsetof(struct rte_mbuf, vlan_tci_outer));
    printf("usize MBUF_TX_OFFLOAD %zu\n", offsetof(struct rte_mbuf, tx_offload));
    printf("usize MBUF_NEXT %zu\n", offsetof(struct rte_mbuf, next));
    printf("usize MBUF_POOL %zu\n", offsetof(struct rte_mbuf, pool));

    printf("usize SIZEOF_rte_eth_fp_ops %zu\n", sizeof(struct rte_eth_fp_ops));
    printf("usize FPOPS_RXQ_DATA %zu\n", offsetof(struct rte_eth_fp_ops, rxq) + offsetof(struct rte_ethdev_qdata, data));
    printf("usize FPOPS_RX_BURST %zu\n", offsetof(struct rte_eth_fp_ops, rx_pkt_burst));
    printf("usize FPOPS_TXQ_DATA %zu\n", offsetof(struct rte_eth_fp_ops, txq) + offsetof(struct rte_ethdev_qdata, data));
    printf("usize FPOPS_TX_BURST %zu\n", offsetof(struct rte_eth_fp_ops, tx_pkt_burst));

    printf("usize MEMPOOL_OPS_INDEX %zu\n", offsetof(struct rte_mempool, ops_index));
    printf("usize MEMPOOL_OPS_TABLE_OPS %zu\n", offsetof(struct rte_mempool_ops_table, ops));
    printf("usize SIZEOF_rte_mempool_ops %zu\n", sizeof(struct rte_mempool_ops));
    printf("usize OPS_ENQUEUE %zu\n", offsetof(struct rte_mempool_ops, enqueue));
    printf("usize OPS_DEQUEUE %zu\n", offsetof(struct rte_mempool_ops, dequeue));

    printf("usize SIZEOF_rte_eth_conf %zu\n", sizeof(struct rte_eth_conf));
    printf("usize HEADROOM %u\n", (unsigned)RTE_PKTMBUF_HEADROOM);
    printf("u16 PORT_INVALID %u\n", (unsigned)RTE_MBUF_PORT_INVALID);
    printf("u64 F_EXTERNAL %llu\n", (unsigned long long)RTE_MBUF_F_EXTERNAL);
    printf("u32 BUILT_VER_YEAR %u\n", (unsigned)RTE_VER_YEAR);
    printf("u32 BUILT_VER_MONTH %u\n", (unsigned)RTE_VER_MONTH);
    return 0;
}
"#;
