//! Build-time sizing for proxima-centauri (guiding principle 12).
//!
//! Reads `proxima-centauri.toml`, applies `PROXIMA_CENTAURI_<SECTION>_<KEY>`
//! environment overrides, and emits `pub const`s plus the atomic type aliases
//! into `$OUT_DIR/proxima_centauri_sized.rs`. Mirrors
//! `examples/no-std/build.rs` and `proxima-primitives/build.rs`.
//!
//! The entropy counter width is the one value that is a *target capability*
//! rather than a policy: Cortex-M3 has no 64-bit atomic instructions, so
//! `AtomicU64` does not compile there. `"auto"` resolves it from
//! `CARGO_CFG_TARGET_HAS_ATOMIC` instead of hard-coding a target assumption
//! in source, which is what this crate did before.

// a build script is the one place panicking is the correct behaviour: a
// misconfigured sizing file must stop the build loudly rather than silently
// bake a wrong constant into a no-alloc binary.
#![allow(clippy::expect_used, clippy::panic)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use toml::Value;

const CONFIG_FILE: &str = "proxima-centauri.toml";

fn override_name(section: &str, key: &str) -> String {
    format!(
        "PROXIMA_CENTAURI_{}_{}",
        section.to_uppercase(),
        key.to_uppercase()
    )
}

/// Read `[section].key` as an integer, letting an env override win.
fn sized_int(root: &Value, section: &str, key: &str) -> u64 {
    let name = override_name(section, key);
    println!("cargo:rerun-if-env-changed={name}");

    if let Ok(raw) = env::var(&name) {
        return raw
            .parse()
            .unwrap_or_else(|err| panic!("{name}={raw} is not a non-negative integer: {err}"));
    }

    let raw = root
        .get(section)
        .and_then(|table| table.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| panic!("{CONFIG_FILE}: missing or non-integer [{section}].{key}"));

    u64::try_from(raw).unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
}

/// Read `[section].key` as a string, letting an env override win.
fn sized_str(root: &Value, section: &str, key: &str) -> String {
    let name = override_name(section, key);
    println!("cargo:rerun-if-env-changed={name}");

    if let Ok(raw) = env::var(&name) {
        return raw;
    }

    root.get(section)
        .and_then(|table| table.get(key))
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("{CONFIG_FILE}: missing or non-string [{section}].{key}"))
        .to_owned()
}

/// Does the target have 64-bit atomics? Cargo hands us the widths as a
/// comma-separated list, so this is a fact about the target rather than a
/// guess keyed off the architecture name.
fn target_has_64_bit_atomics() -> bool {
    env::var("CARGO_CFG_TARGET_HAS_ATOMIC")
        .map(|widths| widths.split(',').any(|width| width.trim() == "64"))
        .unwrap_or(false)
}

fn resolve_counter_bits(requested: &str) -> u32 {
    match requested {
        "auto" => {
            if target_has_64_bit_atomics() {
                64
            } else {
                32
            }
        }
        "64" => {
            assert!(
                target_has_64_bit_atomics(),
                "[entropy].counter_bits = 64 but the target has no 64-bit atomics; \
                 use \"auto\" or 32"
            );
            64
        }
        "32" => 32,
        other => panic!("[entropy].counter_bits must be 32, 64, or \"auto\"; got {other:?}"),
    }
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let config_path = Path::new(&manifest_dir).join(CONFIG_FILE);
    println!("cargo:rerun-if-changed={CONFIG_FILE}");

    let text = fs::read_to_string(&config_path)
        .unwrap_or_else(|err| panic!("read {}: {err}", config_path.display()));
    let root: Value = text
        .parse()
        .unwrap_or_else(|err| panic!("parse {}: {err}", config_path.display()));

    let window_packets = sized_int(&root, "replay", "window_packets");
    assert!(
        window_packets > 0,
        "[replay].window_packets must be non-zero"
    );
    assert!(
        window_packets.is_multiple_of(64),
        "[replay].window_packets must be a multiple of 64 (the bitmap is whole u64 words); \
         got {window_packets}"
    );
    let window_words = window_packets / 64;

    let counter_bits = resolve_counter_bits(&sized_str(&root, "entropy", "counter_bits"));
    let max_payload = sized_int(&root, "esp", "max_payload_bytes");
    assert!(max_payload > 0, "[esp].max_payload_bytes must be non-zero");

    let mut generated = String::new();
    writeln!(
        generated,
        "// Generated by build.rs from {CONFIG_FILE}. Do not edit.\n"
    )
    .expect("write to string");

    writeln!(
        generated,
        "/// Packets tracked by the ESP anti-replay window.\n\
         pub const REPLAY_WINDOW_PACKETS: u64 = {window_packets};\n"
    )
    .expect("write to string");
    writeln!(
        generated,
        "/// `u64` words backing the replay bitmap.\n\
         pub const REPLAY_WINDOW_WORDS: usize = {window_words};\n"
    )
    .expect("write to string");

    writeln!(
        generated,
        "/// Width of the DRBG draw counter, resolved against the target's atomics.\n\
         pub const ENTROPY_COUNTER_BITS: u32 = {counter_bits};\n"
    )
    .expect("write to string");
    writeln!(
        generated,
        "/// Atomic counter type for the DRBG.\n\
         pub type EntropyCounter = core::sync::atomic::AtomicU{counter_bits};\n"
    )
    .expect("write to string");
    writeln!(
        generated,
        "/// Value type behind [`EntropyCounter`].\n\
         pub type EntropyCounterValue = u{counter_bits};\n"
    )
    .expect("write to string");

    writeln!(
        generated,
        "/// Largest payload a caller may seal into one packet.\n\
         pub const ESP_MAX_PAYLOAD_BYTES: usize = {max_payload};"
    )
    .expect("write to string");

    let destination = out_dir.join("proxima_centauri_sized.rs");
    fs::write(&destination, generated)
        .unwrap_or_else(|err| panic!("write {}: {err}", destination.display()));
}
