//! Per-variant state structs for [`ConnectionState`].
//!
//! Each variant carries exactly the data that's legal in that state.
//! Transitions consume the old variant (move semantics) and produce
//! the new one; the compiler enforces transition validity by virtue
//! of exhaustive `match`. No `Box<dyn Trait>`, no `Arc<Mutex<State>>`.
//!
//! Stream table, ACK scheduler, loss-detection state, congestion
//! controller, key-update manager, datagram queues, path challenger,
//! multipath table, and ECN state are all live members of the
//! variants below.

use alloc::collections::BTreeMap;
use alloc::vec::Vec;

use arrayvec::ArrayVec;

use crate::quic::ack::AckScheduler;
use crate::quic::anti_amplification::AntiAmplificationCounter;
use crate::quic::connection_id::CidQueue;
use crate::quic::crypto::initial_keys::InitialKeyPair;
use crate::quic::frame::Frame;
use crate::quic::packet::header::MAX_CID_LEN;
use crate::quic::packet_number::{RecvSpace, SendSpace};
use crate::quic::retry_token::MAX_TOKEN_LEN as RETRY_TOKEN_INLINE_CAP;
use crate::quic::side::Side;
use crate::quic::streams::{ConnectionFlowControl, StreamTable};
use crate::quic::time::{AckDelayExponent, Instant};
use crate::quic::tls::{Epoch, EpochSecrets};

/// Maximum bytes a peer's encoded transport-parameter set can occupy
/// in the connection state stash. Sized to comfortably hold a full
/// 18-parameter set including preferred-address (~150 B in practice).
pub const PEER_TRANSPORT_PARAMS_INLINE_BYTES: usize = 256;

/// Maximum CRYPTO bytes the connection buffers between TLS provider
/// calls and packetisation. A real QUIC ClientHello (ALPN + transport
/// params + key share) is ~1514 B and the server's first flight (cert +
/// cert-verify) is larger, so one MTU does NOT bound a single flight; the
/// transmit side fragments the buffered crypto across Initial datagrams.
/// Sized to comfortably hold a flight with a small (self-signed) cert.
pub const CRYPTO_INLINE_BYTES: usize = 4096;

/// Const-generic cap on issued / received connection IDs per RFC 9000
/// §18.2 `active_connection_id_limit`. Sourced from
/// `proxima-quic-proto.toml [connection].cid_queue_cap` (override via
/// `PROXIMA_QUIC_PROTO_CONNECTION_CID_QUEUE_CAP`).
pub const CID_QUEUE_CAP: usize = crate::quic::sized::CONNECTION_CID_QUEUE_CAP;

/// Per-connection cap on concurrently-active bidirectional streams.
/// Sourced from `proxima-quic-proto.toml [streams].max_concurrent_bidi`
/// (override via `PROXIMA_QUIC_PROTO_STREAMS_MAX_CONCURRENT_BIDI`).
///
/// Each stream carries inline send + recv buffers — raising this also
/// raises the dispatcher's stack footprint roughly linearly. Tune in
/// concert with [`crate::quic::streams::STREAM_SEND_INLINE`] +
/// [`crate::quic::streams::STREAM_RECV_INLINE`] for memory-constrained
/// targets.
pub const MAX_BIDI_STREAMS: usize = crate::quic::sized::STREAMS_MAX_CONCURRENT_BIDI;

/// Per-connection cap on concurrently-active unidirectional streams.
/// Sourced from `proxima-quic-proto.toml [streams].max_concurrent_uni`.
pub const MAX_UNI_STREAMS: usize = crate::quic::sized::STREAMS_MAX_CONCURRENT_UNI;

/// Fixed cap for the readable-stream set. Every readable stream lives in
/// the table (bounded by the concurrent caps); a reaped stream can linger
/// one drain cycle, so 2x the table cap is safe headroom and keeps the set
/// alloc-free — a `heapless::Vec` on the stack, not a `BTreeSet` that
/// allocates a tree node per readable stream every poll.
pub const READABLE_CAP: usize = (MAX_BIDI_STREAMS + MAX_UNI_STREAMS) * 2;

/// Connection identifier byte string.
pub type ConnectionIdBytes = ArrayVec<u8, MAX_CID_LEN>;

/// Inline byte stash for the peer's encoded transport parameters.
/// Populated when the TLS provider fires
/// [`crate::quic::tls::TlsEvent::PeerTransportParameters`].
pub type PeerTransportParametersBytes = ArrayVec<u8, PEER_TRANSPORT_PARAMS_INLINE_BYTES>;

/// Inline byte stash for outbound CRYPTO frame bytes pending packetisation.
pub type CryptoSendBuffer = ArrayVec<u8, CRYPTO_INLINE_BYTES>;

/// Per-epoch CRYPTO frame send-buffer + offset cursors for retransmit
/// support per RFC 9002 §6.2.4. Distinct from [`CryptoSendBuffer`]:
/// this holds ALL bytes generated by the TLS provider that have not
/// yet been ACKed (rather than just the next chunk to emit), and
/// tracks how many bytes have already gone out so retransmit
/// (resend the unacked prefix) is just a cursor reset.
#[derive(Debug, Clone, Default)]
pub struct CryptoEpochBuffer {
    /// Bytes for this epoch's CRYPTO frame stream that haven't yet
    /// been acknowledged. buffer[0] sits at stream offset
    /// [`Self::offset_acked`].
    buffer: ArrayVec<u8, CRYPTO_INLINE_BYTES>,
    /// Stream offset of `buffer[0]`. Advanced as the head of the
    /// buffer gets ACKed.
    offset_acked: u64,
    /// Number of buffer bytes already emitted in at least one outbound
    /// packet. Reset to 0 by loss detection to trigger retransmit.
    bytes_sent: usize,
    /// Per-PN tracking: PN → (start_in_buffer, length_emitted) for
    /// the bytes carried by that packet. Capped at 16 in-flight
    /// CRYPTO packets per epoch — handshake CRYPTO flights rarely
    /// exceed a couple of packets.
    inflight: heapless::LinearMap<u64, CryptoInflight, 16>,
}

/// One in-flight CRYPTO frame tracking record.
#[derive(Debug, Clone, Copy)]
pub struct CryptoInflight {
    /// Offset within the per-epoch buffer where the bytes carried by
    /// this packet started.
    pub start_in_buffer: usize,
    /// Number of bytes emitted in this packet's CRYPTO frame.
    pub length: usize,
}

impl CryptoEpochBuffer {
    /// Construct an empty buffer.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            buffer: ArrayVec::new_const(),
            offset_acked: 0,
            bytes_sent: 0,
            inflight: heapless::LinearMap::new(),
        }
    }

    /// Total bytes currently buffered (acked-prefix already dropped).
    #[must_use]
    pub fn buffered_len(&self) -> usize {
        self.buffer.len()
    }

    /// `true` if no bytes are currently buffered (either never pumped
    /// or every byte has been acknowledged).
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.buffer.is_empty()
    }

    /// Borrow the full buffer (acked-prefix-stripped) for tests +
    /// diagnostics. NOT the same as [`Self::unsent`] — this includes
    /// bytes already emitted in at least one in-flight packet.
    #[must_use]
    pub fn as_slice(&self) -> &[u8] {
        &self.buffer
    }

    /// Stream offset of the next byte that hasn't been emitted yet.
    #[must_use]
    pub fn next_send_offset(&self) -> u64 {
        self.offset_acked + self.bytes_sent as u64
    }

    /// Bytes ready to send (i.e. not yet emitted). Borrowed slice.
    #[must_use]
    pub fn unsent(&self) -> &[u8] {
        &self.buffer[self.bytes_sent..]
    }

    /// Append fresh bytes from the TLS provider's `write_handshake`.
    /// Returns the number of bytes accepted (caller's error path
    /// fires `BufferTooSmall` when this is less than `bytes.len()`).
    pub fn append(&mut self, bytes: &[u8]) -> usize {
        let cap = self.buffer.remaining_capacity();
        let take = core::cmp::min(cap, bytes.len());
        // try_extend_from_slice is infallible — bounded by `take`.
        let _ = self.buffer.try_extend_from_slice(&bytes[..take]);
        take
    }

    /// Mark `length` bytes (starting at `next_send_offset`) as
    /// emitted in packet `pn`. Returns the stream offset of the
    /// first emitted byte (which the caller writes into the
    /// CRYPTO frame's offset field).
    pub fn record_emission(&mut self, pn: u64, length: usize) -> u64 {
        let start = self.bytes_sent;
        let stream_offset = self.offset_acked + start as u64;
        self.bytes_sent = self.bytes_sent.saturating_add(length);
        if self.inflight.len() >= self.inflight.capacity()
            && let Some((&oldest_pn, _)) = self.inflight.iter().next()
        {
            let _ = self.inflight.remove(&oldest_pn);
        }
        let _ = self.inflight.insert(
            pn,
            CryptoInflight {
                start_in_buffer: start,
                length,
            },
        );
        stream_offset
    }

    /// Apply an ACK for packet `pn`. If the acked packet covered the
    /// head of the buffer, the prefix is dropped and `offset_acked`
    /// advances. Inflight entries for `pn` are removed regardless.
    pub fn on_pn_acked(&mut self, pn: u64) {
        let Some(record) = self.inflight.remove(&pn) else {
            return;
        };
        if record.start_in_buffer == 0 {
            let drop_len = record.length.min(self.buffer.len());
            // Truncate from the front via shift; arrayvec doesn't have
            // a cheap front-drop, so we copy the tail forward.
            self.buffer.drain(..drop_len);
            self.offset_acked = self.offset_acked.saturating_add(drop_len as u64);
            self.bytes_sent = self.bytes_sent.saturating_sub(drop_len);
            // Adjust every other inflight entry's start_in_buffer by
            // -drop_len so they remain consistent with the truncated
            // buffer.
            let pns: arrayvec::ArrayVec<u64, 16> = self.inflight.keys().copied().collect();
            for key in pns {
                if let Some(entry) = self.inflight.get_mut(&key) {
                    entry.start_in_buffer = entry.start_in_buffer.saturating_sub(drop_len);
                }
            }
        }
    }

    /// Apply a loss for packet `pn`. Conservative: reset
    /// `bytes_sent` to the start_in_buffer of the lost packet so
    /// the next emission re-sends those bytes (and everything
    /// after them) — matches RFC 9002 §6.2.4 ("retransmit existing
    /// data, possibly the entire ClientHello").
    pub fn on_pn_lost(&mut self, pn: u64) {
        if let Some(record) = self.inflight.remove(&pn) {
            self.bytes_sent = self.bytes_sent.min(record.start_in_buffer);
        }
    }

    /// PTO probe: reset the send cursor to 0 so the next emission
    /// re-sends the entire CRYPTO flight. RFC 9002 §6.2.4:
    /// "retransmit existing data, possibly the entire ClientHello."
    pub fn reset_for_pto(&mut self) {
        self.bytes_sent = 0;
    }

    /// `true` if there are bytes either pending first send or
    /// pending retransmit (after a loss-reset).
    #[must_use]
    pub fn has_unsent(&self) -> bool {
        self.bytes_sent < self.buffer.len()
    }
}

/// Upper bound on a single epoch's inbound CRYPTO stream offset+len. A
/// ClientHello (server side) or Certificate flight (client side) sits
/// well under this; the cap only fences a peer that names an absurd
/// offset. Lives inside the handshake-phase state, so the whole
/// reassembler is freed at Established — bounded by concurrent
/// handshakes, not total connection count.
pub const CRYPTO_RECV_BYTES: usize = 8192;

/// In-order reassembly for one epoch's inbound CRYPTO stream (RFC 9000
/// §19.6). CRYPTO frames carry a stream offset and may arrive out of
/// order or span several packets; the TLS provider must be fed
/// contiguous bytes from offset 0.
///
/// Out-of-order fragments live in a `BTreeMap` keyed by their start
/// offset — the key *is* the order, so reassembly looks up the fragment
/// covering the next expected byte directly; there is no sort pass.
#[derive(Debug, Clone, Default)]
pub struct CryptoRecvBuffer {
    /// Pending fragments keyed by start offset. The map keeps keys
    /// ordered for free; we index by offset, never sort.
    pending: BTreeMap<u64, Vec<u8>>,
    /// Contiguous prefix already assembled and handed to the provider
    /// (index == stream offset). Retained as the backing for the slice
    /// returned by [`Self::accept`]; its length is the next expected
    /// offset.
    head: Vec<u8>,
}

impl CryptoRecvBuffer {
    /// Construct an empty reassembler.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            pending: BTreeMap::new(),
            head: Vec::new(),
        }
    }

    /// Stage a CRYPTO fragment at `offset` and return the run of
    /// newly-contiguous bytes ready for the TLS provider, if any. A
    /// fragment naming an offset past [`CRYPTO_RECV_BYTES`] is dropped;
    /// the peer retransmits unacked CRYPTO so nothing is lost.
    pub fn accept(&mut self, offset: u64, data: &[u8]) -> Option<&[u8]> {
        let delivered = self.head.len() as u64;
        let end = offset.saturating_add(data.len() as u64);
        if data.is_empty() || end <= delivered || end > CRYPTO_RECV_BYTES as u64 {
            return None;
        }
        // Clip any prefix already in the contiguous head, then stash the
        // remainder under its (clipped) offset key.
        let start = offset.max(delivered);
        let head_already = (start - offset) as usize;
        self.pending.insert(start, data[head_already..].to_vec());

        let before = self.head.len();
        // Drain every fragment that now extends the contiguous prefix.
        // `range(..=delivered)` finds the fragment covering the next
        // byte without scanning or sorting.
        loop {
            let next = self.head.len() as u64;
            let Some((&frag_start, _)) = self.pending.range(..=next).next_back() else {
                break;
            };
            let Some(frag) = self.pending.remove(&frag_start) else {
                break;
            };
            let frag_end = frag_start + frag.len() as u64;
            if frag_end <= next {
                continue; // wholly covered already — drop
            }
            let from = (next - frag_start) as usize;
            self.head.extend_from_slice(&frag[from..]);
        }
        if self.head.len() > before {
            Some(&self.head[before..])
        } else {
            None
        }
    }
}

/// Inline byte stash for a server-issued Retry token. Sourced from
/// `proxima-quic-proto.toml [retry_token].max_token_len`.
pub type RetryTokenBuffer = ArrayVec<u8, RETRY_TOKEN_INLINE_CAP>;

/// Stubbed types that downstream components flesh out.
///
/// Each is `#[non_exhaustive]` so adding fields in C12+ is non-breaking.
pub mod stub {
    /// C14 loss detection — empty in C11.
    #[derive(Debug, Default, Clone, Copy)]
    #[non_exhaustive]
    pub struct LossDetection;

    /// C15+ congestion controller — empty in C11.
    #[derive(Debug, Default, Clone, Copy)]
    #[non_exhaustive]
    pub struct CongestionController;
}

/// Initial-epoch state (RFC 9000 §17.2.2).
///
/// Owned data:
/// - Side identity + per-connection monotonic-clock anchor + last-seen `now`.
/// - Initial keys derived from the first DCID (RFC 9001 §5.2).
/// - Local + remote CID queues (built incrementally as NEW_CONNECTION_ID
///   frames arrive; both empty at construction).
/// - The DCID we use to address packets to the peer (may differ from
///   `local_initial_dcid` once we receive the server's SCID in the
///   first server Initial).
/// - Initial-epoch packet-number space (send + recv).
/// - Anti-amplification budget (3× on the server; unconstrained on the client).
/// - Idle-timeout deadline.
/// - Pending CRYPTO bytes (ClientHello on the client side; ServerHello on
///   the server side).
#[derive(Debug, Clone)]
pub struct InitialState {
    pub side: Side,
    pub origin: Instant,
    pub last_now: Instant,
    pub local_initial_dcid: ConnectionIdBytes,
    pub local_initial_scid: ConnectionIdBytes,
    pub current_remote_cid: ConnectionIdBytes,
    pub local_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub remote_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub initial_send: SendSpace,
    pub initial_recv: RecvSpace<128>,
    pub initial_keys: InitialKeyPair,
    pub initial_ack_scheduler: AckScheduler,
    pub anti_amplification: AntiAmplificationCounter,
    pub idle_deadline: Instant,
    pub crypto_send_initial: CryptoEpochBuffer,
    /// In-order reassembly for the inbound Initial-epoch CRYPTO stream
    /// (the peer's ClientHello / ServerHello). RFC 9000 §19.6.
    pub crypto_recv_initial: CryptoRecvBuffer,
    /// Original DCID the client used in its very first Initial flight.
    /// `Some(_)` only after a Retry has been processed — the field is
    /// preserved across the FSM reset so the next ClientHello can echo
    /// it via the `original_destination_connection_id` transport
    /// parameter per RFC 9000 §7.3 + §17.2.5.
    pub original_destination_cid: Option<ConnectionIdBytes>,
    /// Server-issued Retry token to attach to the next Initial flight
    /// per RFC 9000 §17.2.5. Empty until a Retry is processed.
    pub retry_token: RetryTokenBuffer,
    /// Set true once any Retry packet has been successfully validated
    /// and applied. Subsequent Retry packets MUST be discarded per
    /// RFC 9000 §17.2.5.
    pub retry_received: bool,
}

/// Handshake-epoch state (RFC 9000 §17.2.4).
///
/// Inherits the live Initial-epoch state (we may still owe Initial-space
/// ACKs per RFC 9001 §4.9.1) and adds Handshake-epoch keys, PN space,
/// and CRYPTO buffer.
#[derive(Debug, Clone)]
pub struct HandshakeState {
    pub side: Side,
    pub origin: Instant,
    pub last_now: Instant,
    pub current_remote_cid: ConnectionIdBytes,
    pub local_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub remote_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub anti_amplification: AntiAmplificationCounter,
    pub idle_deadline: Instant,
    pub local_initial_scid: ConnectionIdBytes,
    pub initial_send: SendSpace,
    pub initial_recv: RecvSpace<128>,
    pub initial_keys: InitialKeyPair,
    pub initial_ack_scheduler: AckScheduler,
    pub handshake_send: SendSpace,
    pub handshake_recv: RecvSpace<128>,
    pub handshake_secrets: EpochSecrets,
    pub handshake_ack_scheduler: AckScheduler,
    pub crypto_send_initial: CryptoEpochBuffer,
    pub crypto_send_handshake: CryptoEpochBuffer,
    /// In-order reassembly for the inbound Handshake-epoch CRYPTO stream
    /// (the peer's Certificate / CertVerify / Finished flight, which
    /// routinely spans several packets). RFC 9000 §19.6.
    pub crypto_recv_handshake: CryptoRecvBuffer,
    /// Retry token (RFC 9000 §8.1.2) carried over from the Initial state
    /// so any retained Initial-epoch ACK sent after the transition still
    /// echoes it. Empty when no Retry was processed.
    pub retry_token: RetryTokenBuffer,
    /// Set once `TlsEvent::PeerTransportParameters` has fired. Empty
    /// until then.
    pub peer_transport_params: PeerTransportParametersBytes,
    /// Application-epoch secrets the TLS provider may emit early
    /// (before the peer's final handshake CRYPTO arrives). Server-side
    /// rustls produces both KeyChange::Handshake and KeyChange::OneRtt
    /// in the same write_hs sequence; we stash the latter here so the
    /// Handshake→Established transition can consume it once the
    /// peer's Finished closes the handshake.
    pub app_secrets_staged: Option<EpochSecrets>,
}

/// Established-epoch state (RFC 9000 §10).
///
/// At this point handshake confirmation has occurred (RFC 9001 §4.1.2)
/// and 1-RTT keys are installed. Initial + Handshake-epoch keys are
/// retained for up to 3 × PTO per RFC 9001 §4.9.2.
#[derive(Debug, Clone)]
pub struct EstablishedState {
    pub side: Side,
    /// Server-only one-shot: `true` until the server's HANDSHAKE_DONE
    /// frame (RFC 9000 §19.20 / RFC 9001 §4.1.2) has been queued for
    /// send. It confirms the handshake to the client; clients that gate
    /// 1-RTT progress on it (OpenSSL's QUIC backend) stall without it.
    pub handshake_done_pending: bool,
    /// Client-side: set once a HANDSHAKE_DONE frame has actually been
    /// received (RFC 9000 §19.20). Stays `false` on the server (which
    /// sends, never receives, the frame).
    pub received_handshake_done: bool,
    pub origin: Instant,
    pub last_now: Instant,
    pub current_remote_cid: ConnectionIdBytes,
    pub local_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub remote_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub local_ack_delay_exponent: AckDelayExponent,
    pub peer_ack_delay_exponent: AckDelayExponent,
    pub idle_deadline: Instant,
    pub application_send: SendSpace,
    pub application_recv: RecvSpace<128>,
    pub application_secrets: EpochSecrets,
    pub application_ack_scheduler: AckScheduler,
    pub peer_transport_params: PeerTransportParametersBytes,
    pub streams: StreamTable<MAX_BIDI_STREAMS, MAX_UNI_STREAMS>,
    /// Streams that received data or a FIN since the driver last
    /// serviced them. The H3 driver reads only these per step instead
    /// of scanning the whole table — O(active) not O(N) per datagram,
    /// the difference between flat and inverse throughput scaling.
    pub readable: heapless::Vec<u64, READABLE_CAP>,
    pub flow_control: ConnectionFlowControl,
    /// MAX_STREAMS state per RFC 9000 §4.6 — tracks peer-imposed
    /// cap on locally-initiated bidirectional streams +
    /// locally-advertised cap on peer-initiated bidirectional
    /// streams. Initialized from peer's `initial_max_streams_bidi`
    /// transport parameter at handshake completion.
    pub max_streams_bidi: crate::quic::streams::MaxStreamsState,
    /// MAX_STREAMS state for unidirectional streams. Initialized
    /// from peer's `initial_max_streams_uni` TP.
    pub max_streams_uni: crate::quic::streams::MaxStreamsState,
    pub loss_detection: stub::LossDetection,
    pub congestion_control: stub::CongestionController,
    /// RFC 9221 DATAGRAM send + recv queues. `peer_max` is updated
    /// from `max_datagram_frame_size` transport parameter at
    /// transition_handshake_to_established (C25.1).
    pub datagrams: crate::quic::datagram::DatagramQueues,
    /// RFC 9000 §8.2 / §9 path validator. Owns outstanding
    /// PATH_CHALLENGE tokens + the single pending PATH_RESPONSE
    /// awaiting emission. Initiating + observing wired by C21.1.
    pub path_challenger: crate::quic::path::PathChallenger,
    /// RFC 9001 §6 key-update state machine. Constructed at
    /// Established entry with handshake_confirmed=true; tracks
    /// current generation, current-phase-acked flag (lifted on
    /// 1-RTT ACK receipt), and pending next-phase secrets staging.
    pub key_update: crate::quic::key_update::KeyUpdateManager,
    /// draft-ietf-quic-multipath-21 path table — populated only when
    /// peer advertised `initial_max_path_id` TP. Empty / inactive
    /// when multipath isn't negotiated.
    pub multipath: crate::quic::multipath::MultipathTable,
    /// RFC 9000 §13.4 + RFC 8311 ECN state for the Application
    /// (1-RTT) packet space. Per RFC §13.4 ECN is per-PN-space; this
    /// is the 1-RTT instance. (Initial / Handshake epochs MUST NOT
    /// be ECN-marked per the spec's validation rules.)
    pub ecn: crate::quic::ecn::EcnState,
    /// Largest `path_id` we'll accept inbound. Sourced from peer's
    /// `initial_max_path_id` TP per draft §2.1; raised via inbound
    /// MAX_PATH_ID frames.
    pub local_max_path_id: u64,
    /// Largest `path_id` peer will accept; we send MAX_PATH_ID to
    /// raise it; we MUST NOT issue path IDs above this value.
    pub peer_max_path_id: u64,
    /// Per-stream initial credits per RFC 9000 §4.5 + §18.2:
    /// peer's TP 0x05 — credit for streams the peer opens (= our
    /// send credit on peer-opened bi-streams).
    pub peer_initial_max_stream_data_bidi_local: u64,
    /// Peer's TP 0x06 — credit for streams we open (= our send
    /// credit on locally-opened bi-streams).
    pub peer_initial_max_stream_data_bidi_remote: u64,
    /// Peer's TP 0x07 — credit for uni streams we open (= our send
    /// credit on locally-opened uni-streams).
    pub peer_initial_max_stream_data_uni: u64,
    /// Our TP 0x05 — credit for streams we open (= our recv credit
    /// on locally-opened bi-streams). Symmetric counterpart of
    /// `peer_initial_max_stream_data_bidi_local`.
    pub local_initial_max_stream_data_bidi_local: u64,
    /// Our TP 0x06 — credit for streams peer opens (= our recv
    /// credit on peer-opened bi-streams).
    pub local_initial_max_stream_data_bidi_remote: u64,
    /// Our TP 0x07 — credit for uni streams peer opens (= our recv
    /// credit on peer-opened uni-streams).
    pub local_initial_max_stream_data_uni: u64,
    /// Handshake-epoch keys retained per RFC 9001 §4.9.2 — peer may
    /// still send Handshake-encrypted ACKs for up to 3 × PTO after
    /// HandshakeConfirmed. `None` once discarded.
    pub handshake_secrets_retained: Option<EpochSecrets>,
    pub handshake_keys_retain_until: Option<Instant>,
    /// SCID we put in our Initial flight, retained so the Handshake-
    /// epoch tail packets emitted from Established carry the same
    /// source CID per RFC 9000 §17.2.
    pub local_initial_scid_retained: ConnectionIdBytes,
    /// Handshake-epoch send context carried into Established so the
    /// client's Finished + any post-confirmation Handshake-epoch ACK
    /// can still be transmitted (RFC 9001 §4.1.2 — client may emit
    /// 1-RTT and Handshake interleaved until the server has confirmed).
    /// Dropped together with `handshake_secrets_retained` once the
    /// 3 × PTO retention window expires.
    pub handshake_send_retained: SendSpace,
    pub handshake_recv_retained: RecvSpace<128>,
    pub crypto_send_handshake_retained: CryptoEpochBuffer,
    pub handshake_ack_scheduler_retained: AckScheduler,
    /// Initial-epoch ACK scheduler retained for the same RFC 9001
    /// §4.9.1 window — peer's Initial-epoch packets may still arrive
    /// and need ACKs in the Initial epoch even after we've transitioned.
    pub initial_ack_scheduler_retained: AckScheduler,
    pub initial_recv_retained: RecvSpace<128>,
    pub initial_keys_retained: Option<crate::quic::crypto::initial_keys::InitialKeyPair>,
    /// Per-PN tracked frame intents for 1-RTT retransmit-on-loss
    /// (RFC 9002 §6.1) on the primary path (path_id = 0). The
    /// connection-level emitter pushes intents here keyed by the
    /// packet number that carried them; on ACK the entry is dropped,
    /// on loss the entry's intents are re-enqueued.
    ///
    /// boxed because the heapless `FnvIndexMap<u64, Vec<_>, 1024>` is
    /// ~32 KB inline and would push `EstablishedState` past test-thread
    /// stack capacity; one heap alloc up front beats per-entry allocs.
    pub(crate) inflight_app_frames: alloc::boxed::Box<super::InflightFrames>,
    /// Byte arena holding the STREAM-frame payloads referenced by the
    /// in-flight `FrameIntent::Stream { arena_offset, len }` entries.
    /// Store-once: bytes are appended here (not copied into each
    /// FrameIntent), so the per-frame intent is pure `Copy` metadata and
    /// moving it through the send pipeline never copies the payload. Reset
    /// to offset 0 when both `inflight_app_frames` and `pending_retx` are
    /// empty (no live reference into the arena).
    pub(crate) retx_arena: proxima_core::arena::ByteArena,
    /// 1-RTT frame intents on the primary path waiting to be
    /// re-emitted. Drained by `poll_transmit_established` before
    /// scanning streams for new data.
    pub(crate) pending_retx: alloc::boxed::Box<super::PendingRetx>,
    /// PTO fallback: when PTO fires with nothing in-flight, this
    /// flag causes poll_transmit_established to emit a PING frame
    /// (which IS ack-eliciting, unlike ACK-only). Cleared after
    /// emission.
    pub(crate) ping_pending: bool,
    /// Per-non-primary-path 1-RTT PN-space state per
    /// draft-ietf-quic-multipath-21. Each entry carries its own
    /// SendSpace + RecvSpace + AckScheduler + inflight frames so
    /// PATH_ACK frames can drive per-path loss detection
    /// independently of the primary path's RFC 9000 ACK stream.
    /// Path 0 is NOT in this map — it uses the primary fields above.
    pub(crate) path_pn_state:
        heapless::LinearMap<u32, PathPnState, { crate::quic::multipath::MAX_PATHS_PER_CONNECTION }>,
}

impl EstablishedState {
    /// Mark `stream_id` readable for the next driver step. Deduped; the
    /// 2x-table-cap sizing makes the set unable to fill, so a dropped push
    /// is unreachable (a full set would only re-mark an already-readable
    /// stream the driver will service anyway).
    pub fn mark_readable(&mut self, stream_id: u64) {
        if !self.readable.contains(&stream_id) {
            let _ = self.readable.push(stream_id);
        }
    }

    /// Drop `stream_id` from the readable set (reaped/serviced stream).
    pub fn clear_readable(&mut self, stream_id: u64) {
        if let Some(pos) = self.readable.iter().position(|entry| *entry == stream_id) {
            self.readable.swap_remove(pos);
        }
    }
}

/// Per-non-zero-path 1-RTT packet-number state.
#[derive(Debug, Clone, Default)]
pub struct PathPnState {
    pub send: SendSpace,
    pub recv: RecvSpace<128>,
    pub ack_scheduler: AckScheduler,
    /// boxed for the same reason as `EstablishedState::inflight_app_frames`
    /// — the heapless map is fat inline; one alloc per non-primary path.
    pub(crate) inflight_app_frames: alloc::boxed::Box<super::InflightFrames>,
    pub(crate) pending_retx: alloc::boxed::Box<super::PendingRetx>,
}

#[allow(dead_code)]
impl PathPnState {
    /// Borrow the in-flight 1-RTT frame intents keyed by PN.
    #[must_use]
    pub(crate) fn inflight_frames(&self) -> &super::InflightFrames {
        &self.inflight_app_frames
    }

    /// Borrow the in-flight frame intents mutably.
    pub(crate) fn inflight_frames_mut(&mut self) -> &mut super::InflightFrames {
        &mut self.inflight_app_frames
    }

    /// Borrow the pending re-transmit queue.
    #[must_use]
    pub(crate) fn pending_retx(&self) -> &[super::FrameIntent] {
        self.pending_retx.as_slice()
    }

    /// Push intents back onto this path's pending re-transmit queue
    /// (e.g. after loss detection declared their carrier PN lost).
    /// Bounded by `MAX_INFLIGHT_FRAME_PACKETS`; overflowing pushes
    /// silently drop. By construction every retx intent first lived
    /// as an in-flight intent (also capped at the same constant), so
    /// overflow here would mean a runtime-cap violation upstream.
    pub(crate) fn requeue(&mut self, intents: alloc::vec::Vec<super::FrameIntent>) {
        let mut combined: alloc::boxed::Box<super::PendingRetx> =
            alloc::boxed::Box::new(super::PendingRetx::new());
        for intent in intents {
            if combined.push(intent).is_err() {
                break;
            }
        }
        let prior = core::mem::replace(
            &mut self.pending_retx,
            alloc::boxed::Box::new(super::PendingRetx::new()),
        );
        for intent in *prior {
            if combined.push(intent).is_err() {
                break;
            }
        }
        self.pending_retx = combined;
    }
}

/// Closing state (RFC 9000 §10.2 — connection is shutting down,
/// retransmitting CONNECTION_CLOSE on inbound traffic, awaiting peer's
/// CONNECTION_CLOSE to transition to Draining).
#[derive(Debug, Clone)]
pub struct ClosingState {
    pub side: Side,
    pub last_now: Instant,
    pub close_frame: ConnectionCloseFrameOwned,
    pub close_deadline: Instant,
    /// Retained for re-encoding CONNECTION_CLOSE on retransmit.
    pub application_secrets: Option<EpochSecrets>,
    pub handshake_secrets: Option<EpochSecrets>,
    pub initial_keys: Option<InitialKeyPair>,
    pub remote_cid_queue: CidQueue<CID_QUEUE_CAP>,
    pub current_remote_cid: ConnectionIdBytes,
    pub retransmit_close_after: Instant,
    /// The epoch at which the CONNECTION_CLOSE was originally minted —
    /// retransmits use the deepest-installed key per RFC 9000 §10.2.3.
    pub close_epoch: Epoch,
    /// Preserved from the established state so each retransmit of
    /// CONNECTION_CLOSE uses a fresh PN instead of reusing 0. A reused
    /// PN would share an AEAD nonce with a prior application packet.
    pub close_send_space: crate::quic::packet_number::SendSpace,
}

/// Draining state (RFC 9000 §10.2 — peer ack'd or sent CLOSE; we silently
/// discard everything until `drain_deadline`).
#[derive(Debug, Clone)]
pub struct DrainingState {
    pub last_now: Instant,
    pub drain_deadline: Instant,
}

/// Discriminated FSM enum per the C11 design pass.
//
// Per the FSM design + principle 11, every variant owns its per-state
// data INLINE — no `Box<dyn Trait>`, no `Arc<Mutex<…>>`. The enum's
// stack size is the size of its largest variant (HandshakeState today);
// boxing variants would defeat the cache-friendly transition design.
// Transitions happen on the order of microseconds (handshake confirm,
// close, drain) — the per-move cost is in the noise compared to the
// AEAD work that wraps each one.
#[derive(Debug, Clone)]
#[allow(clippy::large_enum_variant)]
#[non_exhaustive]
pub enum ConnectionState {
    Initial(InitialState),
    Handshake(HandshakeState),
    // Boxed: EstablishedState is by far the largest variant (the inline
    // stream table + buffers). Inline, it sized the whole enum to ~MB, so
    // every ConnectionState construction/move spilled a multi-MB stack
    // temporary that the prologue zeroed — ~94% of handle_datagram's self
    // time per packet. Boxing keeps the enum pointer-sized.
    Established(alloc::boxed::Box<EstablishedState>),
    Closing(ClosingState),
    Draining(DrainingState),
    Closed,
}

/// Errors from [`InitialState::reset_for_retry`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum RetryResetError {
    /// A Retry was already processed on this connection. RFC 9000
    /// §17.2.5 — "client MUST discard any Retry packets that it
    /// receives after it has received and processed an initial Retry
    /// packet."
    AlreadyApplied,
    /// `retry_scid` was longer than [`MAX_CID_LEN`].
    RetryScidTooLong,
    /// `retry_token` overflowed [`RETRY_TOKEN_INLINE_CAP`].
    TokenTooLong,
    /// Re-derivation of Initial keys from `retry_scid` failed.
    InitialKeysDerive(crate::quic::crypto::expand_label::ExpandError),
}

impl InitialState {
    /// Reset the Initial-epoch state in response to a server Retry
    /// packet per RFC 9000 §17.2.5:
    ///
    /// 1. Stash the original `local_initial_dcid` into
    ///    `original_destination_cid` (preserved across the reset so the
    ///    next ClientHello can echo it via the
    ///    `original_destination_connection_id` transport parameter per
    ///    RFC 9000 §7.3).
    /// 2. Replace `local_initial_dcid` + `current_remote_cid` with
    ///    `retry_scid`.
    /// 3. Re-derive `initial_keys` from the new DCID per RFC 9001 §5.2.
    /// 4. Reset `initial_send` + `initial_recv` + `initial_ack_scheduler`
    ///    + `anti_amplification` for the new flight.
    /// 5. Reset `crypto_send_initial`'s send cursor so the BUFFERED
    ///    ClientHello re-sends under the new keys (RFC 9000 §17.2.5 — the
    ///    ClientHello is unchanged; rustls won't re-emit it).
    /// 6. Stash the Retry `token` bytes for the next ClientHello to
    ///    include in its Token field.
    /// 7. Flip `retry_received = true`.
    ///
    /// # Errors
    ///
    /// See [`RetryResetError`].
    pub fn reset_for_retry(
        &mut self,
        retry_scid: &[u8],
        retry_token: &[u8],
    ) -> Result<(), RetryResetError> {
        if self.retry_received {
            return Err(RetryResetError::AlreadyApplied);
        }
        if retry_scid.len() > MAX_CID_LEN {
            return Err(RetryResetError::RetryScidTooLong);
        }
        if retry_token.len() > self.retry_token.capacity() {
            return Err(RetryResetError::TokenTooLong);
        }

        let new_initial_keys = crate::quic::crypto::initial_keys::derive(retry_scid)
            .map_err(RetryResetError::InitialKeysDerive)?;

        // Preserve the ORIGINAL DCID — the one used in the very first
        // Initial flight. Subsequent Retries on top of an
        // already-Retried state are rejected above, so this field
        // captures the truly first DCID exactly once.
        let original = core::mem::take(&mut self.local_initial_dcid);
        self.original_destination_cid = Some(original);

        let mut new_dcid: ConnectionIdBytes = ArrayVec::new();
        // try_extend_from_slice cannot fail — bounds-checked above.
        new_dcid.try_extend_from_slice(retry_scid).ok();
        self.local_initial_dcid = new_dcid.clone();
        self.current_remote_cid = new_dcid;

        self.initial_keys = new_initial_keys;
        self.initial_send = SendSpace::new();
        self.initial_recv = RecvSpace::new();
        self.initial_ack_scheduler = AckScheduler::new();
        self.anti_amplification = AntiAmplificationCounter::new(self.side);
        // RFC 9000 §17.2.5 — the ClientHello does not change in response to a
        // Retry. rustls produces it once and won't re-emit, so re-send the
        // BUFFERED ClientHello (re-encrypted under the new retry-SCID Initial
        // keys, with the token now in the header) rather than clearing it —
        // clearing left `crypto_send_initial` empty, so the client sent no
        // Initial at all after a Retry and the handshake stalled.
        self.crypto_send_initial.reset_for_pto();

        self.retry_token.clear();
        // try_extend_from_slice cannot fail — bounds-checked above.
        self.retry_token.try_extend_from_slice(retry_token).ok();
        self.retry_received = true;
        Ok(())
    }
}

impl EstablishedState {
    /// Borrow the SendSpace for `path_id`. Returns `None` for non-zero
    /// path IDs not yet registered in `path_pn_state`.
    #[must_use]
    pub fn path_send_space(&self, path_id: u32) -> Option<&SendSpace> {
        if path_id == 0 {
            Some(&self.application_send)
        } else {
            self.path_pn_state.get(&path_id).map(|state| &state.send)
        }
    }

    /// Mutable borrow of the SendSpace for `path_id`. Returns `None`
    /// when non-zero path isn't registered.
    pub fn path_send_space_mut(&mut self, path_id: u32) -> Option<&mut SendSpace> {
        if path_id == 0 {
            Some(&mut self.application_send)
        } else {
            self.path_pn_state
                .get_mut(&path_id)
                .map(|state| &mut state.send)
        }
    }

    /// Mutable borrow of the per-path AckScheduler.
    pub fn path_ack_scheduler_mut(&mut self, path_id: u32) -> Option<&mut AckScheduler> {
        if path_id == 0 {
            Some(&mut self.application_ack_scheduler)
        } else {
            self.path_pn_state
                .get_mut(&path_id)
                .map(|state| &mut state.ack_scheduler)
        }
    }

    /// Mutable borrow of the per-path RecvSpace.
    pub fn path_recv_space_mut(&mut self, path_id: u32) -> Option<&mut RecvSpace<128>> {
        if path_id == 0 {
            Some(&mut self.application_recv)
        } else {
            self.path_pn_state
                .get_mut(&path_id)
                .map(|state| &mut state.recv)
        }
    }

    /// Register an entry for `path_id` in `path_pn_state` if not yet
    /// present. Path 0 is implicit — calling this with `path_id = 0`
    /// is a no-op.
    ///
    /// # Errors
    ///
    /// Returns [`PathPnStateError::TableFull`] when the LinearMap is
    /// at capacity (MAX_PATHS_PER_CONNECTION).
    pub fn ensure_path_pn_state(&mut self, path_id: u32) -> Result<(), PathPnStateError> {
        if path_id == 0 {
            return Ok(());
        }
        if self.path_pn_state.contains_key(&path_id) {
            return Ok(());
        }
        self.path_pn_state
            .insert(path_id, PathPnState::default())
            .map(|_| ())
            .map_err(|_| PathPnStateError::TableFull)
    }
}

/// Errors from per-path PN-state operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum PathPnStateError {
    /// Path table at the per-connection cap (MAX_PATHS_PER_CONNECTION).
    TableFull,
}

impl ConnectionState {
    /// Stable static label for diagnostics.
    #[must_use]
    pub const fn label(&self) -> &'static str {
        match self {
            Self::Initial(_) => "Initial",
            Self::Handshake(_) => "Handshake",
            Self::Established(_) => "Established",
            Self::Closing(_) => "Closing",
            Self::Draining(_) => "Draining",
            Self::Closed => "Closed",
        }
    }

    /// The most recent `now` the state has seen (or `Instant::ZERO`
    /// for `Closed`).
    #[must_use]
    pub const fn last_now(&self) -> Instant {
        match self {
            Self::Initial(state) => state.last_now,
            Self::Handshake(state) => state.last_now,
            Self::Established(state) => state.last_now,
            Self::Closing(state) => state.last_now,
            Self::Draining(state) => state.last_now,
            Self::Closed => Instant::ZERO,
        }
    }

    /// Update `last_now` in place; no-op for `Closed`.
    pub fn touch(&mut self, now: Instant) {
        match self {
            Self::Initial(state) => state.last_now = now,
            Self::Handshake(state) => state.last_now = now,
            Self::Established(state) => state.last_now = now,
            Self::Closing(state) => state.last_now = now,
            Self::Draining(state) => state.last_now = now,
            Self::Closed => {}
        }
    }
}

/// Owned copy of [`crate::quic::frame::ConnectionCloseFrame`] suitable for
/// stashing on [`ClosingState`].
///
/// We carry the wire-format type byte (`0x1c` transport-level close
/// or `0x1d` application-level close), the error code, the frame type
/// that triggered the close (transport-level only), and an inline
/// reason phrase capped at 256 bytes. Real peers rarely use more than
/// a few dozen bytes of reason; 256 is comfortable headroom.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConnectionCloseFrameOwned {
    pub frame_type: u8,
    pub error_code: u64,
    pub triggering_frame_type: Option<u64>,
    pub reason: ArrayVec<u8, 256>,
}

impl ConnectionCloseFrameOwned {
    /// Build an application-level close (frame type `0x1d`).
    #[must_use]
    pub fn application(error_code: u64, reason: &[u8]) -> Self {
        let mut owned_reason: ArrayVec<u8, 256> = ArrayVec::new();
        let copy_len = core::cmp::min(reason.len(), owned_reason.capacity());
        // try_extend_from_slice cannot fail because of the min cap above.
        owned_reason.try_extend_from_slice(&reason[..copy_len]).ok();
        Self {
            frame_type: 0x1d,
            error_code,
            triggering_frame_type: None,
            reason: owned_reason,
        }
    }

    /// Build a transport-level close (frame type `0x1c`).
    #[must_use]
    pub fn transport(error_code: u64, triggering_frame_type: u64, reason: &[u8]) -> Self {
        let mut owned_reason: ArrayVec<u8, 256> = ArrayVec::new();
        let copy_len = core::cmp::min(reason.len(), owned_reason.capacity());
        owned_reason.try_extend_from_slice(&reason[..copy_len]).ok();
        Self {
            frame_type: 0x1c,
            error_code,
            triggering_frame_type: Some(triggering_frame_type),
            reason: owned_reason,
        }
    }

    /// Borrow as the wire-format [`Frame::ConnectionClose`] variant for
    /// encoding via the C3 frame codec.
    #[must_use]
    pub fn as_frame(&self) -> Frame<'_> {
        Frame::ConnectionClose {
            error_code: self.error_code,
            frame_type: self.triggering_frame_type,
            reason: &self.reason,
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn state_label_matches_variant() {
        let closed = ConnectionState::Closed;
        assert_eq!(closed.label(), "Closed");
    }

    #[test]
    fn touch_updates_last_now_for_draining() {
        let mut state = ConnectionState::Draining(DrainingState {
            last_now: Instant::from_micros(100),
            drain_deadline: Instant::from_micros(1000),
        });
        state.touch(Instant::from_micros(200));
        assert_eq!(state.last_now(), Instant::from_micros(200));
    }

    #[test]
    fn touch_is_noop_for_closed() {
        let mut state = ConnectionState::Closed;
        state.touch(Instant::from_micros(123));
        assert_eq!(state.last_now(), Instant::ZERO);
    }

    #[test]
    fn application_close_carries_reason_and_type() {
        let close = ConnectionCloseFrameOwned::application(0x2a, b"bye");
        assert_eq!(close.frame_type, 0x1d);
        assert_eq!(close.error_code, 0x2a);
        assert_eq!(close.reason.as_slice(), b"bye");
        assert_eq!(close.triggering_frame_type, None);
    }

    #[test]
    fn transport_close_carries_triggering_frame_type() {
        let close = ConnectionCloseFrameOwned::transport(0x07, 0x06, b"boom");
        assert_eq!(close.frame_type, 0x1c);
        assert_eq!(close.error_code, 0x07);
        assert_eq!(close.triggering_frame_type, Some(0x06));
        assert_eq!(close.reason.as_slice(), b"boom");
    }

    #[test]
    fn close_reason_truncates_at_inline_cap() {
        let big = [0xAA; 512];
        let close = ConnectionCloseFrameOwned::application(0, &big);
        assert_eq!(close.reason.len(), 256);
    }

    #[test]
    fn crypto_recv_delivers_in_order_fragment_immediately() {
        let mut reassembler = CryptoRecvBuffer::new();
        assert_eq!(reassembler.accept(0, b"hello"), Some(&b"hello"[..]));
    }

    #[test]
    fn crypto_recv_buffers_gap_then_delivers_run_on_fill() {
        let mut reassembler = CryptoRecvBuffer::new();
        // A fragment past offset 0 leaves a head gap — nothing deliverable.
        assert_eq!(reassembler.accept(5, b"world"), None);
        // The offset-0 filler makes the whole run contiguous in one call.
        assert_eq!(reassembler.accept(0, b"hello"), Some(&b"helloworld"[..]));
    }

    #[test]
    fn crypto_recv_reassembles_out_of_order_multi_fragment() {
        // Mirrors curl's ngtcp2 ClientHello: CRYPTO frames land at
        // non-zero, out-of-order offsets and only become deliverable once
        // the offset-0 fragment arrives — the bug that broke interop.
        let mut reassembler = CryptoRecvBuffer::new();
        let stream: Vec<u8> = (0..20u8).collect();
        assert_eq!(reassembler.accept(15, &stream[15..20]), None); // tail
        assert_eq!(reassembler.accept(5, &stream[5..10]), None); // middle
        assert_eq!(reassembler.accept(10, &stream[10..15]), None); // bridge
        // Head arrives last → drains 0..5 then every buffered run in order.
        assert_eq!(reassembler.accept(0, &stream[0..5]), Some(&stream[..]));
    }

    #[test]
    fn crypto_recv_ignores_duplicate_and_clips_overlap() {
        let mut reassembler = CryptoRecvBuffer::new();
        assert_eq!(reassembler.accept(0, b"abcdef"), Some(&b"abcdef"[..]));
        // Wholly-old duplicate — no re-delivery.
        assert_eq!(reassembler.accept(0, b"abc"), None);
        // Partial overlap — only the genuinely-new tail is delivered.
        assert_eq!(reassembler.accept(4, b"efghij"), Some(&b"ghij"[..]));
    }

    #[test]
    fn crypto_recv_drops_fragment_past_capacity_without_panic() {
        let mut reassembler = CryptoRecvBuffer::new();
        assert_eq!(reassembler.accept(CRYPTO_RECV_BYTES as u64, b"x"), None);
    }
}
