#!/usr/bin/env bash
# runs the proxima-intercept capture bench (compare-bench vs std::fs::write)
# and writes a results table to
# proxima-intercept/benches/RESULTS_bench_intercept_capture_<platform>.md.
#
# this script is the per-component bench substrate per Principle 16: numbers
# without a re-runnable harness are hypothesis. running it and committing the
# results MD is the contract.

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=./_bench-common.sh
source "${script_dir}/_bench-common.sh"

crate_dir="$(cd "$script_dir/.." && pwd)"
cd "$crate_dir"

platform="$(detect_platform)"
# Respect CARGO_TARGET_DIR if the user has redirected the build cache; otherwise
# fall back to the workspace's default target/ directory.
target_root="${CARGO_TARGET_DIR:-target}"
CRITERION_DIR="${target_root}/criterion"
# mktemp -d avoids the TOCTOU symlink trap that a fixed /tmp path opens up;
# critical on shared CI hosts.
LOGS_DIR="$(mktemp -d -t bench-intercept-capture-logs.XXXXXX)"
trap 'rm -rf "${LOGS_DIR}"' EXIT

results_file="proxima-intercept/benches/RESULTS_bench_intercept_capture_${platform}.md"

declare -a BENCH_GROUPS=(
    "capture_typical_post_turn"
    "capture_streaming_chunks"
)

declare -a ARMS_TYPICAL_POST=(
    "proxima"
    "incumbent_fs_write"
)

declare -a ARMS_STREAMING=(
    "proxima_chunk_push"
    "incumbent_append_per_chunk"
)

declare -a DESIGN_FAVORS_TYPICAL_POST=(
    "incumbent"
    "incumbent"
)

declare -a DESIGN_FAVORS_STREAMING=(
    "neutral"
    "neutral"
)

printf 'bench-intercept-capture: platform=%s\n' "$platform"

run_group() {
    local group="$1"
    printf -- '--- running %s ---\n' "$group"
    set +e
    cargo bench \
        -p proxima-intercept \
        --features intercept-capture \
        --bench bench_intercept_capture \
        -- "$group" \
        2>&1 | tee "${LOGS_DIR}/${group}.log"
    local exit_code=("${PIPESTATUS[@]}")
    set -e
    # Bench may legitimately exit non-zero on a fully missing group filter
    # (criterion treats "no benchmark matched filter" as exit 1). Surface any
    # non-zero exit on the cargo side as a warning so a compile failure does
    # not silently fall through to a "pending" result row.
    if [[ "${exit_code[0]}" != "0" ]]; then
        printf 'warn: cargo bench exited %s for group %s; results may be stale or missing\n' \
            "${exit_code[0]}" "$group" >&2
    fi
}

for group in "${BENCH_GROUPS[@]}"; do
    run_group "$group"
done

format_ns_as_throughput() {
    local mean_ns="$1"
    local bytes="$2"
    if [[ "$mean_ns" == "pending" || -z "$bytes" || "$bytes" == "0" ]]; then
        printf 'pending'
        return
    fi
    awk -v ns="$mean_ns" -v bytes="$bytes" '
        BEGIN {
            seconds = ns / 1e9
            bytes_per_sec = bytes / seconds
            if (bytes_per_sec >= 1024 * 1024) {
                printf "%.2f MiB/s", bytes_per_sec / (1024 * 1024)
            } else if (bytes_per_sec >= 1024) {
                printf "%.2f KiB/s", bytes_per_sec / 1024
            } else {
                printf "%.0f B/s", bytes_per_sec
            }
        }
    '
}

format_ns_pretty() {
    local mean_ns="$1"
    if [[ "$mean_ns" == "pending" ]]; then
        printf 'pending'
        return
    fi
    awk -v ns="$mean_ns" '
        BEGIN {
            if (ns >= 1e6) {
                printf "%.2f ms", ns / 1e6
            } else if (ns >= 1e3) {
                printf "%.2f µs", ns / 1e3
            } else {
                printf "%.0f ns", ns
            }
        }
    '
}

# typical-post bytes per iter: request_wire(245) + request_body(195) +
# response_head(~150) + response_body(1771) ≈ 2361. use 2361 as the throughput
# divisor (matches Throughput::Bytes set in the bench).
TYPICAL_POST_BYTES=2361
# streaming-chunks bytes per iter: 32 chunks × ~46 bytes = 1472
STREAMING_CHUNKS_BYTES=1472

emit_row() {
    local group="$1"
    local arm="$2"
    local design_favors="$3"
    local bytes_divisor="$4"
    local estimates_file
    estimates_file="$(find_estimates "$CRITERION_DIR" "$group" "$arm")"
    local mean_ns
    mean_ns="$(extract_mean_ns "$estimates_file")"
    local cov
    cov="$(extract_cov "$estimates_file")"
    local time_pretty
    time_pretty="$(format_ns_pretty "$mean_ns")"
    local throughput_pretty
    throughput_pretty="$(format_ns_as_throughput "$mean_ns" "$bytes_divisor")"
    printf '| %s | %s | %s | %s | %s |\n' \
        "$arm" "$time_pretty" "$throughput_pretty" "$cov" "$design_favors"
}

mkdir -p "$(dirname "$results_file")"

cat > "$results_file" << EOF
# bench_intercept_capture results — platform=${platform}

Generated by \`scripts/bench-intercept-capture.sh\`. Re-running this script
regenerates this file in place; commit the file to version the baseline.

Workspace: proxima-intercept. Feature: \`intercept-capture\`. Criterion:
100 measurements/group, 3s measurement_time, html_reports enabled.

## capture_typical_post_turn

| arm | time/iter | thrpt | CoV | design-favors |
|---|---|---|---|---|
EOF

for ((idx=0; idx<${#ARMS_TYPICAL_POST[@]}; idx++)); do
    emit_row "capture_typical_post_turn" \
        "${ARMS_TYPICAL_POST[$idx]}" \
        "${DESIGN_FAVORS_TYPICAL_POST[$idx]}" \
        "$TYPICAL_POST_BYTES" >> "$results_file"
done

cat >> "$results_file" << EOF

## capture_streaming_chunks

| arm | time/iter | thrpt | CoV | design-favors |
|---|---|---|---|---|
EOF

for ((idx=0; idx<${#ARMS_STREAMING[@]}; idx++)); do
    emit_row "capture_streaming_chunks" \
        "${ARMS_STREAMING[$idx]}" \
        "${DESIGN_FAVORS_STREAMING[$idx]}" \
        "$STREAMING_CHUNKS_BYTES" >> "$results_file"
done

cat >> "$results_file" << EOF

## Honest read

proxima loses against incumbent (\`std::fs::write\`) on the incumbent's home
turf (single blob persistence, no parse/redact/frame). this is the deliberate
trade for typed event framing + auth redaction + replay via ReplayUpstream.
typical bandwidth budgets (LLM streaming ~MB/s) are well within the
~ms-per-turn cost.
EOF

printf '\nwrote %s\n' "$results_file"
