#!/usr/bin/env bash
# runs the proxima par.rs vs rayon comparison bench across three workload
# groups and writes a results table to benches/RESULTS_bench-vs-rayon_<platform>.md.
# only covers shapes proxima par.rs actually implements — NOT a full rayon
# surface comparison. see docs/bench-suite/discipline-bench-vs-rayon.md.

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=./_bench-common.sh
source "${script_dir}/_bench-common.sh"

crate_dir="$(cd "$script_dir/.." && pwd)"
cd "$crate_dir"

platform="$(detect_platform)"

FEATURES="http1,http2,tcp,tls,runtime-tokio,runtime-prime-full,runtime-prime-bgpool-rayon,runtime-prime-bgpool-par,runtime-prime-bgpool-async,rayon"
CRITERION_DIR="target/criterion"
LOGS_DIR="/tmp/bench-vs-rayon-logs"
mkdir -p "$LOGS_DIR"

results_file="benches/RESULTS_bench-vs-rayon_${platform}.md"

# arms we care about per workload group (the groups that exist in bench_background_pool)
# TODO: extend arm list when proxima_par_each lands (currently only reduce/map shapes)
declare -a GROUPS=(
    "bg_pool_tiny_jobs"
    "bg_pool_cpu_imbalanced"
    "bg_pool_fork_join"
)

# arms relevant to the vs-rayon comparison (subset of all arms in the bench file)
declare -a RAYON_ARMS=(
    "proxima_typed"
    "proxima_dyn"
    "proxima_par_reduce_512"
    "proxima_par_reduce_2048"
    "proxima_par_reduce_8192"
    "proxima_par_iter_map_sum"
    "proxima_par_iter_map_collect"
    "proxima_par_iter_map_async_sum"
    "proxima_par_stream_then_16"
    "proxima_par_stream_then_64"
    "proxima_par_stream_then_ordered_64"
    "rayon"
    "rayon_par_iter"
    "rayon_via_bgpool"
    "proxima_rayon_backed"
    "tokio_spawn_blocking"
)

printf 'bench-vs-rayon: platform=%s\n' "$platform"

run_group() {
    local group="$1"
    printf -- '--- running %s ---\n' "$group"
    cargo bench \
        --no-default-features \
        --features "$FEATURES" \
        --bench bench_background_pool \
        -- "$group" \
        2>&1 | tee "${LOGS_DIR}/${group}.log" || true
}

# run all three groups sequentially; criterion writes criterion/ output for each
for group in "${GROUPS[@]}"; do
    run_group "$group"
done

# get_rayon_mean <group> <arm> — returns formatted time string or "n/a"
get_rayon_mean() {
    local group="$1"
    local arm="$2"
    local estimates_file
    estimates_file="$(find_estimates "$CRITERION_DIR" "$group" "$arm")"
    if [[ -z "$estimates_file" ]]; then
        printf 'n/a'
        return
    fi
    local mean_ns
    mean_ns="$(extract_mean_ns "$estimates_file")"
    format_time_ns "$mean_ns"
}

# get_rayon_cov <group> <arm> — returns CoV string or "n/a"
get_rayon_cov() {
    local group="$1"
    local arm="$2"
    local estimates_file
    estimates_file="$(find_estimates "$CRITERION_DIR" "$group" "$arm")"
    extract_cov "$estimates_file"
}

# get_rayon_raw_ns <group> <arm> — returns raw ns integer or "n/a"
get_rayon_raw_ns() {
    local group="$1"
    local arm="$2"
    local estimates_file
    estimates_file="$(find_estimates "$CRITERION_DIR" "$group" "$arm")"
    if [[ -z "$estimates_file" ]]; then
        printf 'n/a'
        return
    fi
    extract_mean_ns "$estimates_file"
}

# write the results markdown file
{
    printf '**par.rs is not a drop-in rayon replacement. This bench compares proxima'\''s par_reduce / par_each / par_map_collect (sync + async) against rayon on the shapes par.rs actually implements. Rayon'\''s par_filter, par_sort_*, par_chunks_mut, scope, install, par_bridge are out of scope.**\n\n'
    printf 'Platform: `%s`. Generated by `scripts/bench-vs-rayon.sh`.\n\n' "$platform"
    printf 'Unit: mean wall time from criterion `estimates.json` (lower is better).\n'
    printf 'CoV: std_dev / mean as reported by criterion.\n\n'

    for group in "${GROUPS[@]}"; do
        printf '## %s\n\n' "$group"
        printf '| arm | %s mean | %s CoV | Linux mean | Linux CoV | notes |\n' \
            "$(printf '%s' "$platform" | tr '[:lower:]' '[:upper:]')" \
            "$(printf '%s' "$platform" | tr '[:lower:]' '[:upper:]')"
        printf '|-----|---------|--------|------------|-----------|-------|\n'

        for arm in "${RAYON_ARMS[@]}"; do
            raw="$(get_rayon_raw_ns "$group" "$arm")"
            mean="$(get_rayon_mean "$group" "$arm")"
            cov="$(get_rayon_cov "$group" "$arm")"

            # only print the arm if it has data or is a rayon/proxima_par arm
            # (we want n/a rows for context rather than silently omitting them)
            if [[ "$raw" == "n/a" && "$arm" != rayon* && "$arm" != proxima_par* && "$arm" != proxima_rayon* && "$arm" != tokio* ]]; then
                continue
            fi

            notes=""
            case "$arm" in
                rayon_par_iter)          notes="rayon recursive split + work-steal" ;;
                rayon)                   notes="rayon dyn dispatch" ;;
                rayon_via_bgpool)        notes="rayon pool inside bgpool wrapper" ;;
                proxima_rayon_backed)    notes="proxima typed API on rayon pool" ;;
                tokio_spawn_blocking)    notes="control" ;;
                proxima_par_reduce_512)  notes="threshold=512" ;;
                proxima_par_reduce_2048) notes="threshold=2048" ;;
                proxima_par_reduce_8192) notes="threshold=8192" ;;
                proxima_par_iter_map_async_sum) notes="async map variant" ;;
                proxima_par_stream_then_16)     notes="buffered concurrency, cap=16" ;;
                proxima_par_stream_then_64)     notes="buffered concurrency, cap=64" ;;
                proxima_par_stream_then_ordered_64) notes="ordered reorder buf, cap=64" ;;
                *) notes="" ;;
            esac

            if [[ "$platform" == "m1" ]]; then
                printf '| %s | %s | %s | pending | pending | %s |\n' \
                    "$arm" "$mean" "$cov" "$notes"
            else
                printf '| %s | pending | pending | %s | %s | %s |\n' \
                    "$arm" "$mean" "$cov" "$notes"
            fi
        done

        printf '\n'
    done
} > "$results_file"

printf 'wrote %s\n' "$results_file"
