//! Sans-IO HTTP/1.x codec — request parser, body decoder, connection
//! state machine, response writer. Extracted from `proxima-h1` for the
//! no_std + alloc cliff.
//!
//! Layers:
//!
//! - [`h1`]: request-line + header parsing.
//! - [`h1_body`]: chunked / content-length body decoder.
//! - [`h1_connection`]: per-connection state machine + keep-alive
//!   bookkeeping.
//! - [`h1_response`]: response head + body encoder.
//! - [`h1_client`]: client inverse — request-head encoder + response-head
//!   parser (the bytes a client writes / reads).
//!
//! # Tier
//!
//! Compiles under `#![no_std]` with `alloc`. `--no-default-features
//! --features http1_codec-no-alloc` builds tier-3 (`core::*` only) —
//! exposing just the streaming request-head parser subset
//! ([`h1::parse_head_streaming`], [`h1::Header`],
//! [`h1::StreamingStatus`], [`h1::ParserLimits`]), which pushes
//! borrowed offsets into caller storage and never touches a heap. The
//! body decoder / connection FSM / response writer / owned-`RequestHead`
//! surface require `alloc`.
//!
//! The std IO adapter over this sans-IO core is `proxima-http::http1`; it
//! owns the tokio client pool + listener glue and stays `std` by design —
//! the absence of `no_std` there is intentional, not an oversight.

/// Build-time sizing constant generated by `build.rs` from
/// `http1_codec.toml` (+ optional `PROXIMA_PROTOCOLS_HTTP1_CODEC_*` env
/// override): the inline capacity of the `SmallVec` backing
/// [`h1::RequestHead::headers`]. Only meaningful on the alloc tier —
/// the bare no_std no-alloc subset never builds that type. Deliberately
/// NOT reused by [`frame_codec_pipe::OwnedFrame::headers`], which stays
/// a plain `Vec` — see that field's doc for why inlining it measured
/// as a net latency loss.
#[cfg(not(feature = "http1_codec-no-alloc"))]
pub mod sized {
    include!(concat!(
        env!("OUT_DIR"),
        "/proxima_protocols_http1_codec_sized.rs"
    ));
}

#[cfg(all(
    feature = "http1_codec-codec-trait",
    not(feature = "http1_codec-no-alloc")
))]
pub mod codec_trait;
#[cfg(all(
    feature = "http1_codec-frame-pipe",
    not(feature = "http1_codec-no-alloc")
))]
pub mod frame_codec_pipe;
pub mod h1;
#[cfg(not(feature = "http1_codec-no-alloc"))]
pub mod h1_body;
#[cfg(not(feature = "http1_codec-no-alloc"))]
pub mod h1_client;
#[cfg(not(feature = "http1_codec-no-alloc"))]
pub mod h1_connection;
#[cfg(not(feature = "http1_codec-no-alloc"))]
pub mod h1_response;

#[cfg(all(
    feature = "http1_codec-codec-trait",
    not(feature = "http1_codec-no-alloc")
))]
pub use codec_trait::{FrameError as H1FrameError, H1RequestCodec};
// `FrameCodecPipe` itself now lives at `crate::codec_pipe::FrameCodecPipe` —
// generic over ANY `FrameCodec`, not re-exported per-protocol. Consumers
// spell it `proxima_protocols::codec_pipe::FrameCodecPipe<H1RequestCodec>`.
#[cfg(all(
    feature = "http1_codec-frame-pipe",
    not(feature = "http1_codec-no-alloc")
))]
pub use frame_codec_pipe::{
    H1RequestFrame, H1RequestFrameCodec, H1RequestFrameError, OwnedFrame, OwnedHeader,
};
