//! Sans-IO QUIC + TLS 1.3 protocol implementation per RFC 9000 / 9001 / 9002
//! / 9221 + multipath draft. Publicly consumable outside proxima — designed
//! to be driven from any I/O loop (DPDK / SPDK / AF_XDP / embedded / fuzzer
//! / in-process test harness).
//!
//! No I/O traits in the signature. No `async`. No `tokio`. No `std::net`.
//! No `prime`. Bytes in (`&[u8]` + peer ID + monotonic `now` + crypto-rng),
//! events + outbound datagram descriptors out. The caller owns the wire.
//!
//! # Layout (filled in by components C1..C27 — empty at A0)
//!
//! Codec leaves (target tier-3):
//!
//! - `varint` — RFC 9000 §16 variable-length integer encoding.
//! - `packet::{header, payload}` — long / short / retry / version-neg.
//! - `frame` — all 28 RFC 9000 §19 frame types + RFC 9221 DATAGRAM.
//! - `transport_parameters` — RFC 9000 §18 + extension params (ECN,
//!   multipath, RFC 9221 max_datagram_frame_size).
//! - `packet_number` — encode / decode + truncation arithmetic.
//! - `connection_id` — fixed-length byte string per RFC 9000 §5.1.
//! - `range_set` — `ArrayRangeSet<MAX>` for ACK ranges.
//!
//! Crypto leaves (target tier-3, composes aws-lc-rs):
//!
//! - `crypto::expand_label` — HKDF-Expand-Label per RFC 9001 §5.2.
//! - `crypto::aead` — in-place packet protection per RFC 9001 §5.1.
//! - `crypto::header_protection` — mask generation per RFC 9001 §5.4.
//! - `crypto::initial_keys` — initial-secret derivation per RFC 9001 §5.2.
//! - `crypto::key_update` — phase tracking per RFC 9001 §6.
//!
//! TLS sans-IO (tier-1; composes rustls + aws-lc-rs no_std + alloc, or
//! inline TLS state machine spike if upstream rustls gaps too large):
//!
//! - `tls::handshake` — TLS 1.3 handshake feed for QUIC CRYPTO frames.
//! - `tls::secrets` — secret derivation routed into AEAD / header protection.
//!
//! State machines (tier-1 — alloc-required for unbounded state):
//!
//! - `streams::{send, recv, table}` — uni / bi flow control (RFC 9000 §4).
//! - `ack::{ranges, scheduler}` — ACK generation per RFC 9000 §13.2.
//! - `loss_detection` — PTO + persistent congestion per RFC 9002 §6.
//! - `congestion::{newreno, cubic, bbrv2}` — RFC 9002 §7 + RFC 9438 + BBRv2 draft.
//! - `ecn` — codepoint marking + congestion signal per RFC 9000 §13.4.
//! - `datagram` — RFC 9221 unreliable DATAGRAM send / recv queues.
//! - `multipath::{path, scheduler}` — draft-ietf-quic-multipath.
//! - `path_validation` — PATH_CHALLENGE / PATH_RESPONSE per RFC 9000 §9.
//! - `version_negotiation` — RFC 9000 §6.
//! - `address_validation` — retry tokens per RFC 9000 §8.
//! - `zero_rtt` — RFC 9001 §4.6 + anti-replay considerations.
//! - `connection::{state, transmit, event}` — discriminated enum FSM
//!   (Initial / Handshake / Established / Closing / Draining / Closed).
//! - `endpoint::demux` — DCID table + retry / VN dispatch.
//!
//! # Tier
//!
//! `--no-default-features --features quic` builds tier-3 with `core::*`
//! only — exposes the leaf module subset (crypto leaves, varint, packet
//! header/frame parse, connection_id). `--features quic-alloc` builds
//! tier-1 with `core::*` + `alloc::*` — adds `connection`, `streams`,
//! `endpoint`, `datagram`.
//!
//! The std IO adapter over this sans-IO core is `proxima-quic`; it owns the
//! endpoint/socket IO edge and stays `std` by design — the absence of
//! `no_std` there is intentional, not an oversight.
//!
//! Discipline per `pty-tester/docs/proxima-pty/guiding-principles.md`
//! principle 11 (sans-IO must be enum-shaped state machine, low/no alloc,
//! extreme benching, extreme performance) is binding for every component.

/// Build-time sizing constants generated by `build.rs` from `quic.toml`,
/// with optional `PROXIMA_PROTOCOLS_QUIC_*` env overrides. Every
/// const-generic cap in this module threads through these values so
/// downstream consumers can re-tune via the TOML or env at build time
/// without forking the source.
pub mod sized {
    include!(concat!(env!("OUT_DIR"), "/proxima_protocols_quic_sized.rs"));
}

pub mod ack;
pub mod anti_amplification;
#[cfg(feature = "quic-codec-trait")]
pub mod codec_trait;
#[cfg(feature = "quic-codec-trait")]
pub use codec_trait::{QuicCodecError, QuicFrameCodec};
pub mod congestion;
#[cfg(feature = "quic-alloc")]
pub mod connection;
pub mod connection_id;
pub mod crypto;
#[cfg(feature = "quic-alloc")]
pub mod datagram;
pub mod ecn;
pub mod endpoint;
pub mod frame;
pub mod key_update;
pub mod loss;
pub mod multipath;
pub mod packet;
pub mod packet_number;
pub mod path;
pub mod range_set;
pub mod retry_token;
pub mod side;
pub mod streams;
pub mod time;
pub mod tls;
pub mod transport_parameters;
pub mod varint;
pub mod zero_rtt;
